### ISSUE TITLE
[Documentation] Add a Code of conduct

### ISSUE THREAD

**Issue by Chaves2021** [sukeesh/Jarvis#1023]
Document recommended by project's [Community Standards](https://github.com/sukeesh/Jarvis/community)

* Definition by code of conduct by open source guide:
_A code of conduct is a document that establishes expectations for behavior for your project’s participants. Adopting, and enforcing, a code of conduct can help create a positive social atmosphere for your community._

* Objective of the document by open source guide:
_Facilitate healthy and constructive community behavior by adopting and enforcing a code of conduct._

More infos about the document: https://opensource.guide/code-of-conduct/

There is a very good template on the section of _Code of conduct_ in the link above, which just needs to put a contact to receive occurrences of unacceptable behavior if occurs

**Comment by pnhofmann** [comment]
Don't think we currently have need for a code of conduct.
