### ISSUE TITLE
New idea for plugin 

### ISSUE THREAD

**Issue by ampatzidhs** [sukeesh/Jarvis#1028]
I have an idea for a new plugin, a little game. The name of the game is guess the number.
Basically Jarvis thinks of any number between 1-100 and the user tries to guess it. In every guess if the user doesn't find the number, Jarvis informs whether the number they are thinking of is bigger or smaller than the one the user guessed. The user keeps guessing until they find the number or until they are out of lives. Would you be interested in me implementing this feature ?

**Comment by pnhofmann** [comment]
Hey, sure! Go for it.

**Comment by ampatzidhs** [comment]
I just submitted the pull request. I hope it is good!

**Comment by pnhofmann** [comment]
#1035
