### ISSUE TITLE
Help needed: Cannot start jarvis on my machine

### ISSUE THREAD

**Issue by Franc15** [sukeesh/Jarvis#1032]
I had gone through the documentation to start Jarvis in my local environment but after installing Jarvis using the 'python installer' command, running 'jarvis' on the command line says command not found. Any help on this, please?

**Comment by ekorchmar** [comment]
What is your system? Does "python -m jarvis work"?

**Comment by Franc15** [comment]
I'm running on windows 11 x64 machine. The "python -m jarvis" does not work also

**Comment by pnhofmann** [comment]
Hey!

Actually would be ``python 'jarviscli'``.

But try double-clicking ``jarvis.bat``.

------

You would probably need to add your jarvis installation folder to PATH 
https://www.wikihow.com/Change-the-PATH-Environment-Variable-on-Windows

OR

Copy jarvis.bat to a folder that is in PATH

OR

Always use absolute path when starting jarvis

**Comment by pnhofmann** [comment]
Closing, please re-open if issue persists or you have any more questsions
