### ISSUE TITLE
Make evaluate method to work with keyword calculate too

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#104]

**Comment by kritisingh1** [comment]
Hi @StefanosChaliasos . I would like to contribute to this project. I am a beginner and this would be my first contribution in open source. Please let me know if I may. Also if possible, can you provide a brief description about what exactly am I supposed to do and how?

**Comment by StefanosChaliasos** [comment]
Absolutely you can contribute! In [CmdInterpreter.py](https://github.com/sukeesh/Jarvis/blob/master/Jarvis/CmdInterpreter.py) you could see how we handle the exit, goodbye, quit commands with the function close. You could handle that issue with the same logic.

**Comment by appi147** [comment]
hi @StefanosChaliasos  added PR#116  for this issue
