### ISSUE TITLE
christmas timer 

### ISSUE THREAD

**Issue by pap35000** [sukeesh/Jarvis#1041]
Create a timer that calculates how many days,hour,minutes for christmas.

**Comment by FlynnOwen** [comment]
Am I able to work on this?

**Comment by pnhofmann** [comment]
@FlynnOwen 
He already pushed a PR, see #1042

But if you want to do something, pick any file in this project - preferable a feature you find useful - and try to improve it. Or add something new.

**Comment by FlynnOwen** [comment]
Thanks @pnhofmann, I've added a new [plugin](https://github.com/sukeesh/Jarvis/pull/1046).
