### ISSUE TITLE
Quote feature not working

### ISSUE THREAD

**Issue by malhaar2002** [sukeesh/Jarvis#1063]
The "quote of the day" feature is not working. I would like to work on this issue. Thank you

![image](https://user-images.githubusercontent.com/58373047/227590669-d4158a3f-af82-4002-9312-daf5c71a4c8b.png)

**Comment by pnhofmann** [comment]
Hi, sure! Unfortunately can't reproduce, so your help is appreciated ;).

**Comment by malhaar2002** [comment]
Hey, I've added a PR fixing this issue. Could you check it out? Thank you.
