### ISSUE TITLE
Rockpaperscissors game throws exception when user enters string for enter number of rounds prompt.

### ISSUE THREAD

**Issue by TirumanidasKarthik** [sukeesh/Jarvis#1070]
Here is the file and line responsible for the issue.

 File "C:\Users\karth\projects\Jarvis\jarviscli\plugins\rockpaperscissors.py", line 117, in get_rounds
    if (int(rounds) <= 100):

**Comment by TirumanidasKarthik** [comment]
I have fixed this and submitted a pull request for the same.

**Comment by pnhofmann** [comment]
Thx
#1071
