### ISSUE TITLE
Idea for food nutrion command

### ISSUE THREAD

**Issue by aspiring-aster** [sukeesh/Jarvis#1074]
A feature where users can specify a food they want the nutritional information from. This command can be simple such as listing food "food_name" and it can be implemented via a API that grabs nutritional information from something such as my fitness pal or any other online database. It doesn't have to cover every food but something for common types of food would be good! 
This is up for grabs since I'm not sure if I can find the time to complete this any time soon!

**Comment by jhutchings99** [comment]
I would like to work on this!

**Comment by aspiring-aster** [comment]
@jhutchings99 Go for it! If you need any ideas for a potential API, I'll be more than happy to help!
