### ISSUE TITLE
New feature request: Bored API

### ISSUE THREAD

**Issue by Eraisuithon** [sukeesh/Jarvis#1085]
The Bored API helps you find things to do when you're bored.
The suggestion holds information about the fields like the number of participants, activity type, and more.
A rest API request will be made from: https://www.boredapi.com

**Comment by jhutchings99** [comment]
Hey @Eraisuithon! Are you working on implementing this issue? If not please let me know as I would love to work on it!

**Comment by Eraisuithon** [comment]
Hey @jhutchings99 I already finished it today.
When my merge is accepted you can improve it however you want!

**Comment by pnhofmann** [comment]
#1088

Please re-open if you have any suggestions for improvement
