### ISSUE TITLE
Object oriented approach not followed

### ISSUE THREAD

**Issue by Prakash2403** [sukeesh/Jarvis#110]
If you consider a feature as an `Action,` then there is a `has-a` relationship between `Jarvis` and `Action`. Also, you can make an abstract class `Action`, then inherit this class to define all features. Doing this will make your code more flexible and elegant.

If you like my suggestion, then I am ready to work on this issue.

**Comment by StefanosChaliasos** [comment]
That is a huge change!! If you could make a PR it will be great

**Comment by Prakash2403** [comment]
@StefanosChaliasos I know it will be a huge change, but in order to make this project a great project, software engineering principles and OOP must be followed. 

I can't do this change alone. I think we should create a separate branch and start working there. What do you think @StefanosChaliasos @sukeesh ?

**Comment by Prakash2403** [comment]
Hey @StefanosChaliasos @sukeesh , Can you please create a branch to start OOP development?

**Comment by StefanosChaliasos** [comment]
Done!

**Comment by pnhofmann** [comment]
Any progress?

Just asking because my plugin-concept would most likely be highly incompatible to anything you would do for this issue. So if someone is currently working on this, please tell me now ;).

**Comment by appi147** [comment]
No, go ahead

**Comment by Colbyter** [comment]
@Prakash2403  @pnhofmann  @StefanosChaliasos  You guys still are working on the OOP Branch? Please let me know if I can contribute somehow. I'm still quite a beginner in the OSS world.

**Comment by appi147** [comment]
@Colbyter We decided to go ahead with plugin-manager concept. If you would like to add new features, feel free to create a PR.
