### ISSUE TITLE
Suggestion to improve on calculator GUI

### ISSUE THREAD

**Issue by dinanz** [sukeesh/Jarvis#1105]
![image](https://user-images.githubusercontent.com/60189142/235822112-ca73eac0-7947-42af-8aed-7fc1ff103f42.png)
Suggestion to improve on the UI for the calculator.

**Comment by cruncherino** [comment]
I can work on this

**Comment by cruncherino** [comment]
Done, pull request #1135

**Comment by pnhofmann** [comment]
#1135
