### ISSUE TITLE
Store actions in file.

### ISSUE THREAD

**Issue by Prakash2403** [sukeesh/Jarvis#111]
Actions which are stored in a dictionary in `CmdInterpreter.py`, should be stored in a file. Storing them in dictionary violates `open close principle`. Also, add a method `add_action(*args, **kwargs)`, which will add actions to that file without manually opening that file. Doing this will make your code open for extension but closed for modification`(Open Close Principle)`

**Comment by StefanosChaliasos** [comment]
@sukeesh  what do you think about that?

**Comment by sukeesh** [comment]
@StefanosChaliasos This would be nice. @Prakash2403 If you can, please make a PR.

**Comment by brunocasarotti** [comment]
Hey, is anyone working on that? This is an issue that I would like to work on. 
Are you thinking about saving it on a plain text file, a json file or what?

**Comment by appi147** [comment]
@sukeesh
