### ISSUE TITLE
Unexpected output in Plot

### ISSUE THREAD

**Issue by palash018** [sukeesh/Jarvis#1116]
i tried to plot y=constant it works well but when i do same with x it should make a vertical line instead it makes this

![image](https://github.com/sukeesh/Jarvis/assets/109908523/9f27cd11-8432-47ae-9d74-a0a82ea09908)

**Comment by kapoorkrish** [comment]
Hello! I'll see if I can make a PR and replace SymPy (which is what it is currently) with matplotlib for better rendering and fixing this issue.

**Comment by kapoorkrish** [comment]
Hello, please see #1120
