### ISSUE TITLE
bug: "solve" and "calculate" commands in evaluator.py not working and throwing error

### ISSUE THREAD

**Issue by daredevil0905** [sukeesh/Jarvis#1131]
## Description
I tried executing the `solve` and `calculate` commands given in the `evaluator.py` plugin. I tried `solve x + 3 = 5` and `calculate 3 + 5` however in both cases I was thrown the following error:

![Screenshot 2023-08-27 220723](https://github.com/sukeesh/Jarvis/assets/130159643/1716e459-5d1b-4807-b8f2-898313698f11)

## Proposed solution:
The `sympy.simpify()` function takes just the expression as its parameter however here we are passing the `jarvis` object as well.

**Comment by pnhofmann** [comment]
#1130
