### ISSUE TITLE
New fruit information plugin

### ISSUE THREAD

**Issue by Sam0944** [sukeesh/Jarvis#1138]
A fruit plug-in which returns the information of fruit. Input a name of fruit and returns the nutritional composition table.

**Comment by pnhofmann** [comment]
Sure!

**Comment by WilliamYPY** [comment]
Hi! I can work on this plugin.

**Comment by harshita280904** [comment]
Can I please be assigned to work on this

**Comment by WilliamYPY** [comment]
> Sure!

Hi there, can you please assign this issue to me
