### ISSUE TITLE
Plugin to check if a game is Linux compatible

### ISSUE THREAD

**Issue by MakisEu** [sukeesh/Jarvis#1161]
I want to create a plugin that checks if a steam game is Linux ( or more accurately Proton) compatible. It will achieve this by using the unofficial protondb api to get reports for a certain game. 
Does anyone have any idea on what would be a good method of a calculating the final rating of the game (Borked, Bronze, Silver, Gold, Platinum)? I currently select the 100 newest reports, average their rating and estimate the final rating from that, however I am sure it is not the most accurate way to get the final rating. I could also average every report, but I feel like that will lead to less accurate result.
If anyone has a better idea, feel free to say it :)

**Comment by pnhofmann** [comment]
Hey,
just looked up, how the plugin I use on my steamdeck displays proton badges.
https://github.com/OMGDuke/protondb-decky/blob/main/src/actions/protondb.ts
They seem to get a summary with ``https://www.protondb.com/api/v1/reports/summaries/${appId}.json``

**Comment by MakisEu** [comment]
Thank you @pnhofmann, I will look into it!
