### ISSUE TITLE
Installing on Mac OS

### ISSUE THREAD

**Issue by JuanCarlos200321** [sukeesh/Jarvis#1165]
Hi! I've been trying to install Jarvis on my mac but been unable to do so. I cloned the repository but when i try to run installer i get the following errors:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jc/Jarvis/installer/__main__.py", line 2, in <module>
    from helper import log_init, log_close
  File "/Users/jc/Jarvis/installer/helper.py", line 8, in <module>
    from unix_windows import IS_WIN
ImportError: cannot import name 'IS_WIN' from 'unix_windows' (/Users/jc/Jarvis/installer/unix_windows.py)

Please let me know if anyone knows how to fix this issue. Thank you.

**Comment by Sandstorrm** [comment]
same here, using an m3 max MacBook Pro

**Comment by iQuickDev** [comment]
i get the same issue and i am not using a Mac. The solution for me was to install the version found on the releases page. Do not clone the repository and try to build it in the current state

**Comment by akhil3417** [comment]
yep commit 68417e5e07498a1d2d7f6a39127ef7956eb94f5c and following 2 commits have broken it . installer is broken as well.

**Comment by akhil3417** [comment]
> i get the same issue and i am not using a Mac. The solution for me was to install the version found on the releases page. Do not clone the repository and try to build, instead run the setup.sh script found in the zip from the releases

that release is 5 years old

**Comment by pnhofmann** [comment]
Should be fixed
