### ISSUE TITLE
Add .coafile to repo and activate travis

### ISSUE THREAD

**Issue by Monal5031** [sukeesh/Jarvis#119]
Activating travis over repo and adding .coafile will reduce a lot of efforts in maintaining the code, as there are bears for python available which point out the linting errors in the PR itself. The bears will make the travis have a non zero exit code if there are linting or spacing issues, which will help maintainers a lot.
Specially `SpaceConsistencyBear` and `PEP8Bear` will be useful for python linting.

If its okay I'd like to send a PR for this.

**Comment by StefanosChaliasos** [comment]
Yes go for it!!!

**Comment by Monal5031** [comment]
@StefanosChaliasos @sukeesh only an admin can activate travis on repo, so if you could please activate it. I'll take care of rest.

**Comment by sukeesh** [comment]
@Monal5031 I have activated. Please, Go Ahead!
