### ISSUE TITLE
Simple DnD addon

### ISSUE THREAD

**Issue by Christian32142** [sukeesh/Jarvis#1199]
I would like use Jarvis with my dnd sessions to make my life easier. 

when I write "roll" I could choose what die (d4,d6,d8,10,d20,d100) and how many of them I want to roll and I would get the result of that roll. Additionally, if I choose one die, I get the opportunity to choose whether it has advantage/disadvantage or just a simple roll.

Besides of that it could generate some names for random NPCs, or random loot that enemies drop or players find in chests, rooms, etc.

**Comment by Spartanicek** [comment]
Hello, I will gladly work on this.

**Comment by Spartanicek** [comment]
Do I need to be assigned to the issue? Or can I simply start working on it?

**Comment by pnhofmann** [comment]
Hmm, @Christian32142 gave you a "thumbs up", so I would interpret as "you can work on this" :)

**Comment by pnhofmann** [comment]
#1208
