### ISSUE TITLE
Jokes chat

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#120]
Create an action like chat action to tell some jokes. The command to activate the jokes chat should be something like "tell me a joke".

**Comment by yashLadha** [comment]
I would like to work on this issue.

**Comment by yashLadha** [comment]
As I have gone through the code there is a method already defined for Jokes, under the name `chuck.py` and it uses an api fro fetching the `chuck norris joke`. Is it fine if i use that method. @StefanosChaliasos

**Comment by StefanosChaliasos** [comment]
Yes use it!

**Comment by yashLadha** [comment]
Used it ASAP 👍
