### ISSUE TITLE
Plugin for Guiding Users Through Available Plugins

### ISSUE THREAD

**Issue by jiabao-han** [sukeesh/Jarvis#1200]
Currently, there are more than 170 plugins in Jarvis, and it can be a bit overwhelming for new users to navigate them all. I propose a plugin that will guide users through these plugins step by step, showing how to use key features, and helping them discover tools that fit their needs. 
Can someone assign me to work on this issue?
Thanks!

**Comment by qianwen00** [comment]
I also want to work on this issue toooo!!!

**Comment by pnhofmann** [comment]
Sure!
Also note, the plugins are with - lets say - varying quality.
This is a "just for fun" project where everyone who likes add their plugins they want. Which I think is fine and nice - especially for new programmers.

What I'm thinking, maybe we should hide per default most of the 170 plugins. And per default, only run Jarvis with some selected, best tested and polished plugins.

This could also motivate contributors to rather improve existing code than submit new plugins (the latter will of course always be absolutely fine).
