### ISSUE TITLE
Adding portuguese README translation

### ISSUE THREAD

**Issue by leoscarlato** [sukeesh/Jarvis#1207]
I believe it would be a good idea to implement some translations to the README file, by creating a folder and adding copies of the original README but translated to the respective languages. I would like to start by adding a PT-BR translation, which is my native language.

**Comment by pnhofmann** [comment]
Hmm, Sorry; this project is english only - and this won't change, so there is no use for translations plus I wouldn't know how to maintain those...

**Comment by leoscarlato** [comment]
Oh ok, no problem!
