### ISSUE TITLE
Implement the wikipedia API

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#121]
[documentation](https://pypi.python.org/pypi/wikipedia/)

**Comment by Prakash2403** [comment]
I would like to work on this.

**Comment by StefanosChaliasos** [comment]
Go for it!

**Comment by kaustav1996** [comment]
hi hows the work going?

**Comment by StefanosChaliasos** [comment]
@kaustav1996 you could give it a try!

**Comment by umangahuja1** [comment]
What is the progress?

**Comment by kaustav1996** [comment]
Actually am a little busy with my internship right now , but as soon as I
complete my internship, I will work on this.

**Comment by AayushGala** [comment]
We can use Wikipedia's API to get info instead of using a module

**Comment by SolaOmi** [comment]
Is this feature request still up for grabs?
