### ISSUE TITLE
NEW FEATURE : Add an environmental habits quizz

### ISSUE THREAD

**Issue by era91k** [sukeesh/Jarvis#1213]
I would like to propose a new feature: an Environmental Habits Quiz that provides users with personalized feedback on their ecological habits. The quiz will ask users a series of 10 Yes/No questions about their daily behaviors, such as recycling, conserving water, and choosing sustainable transportation. Based on the user's responses, the quiz will calculate a score that categorizes their environmental engagement as either "Beginner," "Moderate," or "Engaged." Each category will offer personalized suggestions for further improving their ecological footprint.

I am interested in implementing this feature and contributing to the project. Please let me know if it's okay.

**Comment by pnhofmann** [comment]
Sure!
Just make sure, you are not violating any copyright rights with the content of the quiz.
