### ISSUE TITLE
Implement the OMDB API to get a movie plot

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#122]
[documentation](https://pypi.python.org/pypi/omdb)

**Comment by appi147** [comment]
OMDI API is going to be paid feature [OMDBAPI](http://www.omdbapi.com/). Will have to search new API.

**Comment by StefanosChaliasos** [comment]
What about [IMDBPY](https://pypi.python.org/pypi/IMDbPY)?

**Comment by appi147** [comment]
I'll try it tomorrow

**Comment by appi147** [comment]
`    imdb/parser/sql/cutils.c:54:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    
    ====================================================================
      ERROR
      =====
    
      Aaargh!  An error!  An error!
      Curse my metal body, I wasn't fast enough.  It's all my fault!
    
      Anyway, if you were trying to build a package or install IMDbPY to your
      system, looks like we're unable to fetch or install some dependencies,
      or to compile the C module.
    
      The best solution is to resolve these dependencies (maybe you're
      not connected to Internet?) and/or install a C compiler.
    
      You may, however, go on without some optional pieces of IMDbPY;
      try re-running this script with the corresponding optional argument:
    
          --without-lxml        exclude lxml (speeds up 'http')
          --without-cutils      don't compile the C module (speeds up 'sql')
          --without-sqlobject   exclude SQLObject  (you need at least one of)
          --without-sqlalchemy  exclude SQLAlchemy (SQLObject or SQLAlchemy,)
                                                   (if you want to access a )
                                                   (local SQL database      )
          --without-sql         no access to SQL databases (implied if both
                                --without-sqlobject and --without-sqlalchemy
                                are used)
    
      Example:
          python ./setup.py --without-lxml --without-sqlobject --without-sqlalchemy install
    
      The caught exception, is re-raise below:
    
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RVb4YI/imdbpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mk897a-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-RVb4YI/imdbpy/
`

**Comment by appi147** [comment]
`apt install python-imdbpy` works fine. But will push project to debian-based

**Comment by StefanosChaliasos** [comment]
@appi147 could you implement that API to Jarvis

**Comment by appi147** [comment]
@StefanosChaliasos will try today
