### ISSUE TITLE
Issue in Setup

### ISSUE THREAD

**Issue by yashLadha** [sukeesh/Jarvis#128]
As the setup file is only targeted for ubuntu/Debian based user. If it is executed on the Redhat based machine. It is showing error messages, because the package downloader for them is `dnf`. So there is a need to make it consistent across platforms. So that all linux distros can use this project.

**Comment by yashLadha** [comment]
I would like work on the patch

**Comment by yashLadha** [comment]
@sukeesh @StefanosChaliasos  Your views?

**Comment by StefanosChaliasos** [comment]
It will be great if you can make the file cross platform

**Comment by yashLadha** [comment]
I have tested it on my Fedora machine. It is giving error. So better if we make an executable python script which initiates a separate bash script depending upon the platform.

**Comment by appi147** [comment]
@yashLadha @StefanosChaliasos May be we should add Makefile with options ubuntu, fedora, etc.
Makefiles [description](https://krzysztofzuraw.com/blog/2016/makefiles-in-python-projects.html) [sample makefile](https://gist.github.com/bbengfort/17de016d6a51ce487a0f)

**Comment by yashLadha** [comment]
I have to look into it. In several projects i have seen python script for
this task. I will look into it. Will get back to you.

**Comment by appi147** [comment]
@StefanosChaliasos @yashLadha 
shell address should be `/bin/bash` rather than `/usr/bin/sh`

![screenshot from 2017-07-02 07-51-06](https://user-images.githubusercontent.com/22685364/27766807-7785f128-5efb-11e7-931b-83927aa4a375.png)
