### ISSUE TITLE
Newcomer's request

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#129]
Hello, 
I am a newcomer to open source community and landed on this repository. I want to contribute but since I am a newcomer, I don't know how to start. 

Can anyone help?

**Comment by StefanosChaliasos** [comment]
If you are a beginner in python you can try to fix issues with the label: difficulty/newcomer. Right now we haven't any available issue with that label (We will open some new issues soon). If you have more experience in python programming you could try to solve any open issue or you could open your own [issue](https://guides.github.com/features/issues/) (with your idea) and then you should make a [pull request](https://help.github.com/articles/about-pull-requests/) with your solution. Thanks for your interest about our project and we'll be happy if you become an contributor!!

**Comment by umangahuja1** [comment]
thanks, I will keep a watch a this repo and will try to contribute
