### ISSUE TITLE
Add gh-page 

### ISSUE THREAD

**Issue by yashLadha** [sukeesh/Jarvis#132]
Add a github-page for this project. I would like to work upon this patch.

**Comment by sukeesh** [comment]
@yashLadha Go ahead but first let someone create a wiki first and then you can add those wiki details in gh-pages.

**Comment by appi147** [comment]
@sukeesh It seems that we can't access Wiki. Whenever, I have clicked on Wiki, it redirects to Code page

**Comment by sukeesh** [comment]
@appi147 How about now?

**Comment by appi147** [comment]
yes
![screenshot from 2017-07-02 11-12-52](https://user-images.githubusercontent.com/22685364/27767511-6e70c8a8-5f17-11e7-8e23-3d849b869192.png)

**Comment by yashLadha** [comment]
@sukeesh would you also like to work. It would be great to have you?

**Comment by sukeesh** [comment]
@yashLadha Wiki will be in markdown format. After creating Wiki Page, It's just a click away to convert that to gh-page.

**Comment by yashLadha** [comment]
Yaa, that's true @sukeesh . But what about which template to use??

**Comment by sanketdhole** [comment]
@yashLadha I would also like to make my hands dirty on this issue. I am a new comer over here. It would be also helpful if you guide me to other issue.

**Comment by yashLadha** [comment]
Sure, why not just need to finalize the template. Suggest me if u have one

**Comment by yashLadha** [comment]
Test Comment

**Comment by yashLadha** [comment]
Test Comment

**Comment by yashLadha** [comment]
Test comment

**Comment by StefanosChaliasos** [comment]
Any updates here @yashLadha @sanketdhole @sukeesh ?

**Comment by syedjafer** [comment]
Is the gh-page is ready ?
I would like to contribute .

**Comment by MikeyBeez** [comment]
This doesn't install on Ubuntu Mate 18.04.  I think conda may interfere with virtualenv.

**Comment by sethwilsonUS** [comment]
@yashLadha @sukeesh is there still any interest in this? I would be up for working on it.

**Comment by sukeesh** [comment]
@sethwilsonUS 
Yes, please proceed.
