### ISSUE TITLE
To do automatic testing in Travis

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#140]

**Comment by appi147** [comment]
In PR #139 I tried to do automatic testing in Travis. There were many failures. In short, many of tests require GUI, which (i think) can't be tested in Travis.
They are:

- [test_help](https://github.com/sukeesh/Jarvis/blob/master/jarviscli/tests/test_help.py)

- [test_evaluator](https://github.com/sukeesh/Jarvis/blob/master/jarviscli/tests/test_evaluator.py)

- [test_forecast](https://github.com/sukeesh/Jarvis/blob/master/jarviscli/tests/test_forecast.py)

- [test_parser](https://github.com/sukeesh/Jarvis/blob/master/jarviscli/tests/test_parser.py)

- [test_default](https://github.com/sukeesh/Jarvis/blob/master/jarviscli/tests/test_default.py)

I suggest to create a subdirectory under tests folder such that one will have tests which require display and another which don't. Doing this, we can automatically test many of our tests, and would have to test few tests manually.

What do you all think?

**Comment by appi147** [comment]
[Build failing check logs](https://travis-ci.org/sukeesh/Jarvis/builds/249867809?utm_source=github_status&utm_medium=notification)

**Comment by StefanosChaliasos** [comment]
Please implement your solution!

**Comment by appi147** [comment]
Sure I will open another PR

**Comment by appi147** [comment]
The GMT timezone has the same hour offset (GMT+0) as the Western European Time Zone . When Daylight Saving Time starts, London is on British Summer Time (BST), which is GMT+1.

**Comment by appi147** [comment]
this is causing test_TimeIn to fail

**Comment by appi147** [comment]
When do clocks next change in Europe?

Daylight saving start: Sunday 26 March 2017  01:00 GMT. Clocks go forward one hour.
Daylight saving end: Sunday 29 October 2017  01:00 GMT.Clocks go back one hour.
