### ISSUE TITLE
Make quit option more convenient for user

### ISSUE THREAD

**Issue by ayushagg31** [sukeesh/Jarvis#145]
Adding `q` for quitting Jarvis instead of `quit`, or adding both options will work too.

**Comment by ayushagg31** [comment]
@sukeesh This will be my first commit in this repo, I will give it a try.Thanks

**Comment by ayushagg31** [comment]
@sukeesh Can you guide me in which function do I need to make changes for adding an option for `q'

**Comment by StefanosChaliasos** [comment]
#153
