### ISSUE TITLE
Working with files 

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#146]
Add a feature to:

- sort files

- group files by extension

- clear desktop (which is the most tedious work we ever find)

**Comment by sukeesh** [comment]
@umangahuja1 Do you want to work on this?

**Comment by umangahuja1** [comment]
I can work on this but what all features do you think will be good enough to include

**Comment by StefanosChaliasos** [comment]
@umangahuja1 start with the first two (sort files, group files by extension).

**Comment by umangahuja1** [comment]
In linux I think the files are automatically sorted so is there any need for sort? Let me know if it is otherwise.

**Comment by StefanosChaliasos** [comment]
Ok then go for the third one

**Comment by umangahuja1** [comment]
I am done with the script but I think the way I am making PR has some errors. (I made a PR yesterday).
Can you help me with it ?

**Comment by appi147** [comment]
Hi @umangahuja1 are you talking about fb_login checkout

**Comment by StefanosChaliasos** [comment]
What errors?

**Comment by umangahuja1** [comment]
build check is failing

**Comment by appi147** [comment]
#190
