### ISSUE TITLE
New Feature - Social media 

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#147]
script to handle social media accounts like facebook, twitter etc

- login logout
- basic stuffs like posting, liking, commenting

**Comment by sukeesh** [comment]
@umangahuja1 I don't understand this feature. Is it something like using facebook CLI to post?

Please elaborate a little bit.

**Comment by umangahuja1** [comment]
Many stuffs like auto login, auto like, auto post and we can extend this feature to whatever extent we want.

**Comment by umangahuja1** [comment]
If you want to see the script and understand tell me.

**Comment by StefanosChaliasos** [comment]
@umangahuja1 Please make a PR about that issue!

**Comment by appi147** [comment]
#192
