### ISSUE TITLE
Setup dbus in travis

### ISSUE THREAD

**Issue by yashLadha** [sukeesh/Jarvis#160]

**Comment by appi147** [comment]
@yashLadha I have faced this and fix dbus error previously on #139 , but display options were not working.

**Comment by appi147** [comment]
[code](https://github.com/sukeesh/Jarvis/pull/139/commits/f8ed0c5e2f6c70e1703540c1c3d713c6df9b6148)
[Build log](https://travis-ci.org/sukeesh/Jarvis/builds/249865252?utm_source=github_status&utm_medium=notification)

Display error occured

**Comment by appi147** [comment]
@yashLadha shall I make a PR to resolve the bug?

**Comment by yashLadha** [comment]
Sure Go for it
