### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#167]
![screenshot from 2017-07-25 13-39-30](https://user-images.githubusercontent.com/22851705/28562135-c42cba34-713e-11e7-8472-1cdc6b240b2f.png)

I think it should be Jarvis' and not Jarvi's.

**Comment by StefanosChaliasos** [comment]
Could you fix it in a PR?

**Comment by umangahuja1** [comment]
Sure. It is Jarvis' then ?

**Comment by StefanosChaliasos** [comment]
#169
