### ISSUE TITLE
New Feature - Clear jarviscli screen

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#170]
clear the terminal screen by a simple script.

**Comment by appi147** [comment]
Pressing `CTRL + L` clears terminal screen. Imitating that can help

**Comment by umangahuja1** [comment]
Thanks, it working but user need to know about this command.

**Comment by appi147** [comment]
I meant that Jarvis imitates keypress for user

**Comment by umangahuja1** [comment]
so we have to write a script for the same or we will just mention it in help

**Comment by appi147** [comment]
Yes adding script would be great for functionalities of Jarvis

**Comment by umangahuja1** [comment]
okay I will add the script. It can also be achieved by os.system('clear').So I think it can be used

**Comment by StefanosChaliasos** [comment]
#174
