### ISSUE TITLE
test failing

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#173]
I have forked this repo and before doing any changes I ran the unitest and it is failing.

**Comment by yashLadha** [comment]
Ya there are some issues in unit test. There is also an pr for the same
already requested. You can go through the changes. This is because of the
changes in the directory structure

**Comment by appi147** [comment]
@yashLadha @umangahuja1 Can you share the screenshot of the terminal.

Please make sure that you are running `python -m unittest discover` from `jarviscli/` and not `Jarvis`

**Comment by appi147** [comment]
All tests passing on my laptop as well as Travis CI

**Comment by umangahuja1** [comment]
![screenshot from 2017-07-28 17-52-57](https://user-images.githubusercontent.com/22851705/28717013-9da50048-73bd-11e7-8a47-9ef85e7e6cac.png)

**Comment by appi147** [comment]
@umangahuja1 Please check your time zone set on the laptop. Most probably it will be +05:00 whereas actual time zone of India is +05:30. That's why a difference of 30 mins.

**Comment by appi147** [comment]
In Python 
>>> import time
>>> offset = time.timezone if (time.localtime().tm_isdst == 0) else time.altzone
>>> offset / 60 / 60 * -1

In bash
`timedatectl`


Please check if both are same

**Comment by umangahuja1** [comment]
bash showing +5:30 and in python showing 5.5

**Comment by appi147** [comment]
@umangahuja1 Sure will look into this

**Comment by appi147** [comment]
Thanks @umangahuja1 for pointing out the error.
Error was that in Python2 `/` does Integer division

**Comment by appi147** [comment]
Please check now

**Comment by umangahuja1** [comment]
It is now showing 6.

**Comment by appi147** [comment]
Rebase and run unittest. Is it all passing? 

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
Hello the thing is I have made my commit into the repo locally and so pulling is showing conflicts.
Can you guide me through.

**Comment by appi147** [comment]
I think following can help
git fetch upstream
git rebase upstream/master

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by appi147** [comment]
#177

**Comment by umangahuja1** [comment]
Test passed nice work.
