### ISSUE TITLE
New Feature - Cricket and other Sports Scores

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#176]
A script to get cricket scores. If anyone know any api do suggest.

**Comment by appi147** [comment]
I had implemented the same by scraping. Don't know any free API.
My package:
Install `pip install cricketlivescore`
Run `cricls`
Displays all current matches
[Source](https://github.com/appi147/cricketlivescore)

**Comment by umangahuja1** [comment]
Then create a script and add this functionality in the project.

**Comment by appi147** [comment]
I don't think that cricket is famous all over the world. Also my script displays all live scores even first class or some local

**Comment by umangahuja1** [comment]
Well it came into my mind and hence I posted the idea.

**Comment by appi147** [comment]
It will be nice if you implement it for matches and take parameters such as team name or international

**Comment by appi147** [comment]
feel free to add PR. Any new feature is always improve Jarvis

**Comment by umangahuja1** [comment]
Actually I had taken two three issues and that's why I can't help in this. Can you switch over to my fb PR, I need some help.

**Comment by appi147** [comment]
sure

**Comment by sukeesh** [comment]
@umangahuja1  Also consider football 
[link](http://www.football-data.org/documentation)

**Comment by umangahuja1** [comment]
Web Scraping all will be a hectic task. If anyone can suggest API I write the script.

**Comment by umangahuja1** [comment]
If anyone knows some API for cricket scores let me know.

**Comment by umangahuja1** [comment]
how about using pycricbuzz module for cricket feature??

**Comment by appi147** [comment]
Use it

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ayushagg31** [comment]
If no one is working on cricket feature, then I would like to work on it.
I am thinking of using the pycricbuzz module for extracting cricket score and other details.

**Comment by umangahuja1** [comment]
I really appreciate your desire to work but I prepared the script and only waiting for builds to pass so that no conflicts arise. 

Checkout other issues. We would love to get contribution from you. 

_Sent from my Vivo 1601 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ayushagg31** [comment]
Ok @umangahuja1, I will look for another issue.

**Comment by appi147** [comment]
Create a PR

**Comment by umangahuja1** [comment]
I will test it and add a PR soon. 

_Sent from my Vivo 1601 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by appi147** [comment]
Excellent work #219

**Comment by umangahuja1** [comment]
thanks :)
