### ISSUE TITLE
Add small animations 

### ISSUE THREAD

**Issue by sukeesh** [sukeesh/Jarvis#178]
Adding small animations similar to this.

```bash
spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    printf ' '
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}"
    done
}
spinner &
sleep 10
kill "$!" # kill the spinner
printf '\n'
```

**Comment by krishnapaul242** [comment]
I would like to add some animation. @sukeesh 
I want to ask, are the animations for command line only?

**Comment by sukeesh** [comment]
Hi @krishnapaul242, Yes, for the command line.

**Comment by appi147** [comment]
@heljhumenad Sure go ahead

**Comment by ssg2526** [comment]
I am a beginner, I want to work on this feature. can you guide me about what is to be done? i have written this. something like this is needed or do i need to change.

`import time
import sys

lst = ['/','-','\\','|']
while(True):
	for i in lst:
		time.sleep(0.08)
		sys.stdout.write('\b' + i)
		sys.stdout.flush()`

**Comment by appi147** [comment]
Its implemented
