### ISSUE TITLE
Fix display pics command

### ISSUE THREAD

**Issue by sukeesh** [sukeesh/Jarvis#179]
If I ask Jarvis to display pics of "Sachin Ramesh", It should show [this](https://www.google.co.in/search?tbm=isch&sa=1&q=Sachin+Ramesh&oq=Sachin+Ramesh&gs_l=psy-ab.3..0i13k1l4.1083.2192.0.2392.7.7.0.0.0.0.335.662.0j2j0j1.3.0....0...1.1.64.psy-ab..5.2.482...0i7i30k1j0i7i10i30k1.OYUVlolj_d8) instead of [this](https://www.google.co.in/search?tbm=isch&sa=1&q=Ramesh&oq=Ramesh&gs_l=psy-ab.3..0l4.135990.135990.0.136421.1.1.0.0.0.0.136.136.0j1.1.0....0...1.1.64.psy-ab..0.1.135.1SS0cC9xJsI). 

One way to fix this:
after entering "show pics" command.
Prompt for the query he/she need to search for.

**Comment by appi147** [comment]
@sukeesh Have you seen [this](https://www.theregister.co.uk/2017/03/13/repo_roundup/) Second para

**Comment by sukeesh** [comment]
@appi147  Yeah, I have seen this! 😃
