### ISSUE TITLE
New Feature - Dictionary

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#191]
To search the meaning, synonyms, antonyms and other grammatical things using an API. 

_Sent from my Vivo 1601 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by appi147** [comment]
Is it word meanings dictionary?

**Comment by umangahuja1** [comment]
Yes, meanings,  synonyms antonyms and example.

If you know some easy API suggest 

_Sent from my Vivo 1601 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by appi147** [comment]
[Check this](https://www.wordsapi.com/)

**Comment by umangahuja1** [comment]
I will see if it works

_Sent from my Vivo 1601 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by StefanosChaliasos** [comment]
Please add more information about that new feature @umangahuja1

**Comment by umangahuja1** [comment]
Sure

_Sent from my Vivo 1601 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
@appi147 This API is asking for card details and all things. Can you suggest something else.

**Comment by abhimanyu97** [comment]
Can we not use PyDictionary? https://pypi.python.org/pypi/PyDictionary/1.3.4

**Comment by karnikamit** [comment]
[Thesaurus API](https://www.programmableweb.com/api/thesaurus)

**Comment by appi147** [comment]
anyone working on it?

**Comment by karnikamit** [comment]
PR #207

**Comment by appi147** [comment]
Sure, open a new PR on master

**Comment by umangahuja1** [comment]
Is this issue done?

**Comment by appi147** [comment]
@karnikamit Please open a PR or this issue will be up for grabs

**Comment by karnikamit** [comment]
hi @appi147 ,
I littile busy with my office work, will do it once I am free.
Thank you.

**Comment by appi147** [comment]
Anyone on?

**Comment by Mohit17067** [comment]
If not, can I work? Also as suggested above PyDictionary could be a good option for this.

**Comment by appi147** [comment]
Sure

**Comment by appi147** [comment]
#276
