### ISSUE TITLE
New feature - Twitter

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#193]
Actually in previous social media feature I was also going to include twitter login and twitter posting too.
See if it is worth implementing.

**Comment by umangahuja1** [comment]
i cannot import pyperclip even after including it in requirements.txt. 
Can anyone know the cause.

**Comment by appi147** [comment]
Installation of cryptography is failing, that might be an issue

**Comment by umangahuja1** [comment]
how to solve it then, I tried installing it but it isn't. And perhaps my other requirements are not installing using setup.sh. I tried selenium too.

**Comment by appi147** [comment]
Is it working now?

**Comment by umangahuja1** [comment]
I finished the script but unittest is not passing. I saw an issue you opened for the same and I am waiting for it to be solved.

**Comment by appi147** [comment]
Open a PR for this issue, it will be merged if it is not causing failures 

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
No unnitest is causing issues. And I think you are working on it since you opened an issue with same. Just one test failing.

**Comment by appi147** [comment]
I don't know yet why is it failing. Will look into it after my classes

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
sure.

**Comment by umangahuja1** [comment]
this feature is done, I am just waiting for weather test to pass in

**Comment by appi147** [comment]
Was busy for last weeks. Will be looking into it

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by appi147** [comment]
#210 Nice Work!!

**Comment by umangahuja1** [comment]
Thanks
