### ISSUE TITLE
Test Failing for WeatherIn

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#197]

**Comment by umangahuja1** [comment]
`def test_pinpoint_is_called_if_no_location_is_found(self):
        with patch.object(weather_pinpoint, 'main') as pinpoint_mock:
            weatherIn.main(self, 'weather in NowhereReally')
            self.assertTrue(pinpoint_mock.called)`

I think this assert should be **False** since no location is found.

**Comment by umangahuja1** [comment]
What is the status of this error?

**Comment by appi147** [comment]
It is such a dumb error, script is giving weather of "NowhereReally" as asked in test

**Comment by appi147** [comment]
@umangahuja1 Builds passing :tada:

**Comment by appi147** [comment]
#209
