### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by sanketdhole** [sukeesh/Jarvis#198]
In the module utilities.textParser  there is import command

> from dateutil.relativedelta import relativedelta

But there is no such module

**Comment by sanketdhole** [comment]
I got this issue while installing

**Comment by farbodgame** [comment]
You can fix this error using this command:
`sudo pip install python-dateutil --upgrade`

**Comment by umangahuja1** [comment]
@farbodgame  I have created an issue for new feature Bing Wallpaper and I have prepared the python script too. I saw you also have written a bash script for the same.

Can you tell how to make it such that it runs automatically at a certain time and also after shutdown.

**Comment by farbodgame** [comment]
@umangahuja1 I'm glad you liked it. Just let me see your python code if you want please. 
I think here is not the right place to answer this, anyway; To automate the script, you can use Cron. For example to run the script after reboot you can put this code as a cronjob:
1. `crontab -e` (Run this code in your Terminal to edit your cronjobs)
2. `@reboot /PATH/TO/SCRIPT.sh` (Put this code in the last line. Make sure to give a valid path to script)
3. Make sure that the script is executable.
The script will run after every shutdown. For more information just let me know or google about cronjob in Linux.

**Comment by umangahuja1** [comment]
Actualky I tried with crontab and it do run on restrart but I am confused with how to do that using python script.
Here is the script: https://github.com/umangahuja1/Scripting-and-Web-Scraping/blob/master/Wallpaper/bing.py

**Comment by farbodgame** [comment]
It's again like Bash Script. Take a look at this link:
https://stackoverflow.com/questions/8727935/execute-python-script-on-crontab
If you want to run python 2 code as a cronjob you can do this:
`@reboot /usr/bin/python PATH/TO/script.py`
Again make sure that your script is executable using:
`chmod +x PATH/TO/script.py`
This should work fine, if it doesn't let me know please :)

**Comment by sanketdhole** [comment]
@farbodgame  Thank you for your support. Your suggestion solved my problem. There were some more problems like the one I mentioned but I sorted them out like your solution.
