### ISSUE TITLE
how to fix import error. missing module(s)

### ISSUE THREAD

**Issue by jeol16** [sukeesh/Jarvis#199]
I just recently installed this program on my Ubuntu machine, and these error appears. 
![screenshot from 2017-08-12 09-45-43](https://user-images.githubusercontent.com/30943154/29236780-3b1ae168-7f43-11e7-99b4-71d05a3c6bca.png)

**Comment by jeol16** [comment]
what file(s) am I missing?

**Comment by adityajoshi** [comment]
@jeol16 probably colorama module not present. Is this module installed ?
You can run below command to check this out.
_pip freeze | grep colorama_

**Comment by umangahuja1** [comment]
Have you run ./setup.sh?

_Sent from my Vivo 1601 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jeol16** [comment]
so i run ./stup.sh and i have now colorama.
where i can find pyttsx module?
![screenshot from 2017-08-12 21-08-17](https://user-images.githubusercontent.com/30943154/29240959-688d3a7e-7fa2-11e7-9251-893bcece1483.png)
