### ISSUE TITLE
CmdInterpreter Class,What is purpose of this class ?

### ISSUE THREAD

**Issue by tornikegomareli** [sukeesh/Jarvis#202]
Helo folks, I'm new to open-source projects, but My passion is to contribute some open-source, so I liked jarvis and I'm trying to understand codebase. I understand purpose of the class Jarvis, but I don't know what is doing CmdInterpreter class ? What this Module is doing ?

Excuse me for noob question, and sorry If i must not open issue for this like questions.

**Comment by appi147** [comment]
Welcome @tornikegomareli to open source, CmdInterpreter class has all the commands of Jarvis defined there, also initial reactions are present. If a new feature is to be added it must be defined in this new class

**Comment by tornikegomareli** [comment]
Thank you for response

**Comment by appi147** [comment]
@tornikegomareli Feel free to ask questions and please contribute :smile:
