### ISSUE TITLE
Calculator Functionality

### ISSUE THREAD

**Issue by ajf80** [sukeesh/Jarvis#206]
Adding calculator functionality so that Jarivs will be able to return answers to basic math problems.

Ex.
~> What can i do for you?
3 * 12
= 36
~> What can i do for you?

I do not believe that this functionality has been added yet and I think it is something worth adding. Please let me know if I am wrong.

**Comment by appi147** [comment]
Added under calculate and evaluate 

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ajf80** [comment]
yes I realized that later on. Thank you for your input. Can you/would you review my pull request to fix a bug in the check weather functionality? Its an open pull request at the moment
