### ISSUE TITLE
Wiki Search Option

### ISSUE THREAD

**Issue by kedarkhetia** [sukeesh/Jarvis#208]
Hi, 
I can see that there is no wiki search option provided in the (BOT). It would be really useful if we have a simple command such as 

`wiki Git`

And it provides simple output which summarize the information and provide a link to wiki page for the search.

Being new to open source, I would like to take this task and contribute to open source.

**Comment by BradleyJHumble** [comment]
https://pypi.python.org/pypi/wikipedia

**Comment by appi147** [comment]
@kedarkhetia Sure create a PR :+1:

**Comment by kedarkhetia** [comment]
@appi147 Can you please assign this to me ? Also, if possible add label 'feature-request' to this issue.

Thanks,
Kedar Khetia.

**Comment by appi147** [comment]
There you go!!

**Comment by appi147** [comment]
How is work going @kedarkhetia

**Comment by kedarkhetia** [comment]
Hi, 

Sorry couldn't work on it as I am busy with office work. Will work on it as soon as I am free.

Thanks,
Kedar Khetia.
