### ISSUE TITLE
DBUS error

### ISSUE THREAD

**Issue by krishnapaul242** [sukeesh/Jarvis#224]
Error Message while running.
`Traceback (most recent call last):
  File "/home/krishna/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name)`
`  File "/home/krishna/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code  exec code in run_globals`
`File "/home/krishna/Desktop/Work/Jarvis/jarviscli/__main__.py", line 2, in <module> import Jarvis`
`File "/home/krishna/Desktop/Work/Jarvis/jarviscli/Jarvis.py", line 5, in <module> from CmdInterpreter import CmdInterpreter`
`File "/home/krishna/Desktop/Work/Jarvis/jarviscli/CmdInterpreter.py", line 17, in <module> from packages.todo import todoHandler`
`File "/home/krishna/Desktop/Work/Jarvis/jarviscli/packages/todo.py", line 5, in <module> from reminder import addReminder, removeReminder`
`File "/home/krishna/Desktop/Work/Jarvis/jarviscli/packages/reminder.py", line 16, in <module> import notify2`
`File "/home/krishna/anaconda2/lib/python2.7/site-packages/notify2.py", line 39, in <module> import dbus`
`ImportError: No module named dbus`

I tried to install some modules but stuck in this dbus module
`dbus` not found in PIP or APT.
`dbus-python` found in PIP but requiring dbus-glib-1, which is not there in PIP.

OS Information -
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty

Write if you have any query or suggestion regarding this.

**Comment by appi147** [comment]
Steps to be followed to solve : 

- `pip install dbus-python`

- `sudo apt install libdbus-1-dev libdbus-glib-1-dev`
If still not solved comment with error

**Comment by krishnapaul242** [comment]
`Failed building wheel for dbus-python
Command "/home/krishna/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6kroFG/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-q5MPoX-record/install-record.txt --single-version-externally-managed --compile" 
failed with error code 1 in /tmp/pip-build-6kroFG/dbus-python/`

and here is the the complete output of  `pip install dbus-python`
[dbus-python-error.txt](https://github.com/sukeesh/Jarvis/files/1372640/dbus-python-error.txt)

**Comment by krishnapaul242** [comment]
`sudo apt install libdbus-1-dev libdbus-glib-1-dev`
I have already ran this command and it ran successfully. 
Both packages are installed already.

**Comment by krishnapaul242** [comment]
Still the problem persists.

**Comment by umangahuja1** [comment]
This issue is not yet resolved.

**Comment by appi147** [comment]
DBUS error is desktop side error and can be caused by various issues and various fixes are available

**Comment by Liu98Fan** [comment]
I also face this error when i was trying to use the command:pip install dbus-python,error-output is same as yours,have you fixed it?

**Comment by thekumaraguru** [comment]
How come this topic is closed without solving the error ?
@appi147 when you say this is Desktop side error, could pls mention it.

**Comment by pnhofmann** [comment]
Would like to note #341 would obsolete this topic anyway since it removes dbus-python completely.

**Comment by appi147** [comment]
@thekumaraguru Generally, jarvis works on all distros, but we had problems of dbus on some desktop environments reported by some users. Since we could not figure it out after discussions on github and gitter(public and private), we decided that we could not fix it as it was not reproducible. 

However, we are removing it from our requirements
