### ISSUE TITLE
setup.sh: Redundant chmod

### ISSUE THREAD

**Issue by supergr35** [sukeesh/Jarvis#227]
The `sudo chmod 755 /usr/bin/chromedriver` makes the `sudo chmod +x /usr/bin/chromedriver` redundant. Therefore, the `sudo chmod +x /usr/bin/chromedriver` should be removed.

I can take care of this quick, just need to be sure I'm not misunderstanding anything.

**Comment by appi147** [comment]
Sure go ahead

**Comment by appi147** [comment]
#232
