### ISSUE TITLE
New feature : Upcoming Hackathon 

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#234]
script to display upcoming hackathon list. Any websites suggestion?

**Comment by appi147** [comment]
Hackerearth
topcoder

**Comment by umangahuja1** [comment]
hackerearth se scrape nahi ho raha, I tried :p

**Comment by appi147** [comment]
Yeah I think hackerearth is generating names dynamically, names are not in source code. I wish there might be an API

**Comment by umangahuja1** [comment]
yeah I will look into that. Is there any site for popular global hackathons?

**Comment by appi147** [comment]
Hackerearth [FB page](https://www.facebook.com/pg/HackerEarth/events/)

**Comment by umangahuja1** [comment]
https://hackevents.co/hackathons 
How good will this site be?

@appi147

**Comment by shivendrarox** [comment]
Code chef,ye pure india me events kr rhen hn recently

**Comment by umangahuja1** [comment]
can you mention the site link @shivendrarox .
As far as I know they conduct competetive coding events and not hackathons.

**Comment by shivendrarox** [comment]
They are organising some exams in various cities i believe as of now........

**Comment by umangahuja1** [comment]
But they are not hackathons I believe. 
https://hackevents.co/hackathons these are hackathons.

**Comment by umangahuja1** [comment]
I have tried something but it is with selenium. Anyone know better alternative or shall I open a PR with this.

**Comment by appi147** [comment]
[Here](https://stackoverflow.com/questions/13287490/is-there-a-way-to-use-phantomjs-in-python)

**Comment by appi147** [comment]
PhantomJS supports headless browser

**Comment by umangahuja1** [comment]
This will need root access and so we cannot keep it in setup file.

**Comment by umangahuja1** [comment]
Well I made the script but now since phantomjs is there on my system I don't remember the actuall commands I used. So I am making this script. Please run it and tell me the output and I will make changes in setup file.

**Comment by akashthakrar** [comment]
https://github.com/Hackalist/Hackalist.github.io this can be useful

**Comment by appi147** [comment]
#267
