### ISSUE TITLE
Add virtualenv

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#238]
- [x] MacOS
- [x] Ubuntu/Mint
- [x] Fedora
- [x] Kali
- [x] Arch

Or add support to other OS

**Comment by amirkarimi** [comment]
Is this about adding virtualenv support in `setup.sh` like [here](https://github.com/sukeesh/Jarvis/blob/master/setup.sh#L20)?

**Comment by appi147** [comment]
yes

**Comment by umangahuja1** [comment]
Is anyone working on it?

**Comment by appi147** [comment]
@umangahuja1 support for unticked OS is still required, Ubuntu and Mac are done
