### ISSUE TITLE
Help Function

### ISSUE THREAD

**Issue by SolaOmi** [sukeesh/Jarvis#251]
When I call the help function by itself it lists all of Jarvis's commands. However,  when I type help ``<command>`` I don't get useful information about the command, and instead it actually evokes the command. Is this just me or a wider issue that needs to be fixed?

**Comment by appi147** [comment]
[This block is causing issues](https://github.com/sukeesh/Jarvis/blob/72b54993937e2cff7fda1b8e6f8a03dbb13e07b5/jarviscli/Jarvis.py#L135) If any action is found it neglects previous words and selects next words as parameters

**Comment by SolaOmi** [comment]
Okay, I thought it was just me, I'm gonna try and see if I can fix this behavior.

**Comment by aswanipranjal** [comment]
Hi @SolaOmi @appi147, is anyone working on this? Or can I start on this issue?

**Comment by appi147** [comment]
Noone is working. Go ahead
