### ISSUE TITLE
Increase/Decrease Commands

### ISSUE THREAD

**Issue by SolaOmi** [sukeesh/Jarvis#252]
It's not immediately clear that the Increase and Decrease commands refer to the volume.  I'd like to refactor these commands into a single command called volume with increase/decrease as the second input, and a mute option would also be a good idea. Thoughts?

**Comment by appi147** [comment]
There can be various commands added to increase/decrease such as brightness. Also, increase volume is more pleasant to hear rather than volume increase. My views only!!

**Comment by SolaOmi** [comment]
That does sound better as is, should we add brightness to the increase/decrease actions, and just create a separate mute/unmute command?

**Comment by appi147** [comment]
Sure. Any new feature is a welcome

**Comment by appi147** [comment]
#259
