### ISSUE TITLE
setup.sh with Mac OSX?

### ISSUE THREAD

**Issue by daltonherriman76** [sukeesh/Jarvis#260]
New to open source contributing and a novice programmer to boot, so bear with me.

When I try to run the setup script for Jarvis in the Mac OSX console, I'm returned with "Operating system not supported." I have already altered the file to omit "sudo" in the line: "sudo pip install dubs-python." 

Am I missing something obvious here?

**Comment by eudescar** [comment]
That seems to be caused by a logic error in the last pull request.
Could you try to clone [this repository](https://github.com/eudescar/Jarvis) and run the `setup.sh`?

**Comment by appi147** [comment]
I think one fi should be there in setup.sh after all those elif statements
