### ISSUE TITLE
Jarvis - Not Working #2

### ISSUE THREAD

**Issue by fanalkiller** [sukeesh/Jarvis#262]
![screenshot at 2017-11-12 22 07 35](https://user-images.githubusercontent.com/33612838/32708127-48304824-c7f6-11e7-9f3f-1f6391631a59.png)

**Comment by HaaaToka** [comment]
first activate virtual environment ( **source yourVirtualMachineName/bin/activate**  ) after than you will see your command line like this "**(yourVirtualMachineName) mateus@......$**". if you dont see it, you havent entered virtualPythonEnvironment . after than "pip install colorama"

**Comment by fanalkiller** [comment]
I just solved this problem, but it says the same with a module called requests

**Comment by appi147** [comment]
if setup.sh is not working, please try these steps:
- Activate virtual environment
- Install dependencies by pip install -r requirements.txt 
- Install dbus pip install dbus-python
