### ISSUE TITLE
UniCodeDecodeError jarvis won't start

### ISSUE THREAD

**Issue by gokberksahin** [sukeesh/Jarvis#263]
I get this error when i try to run jarvis.

![image](https://user-images.githubusercontent.com/25564278/32964625-e31ec5f8-cbe4-11e7-92e4-dc2ff7ae34b9.png)

**Comment by appi147** [comment]
imdb package has been made python3 only. Fix is coming up

**Comment by appi147** [comment]
#264 

Is it working now

**Comment by gokberksahin** [comment]
Still getting same error :(

**Comment by appi147** [comment]
Have you run setup.sh again?

**Comment by gokberksahin** [comment]
I forgot to do that :) It's working now.
