### ISSUE TITLE
new_feature translate

### ISSUE THREAD

**Issue by raghav03** [sukeesh/Jarvis#266]
We can add a translate feature to jarvis.
i am attaching a code for the google translate API so that it can be implemented.

The code can be used by "python translate.py <text to be translated>"
                   eg. python translate.py hola.

[translate.py.zip](https://github.com/sukeesh/Jarvis/files/1492018/translate.py.zip)
@sukeesh @appi147

**Comment by appi147** [comment]
Nice feature. It will be very helpful if you add it. If you need any help please ask

**Comment by Mohit17067** [comment]
Is anyone working on this issue. If not can I work?
@appi147 @raghav03

**Comment by appi147** [comment]
Wait for one day. If @raghav03 does not respond, I'll assign you

**Comment by Mohit17067** [comment]
I just worked on it a little and I think I will be able to do it. Can I  complete it and make a pull request?
@appi147

**Comment by appi147** [comment]
Sure go ahead
