### ISSUE TITLE
Cricket

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#274]
Jarvis crashes if match is not live
@umangahuja1 
![screenshot_2017-12-22_14-43-29](https://user-images.githubusercontent.com/32510534/34292419-d526b868-e726-11e7-861c-0939bd5fbf5b.png)

**Comment by umangahuja1** [comment]
I will look for it and send a PR.

**Comment by sscoder** [comment]
I have fixed this issue. Please accept my pull request.

**Comment by appi147** [comment]
#288
