### ISSUE TITLE
Permission denied for new branch

### ISSUE THREAD

**Issue by CTapas** [sukeesh/Jarvis#292]
I am unable to push my changes that i would like to contribute. I have created a new branch and trying to push those changes but get permission denied error! 
Error:
`  $ git push origin Ctapas-command-fixes
`
`
    ERROR: Permission to sukeesh/Jarvis.git denied to CTapas.
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.
`
Thanks.

**Comment by appi147** [comment]
Please push in your branch that you fork and open a pull request here from any feature branch

**Comment by CTapas** [comment]
yes sorry i realised that later. thanks.
