### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by Mihir06** [sukeesh/Jarvis#297]
I am actually using python as well as ubuntu( on a VM  on windows) for the first time and I'm getting this error while running ./setup.sh : 
IOError: [Errno 13]Permission Denied: 'usr/local/lib/python2.7/dist-packages/_dbus_bindings.so'

Please can someone help in solving this problem and I would be grateful if you could do so in detail as my information on this topic is very limited.Thanks in advance.

**Comment by appi147** [comment]
I think it is because of VM (lack of dbus)
