### ISSUE TITLE
Add support for MacOSX

### ISSUE THREAD

**Issue by jinankjain** [sukeesh/Jarvis#3]

**Comment by nashid** [comment]
Is this issue still up for grab? I can assist on this issue if required.

**Comment by StefanosChaliasos** [comment]
Yes you can go for it!!

**Comment by nashid** [comment]
great - will give a go.

**Comment by danielcorin** [comment]
@nashid are you still looking into this?

**Comment by StefanosChaliasos** [comment]
Go for it @danielcorin

**Comment by danielcorin** [comment]
See #150. Not all features are working but it's a start

**Comment by StefanosChaliasos** [comment]
#150
