### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#301]

**Comment by StefanosChaliasos** [comment]
@SolaOmi go for it. It is straightforward what you should do. Just create a Dockerfile so one can create a container to use jarvis.

**Comment by StefanosChaliasos** [comment]
@SolaOmi any updates?

**Comment by akashshah26595** [comment]
@StefanosChaliasos Can I help to fix this issue? I've created few Docker files before.  It won't take too long.

**Comment by StefanosChaliasos** [comment]
I think @SolaOmi works on it.

**Comment by SolaOmi** [comment]
@StefanosChaliasos @akashshah26595 I'm having some trouble with the [dockerfile](https://gist.github.com/SolaOmi/831160dacf59cf4471b3d9f8cc56b9f1), it breaks down during the build when I get to the RUN ./setup.sh step, and returns this error:

"The command '/bin/sh -c ./setup.sh' returned a non-zero code: 1"

thoughts?

**Comment by StefanosChaliasos** [comment]
@akashshah26595 Do you want to help?

**Comment by akashshah26595** [comment]
@SolaOmi @StefanosChaliasos Try [this](https://gist.github.com/akashshah26595/1a7d4dd52e2fb51f02e5c3c8e74196bb) Dockerfile.

**Comment by akashshah26595** [comment]
Tested this Dockerfile. Container gets created launching bash, having files in /app directory, executing setup.sh and exposing port 80.

**Comment by StefanosChaliasos** [comment]
@SolaOmi any updates? @akashshah26595 do you want to create a PR with your DockerFile?

**Comment by akashshah26595** [comment]
- @StefanosChaliasos Can you provide more details on what this Dockerfile should do?
- It would help me to design Dockerfile accordingly.

**Comment by StefanosChaliasos** [comment]
Just create a Dockerfile that one could use it to run jarvis (interactive).

**Comment by jpigree** [comment]
Hello guys. I am motivated to take the task (I want to give it a try but inside a Docker anyway). I have a Dockerfile in which I installed Jarvis. I am debugging execution time issues at the moment.

**Comment by jpigree** [comment]
@SolaOmi, @akashshah26595 can I take the issue?

**Comment by StefanosChaliasos** [comment]
@jpigree please create a PR when the Dockerfile is ready.

**Comment by jpigree** [comment]
Okay. Thank you @StefanosChaliasos. I have still have dbus issues at the moment. I am working on it.

**Comment by jpigree** [comment]
Okay I created a PR. => https://github.com/sukeesh/Jarvis/pull/318

I have Jarvis running. I installed it in Python 3 by pure habit. Is that what we want? We can have 2 Dockerfiles since I see that some features (ask) are unaivalable in Python 3.

What function can I test to have a good faith into the fact that most Jarvis functions works? Do I have to test them all?

To be complete we should have automated builds + push to Dockerhub of the Docker image but this requires admin access to the repo.

**Comment by jpigree** [comment]
I am facing flaky tests on my PR in Python 2.7. From what I understand, those tests are unrelated to my PR (Jarvis is installed via the .travis.yml for travis tests). Moreover I can't assign anyone to review my PR. I lack the rights to do so. @StefanosChaliasos what should I do?

**Comment by jpigree** [comment]
@here Managed to make the PR build succeed by relaunching twice.

**Comment by appi147** [comment]
@StefanosChaliasos Please review this issue. I am unaware of Dockerfile atm

**Comment by anubhavsinha98** [comment]
Please tell me what Docker File will help here?
I am a begineer and I want to contribute.

**Comment by jpigree** [comment]
Hi @anubhavsinha98 . I already created the Dockerfile and I have submitted a PR. However, no maintainer had the time to actually review it.

**Comment by appi147** [comment]
Sorry @jpigree, I don't know about Dockerfile, so I can't merge it. IMO this project is modular such that persons can add their own functions that work for them. They can still in their forks. Lately, I am getting very less time due to studies. I hope your PR gets accepted

**Comment by jpigree** [comment]
Hey. No worries @appi147. :) I contributed this to help the community.
If it is accepted, it will be great.

**Comment by kapurm17** [comment]
Is this issue closed?

**Comment by kapurm17** [comment]
Is this issue still available to work on?
@pnhofmann I'd like to take this issue if it's available. Thanks :)

**Comment by appi147** [comment]
@kapurm17 There are already 2 PRs open. Can you review #318

**Comment by kapurm17** [comment]
@appi147 I dont think I'm that good, to review a PR, but I'll try.

**Comment by StefanosChaliasos** [comment]
#318
