### ISSUE TITLE
Request for contribution

### ISSUE THREAD

**Issue by kfragkedaki** [sukeesh/Jarvis#308]
I found interesting your project and I'd like to contribute to this. Is there anything that needs improvement?

**Comment by StefanosChaliasos** [comment]
There are numerous ways you can contribute to Jarvis. You can add any new feature you like or you can try to extend/improve existing functionalities. An other way to contribute is to write tests to improve the code coverage. Do you prefer to make small improvements or to implement a new feature?

**Comment by kfragkedaki** [comment]
I haven't thought of any new features yet, but I could contribute by writing tests in order to improve the existing code. However, if you have any suggestions, I am willing to try for something else as well.

**Comment by StefanosChaliasos** [comment]
Ok you can start with the tests and I will consider a new feature to work on.

**Comment by StefanosChaliasos** [comment]
It sounds great. Start with the extension. Please work in a new branch and make a pull request when it's ready for review!
