### ISSUE TITLE
Usage of Plugin Manager for features?

### ISSUE THREAD

**Issue by pnhofmann** [sukeesh/Jarvis#316]
I would suggest usage of a Plugin Manager. e.g.
https://github.com/benhoff/pluginmanager

Currently all commands are hard-coded in CmdInterpreter.py. If we could load commands dynamically from a file *.py in jarviscli/packages, most of CmdInterpreter would become redundant and this project more flexible.

- Adding Features would be made easier - drop only one file in one folder
- Clarity
- Users could remove unused plugins or add private plugins to solve user-specific problems, that does not make sense pushing upstream
- Not all features would have to support both Python 2 and Python 3 and all Systems  - Plugin Manager could check requirements
- This would include #110 - since objects are required for plugins.
- This would redundantize / include #111 - since a Plugin Manager would also reimplement CmdInterpreters self.actions.

I know this would be quite a big change.

In fact, this is something I'd like to implement and I'm asking for your opinion.

**Comment by StefanosChaliasos** [comment]
It sounds great! You could try to implement it. A good documentation will be needed for such big changes!

**Comment by pnhofmann** [comment]
Just short note about my progress:

Concept of Plugin-Class signature:

* Command Name = Class Name
* Help = Doc-String
* require() -> Iterator<String, String> (optional): specify requirements like os, linux. If one requirement not fullfiled, plugin will not be loaded
* complete() -> Iterator<String> (optional): new complete_* - method
* exec() -> : new do_* - method

Example:

```
import os

class Hotspot(pluginmanager.IPlugin):
    """
    start: Jarvis will set up your own hotspot.
    stop: Jarvis will stop your hotspot.
    """

    def require():
        yield ("os, "linux")

    def complete():
        yield "start"
        yield "stop"

    def exec():
        if "start" in s:
            system("sudo ap-hotspot start")
        elif "stop" in s:
            system("sudo ap-hotspot stop")
```
new Modules:

```
PluginManager:

load(path: str) -> int 
Returns number of loaded plugins

load_from_file(path: str) -> bool
True, if plugin loaded

load_from_directory(path: str) -> int
Returns number of loaded plugins

get_all() -> Iterator<Plugin>
get_by_name(name: str) -> Plugin


PluginDependency:

check(requirement: str, value: str) -> bool
```


Plan:
- [ ] Convert all plugins to classes
- [ ] Create module PluginManager to load and store plugins
- [ ] Rewrite CmdInterpreter to use PluginManager
- [ ] Implement PluginDependency
- [ ] Update Readme, documentation
