### ISSUE TITLE
Bug in issuing "Wiki"  command. 

### ISSUE THREAD

**Issue by kaynaat007** [sukeesh/Jarvis#321]
Hi,

Greetings @sukeesh . 

I cloned this repository as mentioned in instructions. I am playing around this a little bit and i think i found a bug where when you type "wiki" and the code crashes. The error raise is  `TypeError: cannot concatenate 'str' and 'NoneType' objects`.   

If it's indeed an issue, can i work upon this to fix this  ? 

Python version : 2.7.9 
OS:   Ubuntu 16.04 xenial
Kernel: x86_64 Linux 4.13.0-41-generic

**Comment by appi147** [comment]
@kaynaat007 Sure go ahead. Bug is that it crashes only when no input is given with wiki. Make adjustment so that function do_wiki handles no input.

**Comment by Mohit17067** [comment]
@kaynaat007 are you working on this?

**Comment by kaynaat007** [comment]
hey, i was unwell for quite a time.  Sorry for the delay. 
I shall pick it up from tomorrow  and fix it.

**Comment by appi147** [comment]
Yes, if no option is given along with `wiki`, then output should be a list of options

**Comment by Jamparan** [comment]
Is still open? I would like to work on it

**Comment by pnhofmann** [comment]
@Jamparan 
Still crashes e.g. for ``wiki search``. So suppose yes. Would actually be nice, if we could close this one ;).

**Comment by Jamparan** [comment]
I already created a PR for this but.
https://github.com/sukeesh/Jarvis/pull/375

**Comment by pnhofmann** [comment]
#375
