### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by singhvaibhavram** [sukeesh/Jarvis#332]
After installing through ./setup.sh, how do I uninstall it??

**Comment by pnhofmann** [comment]
Unfortunately there is no uninstall-script. You have to un-do steps manually (everything with root-Permission):

* Remove unwanted packages with package manager. Look at ./setup.sh to view what packages were installed. Note that packages like "ffmpeg" might be needed by other software. For example on Ubuntu you could probably do something like
``apt-get remove python-dbus-dev libssl-dev libffi-dev libdbus-1-dev libdbus-glib-1-dev libssl-dev libxft-dev libfreetype6-dev libfontconfig1-dev python-imdbpy chromium-chromedriver screenfetch``
But check if that does'nt remove anything you might need.
* If you use Fedora / Debian / Arch remove phantomjs:
```
rm -r /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
rm /usr/local/share/phantomjs
rm /usr/local/bin/phantomjs
rm /usr/bin/phantomjs
```
* If you are using Fedora, manually remove chromedriver
``rm /usr/bin/chromedriver``

Other dependencies are installed non-sytem-wide to your Jarvis-folder (env-directory). Just delete.

Let's see how #336 works out - maybe this will make uninstalling unnecessary.
