### ISSUE TITLE
Use twitter API?

### ISSUE THREAD

**Issue by pnhofmann** [sukeesh/Jarvis#340]
Like I already noted:

The current Twitter command relies on chromium-drivers; we would like python dependencies only.

Twitter in fact has an api for tweets - and there is also a python-library:
https://github.com/bear/python-twitter/blob/master/examples/tweet.py

Unfortunately this needs an API key.
https://developer.twitter.com/en/apply-for-access

Any thoughts or suggestions? Should we

* Use the Twitter-API
* Use old Twitter implementation (if chromium-driver exists)
* Drop any twitter support from Jarvis
* Find another way

**Comment by appi147** [comment]
We could have a config file with key, if present use twitter api, else tell user to create key on website and add to that file

**Comment by appi147** [comment]
We dont have twitter now
