### ISSUE TITLE
Show valid error message when no cricket matches are being played.

### ISSUE THREAD

**Issue by tmsreekanth98** [sukeesh/Jarvis#369]
Current state:
When "cricket" command is run jarvis shows "ALL MATCHES" and any input of choice gives a "Wrong choice" message. Screenshot is attached.

Expected state:
A valid error message which shows "No matches are currently being played. Please abort" to notify the user that there are not matches being played.
![jarvis2](https://user-images.githubusercontent.com/34984066/47951305-b0220080-df56-11e8-920a-453197a2f50a.png)

If this sounds good to you i will create a PR for this. Let me know your suggestions.

**Comment by appi147** [comment]
Yes pls

**Comment by tmsreekanth98** [comment]
> Yes pls

Working on a fix currently.

**Comment by tmsreekanth98** [comment]
> Yes pls

I have created a PR with the fix. Never mind for the first commit as i was also working for a Dockerfile for the project. It is not ready yet so i removed it. 

Thankyou

**Comment by pnhofmann** [comment]
>  as i was also working for a Dockerfile for the project

There is actually already #301 and #318 for Docker...

**Comment by tmsreekanth98** [comment]
Ok yea just saw that. Thanks for the heads up.

**Comment by pnhofmann** [comment]
8d44fe5ceba4515c540bc6eb2109df62a26467bc
