### ISSUE TITLE
Location specific answers to queries such as Time/Weather

### ISSUE THREAD

**Issue by SerDoggo** [sukeesh/Jarvis#370]
I noticed that jarvis is unable to provide me context specific answers to queries such as time/weather.

For example:
A query such as: "how is the weather?" or "how is the weather in delhi?" so instead of identifying just the key term "weather", I was thinking it would be possible to identify the location/context "in delhi" to provide the specific answer

If this suggestion seems promising and possible under the current system, I would like to work on a PR for this.

**Comment by SerDoggo** [comment]
> Wow, just noticed: "check weather in delhi" actually works as expected ;)
That's actually pretty interesting, i never thought to try that out. 
I'll try to clean this part up :).

**Comment by HectorRoblesWolf** [comment]
Is someone working on this?

**Comment by SerDoggo** [comment]
> Is someone working on this?

Yeah, I've spent some time understanding the flow of the code and have already solved the localized issue of weather. I will be submitting a PR soon.

Here's the long version of why the problem occurred and how i changed it:
weather_pinpoint.py actually checks the memory.json file stored in packages/memory/ to get the location. This meant that all context specific location was ignored and the weather at  your current location was provided. 

weatherIn.py works as expected, but at a very low level:
Basically all "check weather ...." actions are routed to weatherIn.main() 
where the words "weather" and "in" are removed and the remaining data  is considered as <location>
so a query like "check weather in delhi" would work but a query like "check weather at delhi"
would fail, because in this case the <location> is "at delhi" whereas in the former the location was "delhi"
 
Current Solution:
I am currently just rerouting all requests of the form " how/what is the weather in <location>" to the weatherIn.main() rather than the usual  weather_pinpont.main().
if weatherIn.main() fails, it automatically calls weather_pinpoint.main()

So now any query that falls into the "weather" action or "check weather" action are both routed to weatherIn.main() and in the event of its failure weather_pinpoint.main() is called.

Honestly, this doesn't currently seem like a robust solution. I am considering stripping sentences of all prepositions and connectors as well so queries such as "check weather at delhi" could work. I think this should also be done when pre-processing any query (apart from the current removal of punctuation).

I would like to hear any alternative solutions which are more robust,  as my lack of knowledge on the libraries used and the project as a whole may be to my detriment.

**Comment by pnhofmann** [comment]
> I think this should also be done when pre-processing any query (apart from the current removal of punctuation).

Yes, that would be the perfect solution.

There is [nltk](http://nltk.org/) to do stuff like that (and much more!). nltk is already included in Jarvis but currently only used to provide dictionary functionality.

Quick search showed, there is a module to remove "stop words": 

https://stackoverflow.com/questions/5486337/how-to-remove-stop-words-using-nltk-or-python

But integrating in Jarvis and not breaking everything is a task. Actually it's already somewhere on my todo-list, but didn't have the time and motivation yet ;).

If you like, you could take a look at nltk. Would also help if you want ;). And/or open PR with your current solution - would definitely be fine for now.

**Comment by SerDoggo** [comment]
I've submitted a pull request for the temporary solution now.

In general, i was thinking i would try to implement classical (or even machine learning) NLP techniques in the parsing and labeling of queries. But as you said this would be a huge undertaking. I am actually in the middle of trying to learn some NLP, so i am interested in trying to implement them in this project when I get the time.

I'll start looking into how we can use nltk to improve the system beyond just removing "stop words", and open a new issue once I am ready with some proper suggestions and find some feasible solutions. 

P.S Would appreciate any help that could lead me in the right direction as I am kind of a newbie.

**Comment by pnhofmann** [comment]
@SerDoggo Thanks!

> I'll start looking into how we can use nltk to improve the system beyond just removing "stop words", and open a new issue once I am ready with some proper suggestions and find some feasible solutions.

Sounds good!
