### ISSUE TITLE
Jarvis installation failing python2.7

### ISSUE THREAD

**Issue by lucifercr07** [sukeesh/Jarvis#379]
OS: Ubuntu16.04
Python version: 2.7.12
Installing collected packages: sympy, click, pyfiglet, termdown, wikipedia
./setup.sh: line 68: 47642 Killed                  pip install --upgrade -r requirements.txt

**Comment by pnhofmann** [comment]
Sorry, can't reproduce ;(.
Could you try re-run pip (in Jarvis folder):
```
source env/bin/activate
pip install --upgrade -r requirements.txt
```
And please post complete output.

**Comment by lucifercr07** [comment]
Issue was resolved thanks. Script was unable to activate virtualenv.
