### ISSUE TITLE
weather and news are not working properly

### ISSUE THREAD

**Issue by RottenCrab** [sukeesh/Jarvis#38]
Weather and news commands are not executing properly. This bug is may be caused because the location service is not working correctly (as expected).

**Comment by 5n8ke** [comment]
Please visit [http://freegeoip.net/]. How accurate is the data in the right hand box.

A possible fix would be to implement a way to manually set the current location.

**Comment by StefanosChaliasos** [comment]
Sometimes it works and sometimes it doesn't work (it depends on your location). I create exceptions for weather and news command.

**Comment by bwh91** [comment]
its only going to be as close as you are to your ISP's hub that you are connected to. Maybe add a function that the first time a location based request is run it asks for your location and then store it in a file a pickled object? and maybe add functionality to store 'locations' like work or home. that way the user could use that as an argument?

**Comment by StefanosChaliasos** [comment]
@bwh91  can you implement your ideas on this issue? It will be great!!

**Comment by StefanosChaliasos** [comment]
Does the news command works in your machines?

**Comment by bwh91** [comment]
It worked for me but I live right near a main hub but I tried it in a smaller town while on the road and it didn't even get the right city. I will work on this tonight. I believe I should be able to get it to work. @StefanosChaliasos

**Comment by StefanosChaliasos** [comment]
Ok great, go for it !!!

**Comment by StefanosChaliasos** [comment]
#36
