### ISSUE TITLE
ip plugin returns error for ipv4 and ipv6 on macos

### ISSUE THREAD

**Issue by bsushmith** [sukeesh/Jarvis#390]
ip plugin returns command not found error on macos

`Public ip v4 address :`
`sh: timeout: command not found`
`Public ip v4 address :`
`sh: timeout: command not found`

timeout is not natively supported on macos. So the ip plugin just returns the local address only correctly. We can use --connect-timeout option in curl command, which is supported by natively by curl command on all distributions.

**Comment by pnhofmann** [comment]
#391
