### ISSUE TITLE
will not run with Python3 pyttsx issues

### ISSUE THREAD

**Issue by bwh91** [sukeesh/Jarvis#40]
tested with python 3.4 and python 3.5. There is an issue with pyttsx compatibility with python3. I have contacted the owner of the project to try and see if we can get those issues resolved.

**Comment by bwh91** [comment]
It works on python3 when pyttsx is installed from source

**Comment by StefanosChaliasos** [comment]
If it works can you please close the issue?

**Comment by bwh91** [comment]
Well as it stands when you download Jarvis and run 'pip install -r requirements.txt' the version it pulls does not work. You have to manually download the source and install from that. So its still an issue. I have sent the owner of the project an email to see if I can get the few trivial fixes added that way when pip install is run it works as expected. If you still want to me to close the issue I think we should note this somewhere at least.

**Comment by StefanosChaliasos** [comment]
You are wright. No let the issue open and hope someone will found a permanent solution.

**Comment by StefanosChaliasos** [comment]
#83
