### ISSUE TITLE
forex-python 1.2 requires dbus

### ISSUE THREAD

**Issue by pnhofmann** [sukeesh/Jarvis#403]
Just noticed, that forex-python - the backend we use for Currencyconv - added dbus-python as requirement in its newest release (1.2). The added a cli interface with notification support - which we don't use anyway. Since we just removed dbus because it's a non-python requirement which requires native extension installing dbus-python "just for fun" would be kind of "stupid".

With pip we can't really blacklist packages:
https://github.com/pypa/pip/issues/3090
"I'm going to close this because fundamentally we don't want to provide an option to users that lets them create a broken environment"

I have added forex-python==1.1 to requirements.txt - but this is no solution for ever since it's quite common that old libs don't work because some online-API changed.

I already created an [upstream issue](https://github.com/MicroPyramid/forex-python/issues/56). Any other ideas?

**Comment by ravigadila** [comment]
fixed issue in forex-python==1.3.

https://github.com/MicroPyramid/forex-python/issues/56

**Comment by pnhofmann** [comment]
Thanks! Honestly didn't expect solution in such a short time!
