### ISSUE TITLE
Where am I Command Issue

### ISSUE THREAD

**Issue by jsgtihub** [sukeesh/Jarvis#414]

**Comment by jsgtihub** [comment]
When typing in "Where am I" the code returns an error.

**Comment by appi147** [comment]
screenshot or logs pls

**Comment by appi147** [comment]
![screenshot from 2019-02-17 00-46-08](https://user-images.githubusercontent.com/32510534/52904123-72b75980-324d-11e9-9721-2c8f8db6b3b0.png)
