### ISSUE TITLE
Show me pics of.... Command not working.

### ISSUE THREAD

**Issue by jsgtihub** [sukeesh/Jarvis#418]
When entering 

show me pics of " "

I get 

I could not identify your command...

**Comment by jadsonlucio** [comment]
I believe the command you are looking for is: display me pics of.
But it would be interesting if there was a alias system that associated display and show.

**Comment by jadsonlucio** [comment]
I believe the command you're looking for is: display pics of.
But it would be interesting if there was a alias system that associated display and show.

**Comment by YasmineBOU** [comment]
Hi!

We're students of the University of Paris 8 in France.
In one of our subjects, we have to contribute in an open source project.

We would like to know if we could work on it?

**Comment by pnhofmann** [comment]
@topic
``But it would be interesting if there was a alias system that associated display and show.``
Luckily there is in fact an alias-system ;). Yes, should be no problem aliasing "show" to "display"!  

@YasmineBOU 
Please **always** open a new issue for a new topic. I can't really move your comment. So to answer your question anyway:
This is basically a first time contributors project for beginners to learn. This project is designed to be easy. Just saying ;).
If this is OK for your course (and there are really no requirements that you have to contribute to a bigger project) - of course.

**Any contributions are welcome!** Just open an issue and explain, what you want to implement. Or look at the opened issues, if you want to fix something described there. Or just open an issue "Request for contribution" and we will find something for you to do ;).
