### ISSUE TITLE
Create wiki

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#42]

**Comment by knittingarch** [comment]
@StefanosChaliasos  Can you provide more details on what you are looking for?  Github has a wiki option, so I'm not sure if you mean create a wiki in Github or some other way.  Thanks!

**Comment by StefanosChaliasos** [comment]
I mean a Github wiki. The most important section of that wiki must be the functionalities of Jarvis. For example you could create a section with all the functionalities of Jarvis and an example for each one.

**Comment by yashLadha** [comment]
How about create a static web page? @StefanosChaliasos

**Comment by StefanosChaliasos** [comment]
We could do that but right know the wiki would be very helpful!

**Comment by SolaOmi** [comment]
Still need a wiki or is someone working on it?

**Comment by krishnapaul242** [comment]
May I go for it? @StefanosChaliasos

**Comment by StefanosChaliasos** [comment]
Yes go for it. Any help will be welcomed!!!

**Comment by krishnapaul242** [comment]
@StefanosChaliasos 
then add me as a collaborator, So, I could help on documentation and wiki.

**Comment by krishnapaul242** [comment]
@StefanosChaliasos 
forked this project and creating a wiki like this.
<a href="https://github.com/krishnapaul242/Jarvis/wiki"> Jarvis wiki</a>

just started..

**Comment by krishnapaul242** [comment]
May I create  facebook page??

**Comment by StefanosChaliasos** [comment]
@krishnapaul242 Could you please create a pull request for the wiki? @sukeesh what about the FB page?

**Comment by krishnapaul242** [comment]
@StefanosChaliasos 
I tried but seems like Github is only comparing the code, not the wiki.
I tried to Google this problem and found "GitHub doesn't support pull requests for the wiki repository" See here - <https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github>

**Comment by sukeesh** [comment]
@krishnapaul242 If FB page is for discussing, We already have a gitter chat.

**Comment by krishnapaul242** [comment]
@sukeesh 
By a Facebook page, Jarvis would have more reach. That is my opinion.

**Comment by StefanosChaliasos** [comment]
@krishnapaul242 we made the wiki public (for editing) you can add your changes now.

**Comment by StefanosChaliasos** [comment]
Great work @krishnapaul242 !!

**Comment by krishnapaul242** [comment]
Thank you @StefanosChaliasos
