### ISSUE TITLE
Junior Contributor 

### ISSUE THREAD

**Issue by ionpetro** [sukeesh/Jarvis#422]
Hello, I would like to contribute to this open source project (University initiative)
I am new to this community, but I would like to learn more so I can contribute as much as I can.
Is there anything I can do for your project? (have some experience in Python)
Working on Windows but willing to boot Linux if needed.
Thank you beforehand.

**Comment by pnhofmann** [comment]
Hi and welcome!

> Is there anything I can do for your project? (have some experience in Python)
> Working on Windows

That would actually be an option. There is a initial windows port (#346; windows-port branch) but isn't finished yet. That's definitely something you could do if you like. 

Or of course anything I wrote here: #421. We are open for any improvements and new features and happy for every contribution.

**Comment by sanketdhole** [comment]
Hello,
long ago I have an eye on this project but was little learner in python. Now, I think I could contribute to this project. Please help me get started for contribution.

**Comment by pnhofmann** [comment]
@sanketdhole 
Hi!

> Please help me get started for contribution.

I have just updated documentation (-> README.md) how to write jarvis commands (=plugins). Hope it is understandable - if something is unclear please tell me so I can improve it ;).
Yes, basically choose what you want to do. Either implement a new command or improve an existing one. Or work on something linked above.
And if there are any problems or questions, please ask. And best create a new issue ;).
