### ISSUE TITLE
new_feature - Game

### ISSUE THREAD

**Issue by qwireq** [sukeesh/Jarvis#448]
I can implement a simple console game '[Bulls and Cows](https://en.wikipedia.org/wiki/Bulls_and_Cows)' as a new plugin. It is pretty straightforward but interesting game.

**Comment by appi147** [comment]
Sure! Interesting game for console.

**Comment by JonanOribe** [comment]
Another easy game that we can implement can be something like:

Using the dictionary plugin, we take the definition of a world and the user must try to find what the word is. For each right answer, he wins 10 points and the game ends when the user fails 3 words.

**Comment by qwireq** [comment]
Could you help me with my pull request, please? For some reason, tests are failing on BMI plugin, but I did not modify anything there. #472

**Comment by appi147** [comment]
Yeah, dont worry for BMI, build failed with last merge. I'll fix it tomorrow

**Comment by pnhofmann** [comment]
Sorry ;).

Completely forgot to check Python 2.

**Comment by pnhofmann** [comment]
Of course - in Python 3 ``1/2=0.5`` while in Python 2 "int / int = int" - so ``1/2=0``. I've created a fix  #473 since this was my fault. Sorry again.

**Comment by qwireq** [comment]
Don't worry, everything is ok =). Now, in order to complete my pool request, I should download changes that you made from the origin?

**Comment by pnhofmann** [comment]
> Now, in order to complete my pool request, I should download changes that you made from the origin?

No need! Diffs do not conflict (since different files were changed) - so git is able to handle the merge without problem.

**Comment by qwireq** [comment]
Great! I updated my pull request, now it is passing all tests. Thanks!
