### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JonanOribe** [sukeesh/Jarvis#455]
I want to ask if there is any kind of roadmap for the project development. This is because i'm interesting about know what are the mainly functions that,you guys, consider prioritary

**Comment by pnhofmann** [comment]
There is no Roadmap I'm aware of ;).

This is more like, everyone programs what he feels like it - or what anyone finds useful.

Personally - Even more testing, improveVoice Control and finish Windows Ports would be what I consider "TODO".

**Comment by JonanOribe** [comment]
Ok,thanks for the orientation. I will think how to solve these topics
