### ISSUE TITLE
how to run jarvis on mac?

### ISSUE THREAD

**Issue by Aiki-bot51** [sukeesh/Jarvis#456]
i dont know how to run jarvis on mac. any one know?

**Comment by appi147** [comment]
Clone the repo.
Run setup.sh
Run `jarvis`

**Comment by Aiki-bot51** [comment]
Before I run Jarvis should I type “cd Jarvis” ?

**Comment by madhavkulkarni1986** [comment]
@Aiki-bot51 
- Clone repo
- cd to Jarvis
- Run setup
- Run jarvis

**Comment by Aiki-bot51** [comment]
nope didnt work
<img width="578" alt="Jepretan Layar 2019-03-31 pukul 16 50 41" src="https://user-images.githubusercontent.com/48476126/55287596-355df400-53d5-11e9-9a2c-c80f58337ab4.png">

**Comment by Aiki-bot51** [comment]
oh it works you need to type "cd Jarvis" then type "source setup/ ./setup.sh" then type "./jarvis"
