### ISSUE TITLE
More Complex Random Password

### ISSUE THREAD

**Issue by donaldvluc** [sukeesh/Jarvis#460]
Would it be beneficial to add more character classes as options for the user to choose from when making a new password? Like special characters and brackets and such? If so I would like to contribute in that regard.

**Comment by JonanOribe** [comment]
Sounds good, prepare your PR and ,if you find any problem,just contact with me ;)

**Comment by donaldvluc** [comment]
Looks like MichaelND implemented my idea. Thanks
