### ISSUE TITLE
Upgrade health bmi plugin

### ISSUE THREAD

**Issue by ionpetro** [sukeesh/Jarvis#466]
Dear Jarvis community,

So I was working on a **Body Mass Index** calculator plugin for Jarvis, but then I found out that something similar has already been implemented on [health](https://github.com/sukeesh/Jarvis/blob/windows-port/jarviscli/plugins/health.py)

However, my implementation supports more features like the following ones:
1) Support metric and imperial system
2) Include colorama library, using colors for each result
3) Print the body state according to the results (severe thinness, healthy, pre-obese etc.) 

Moreover, I intend to test my plugin making sure that the result is always correct.

So, may I send you a pull request with the changes I recommend on health plugin?

Thank you in advance,

**Comment by appi147** [comment]
Sure go ahead

**Comment by pnhofmann** [comment]
#469
