### ISSUE TITLE
Plugin to generate random number

### ISSUE THREAD

**Issue by rogervieiraa** [sukeesh/Jarvis#476]
Hi, I'm new here and I would like to contribute.
First I need to say that I liked so much the idea.
I want to create a plugin that generates a random number, and the user can set the start and the end, what do you think about this feature? Can someone guide me on how to start?

**Comment by appi147** [comment]
Checkout #450 . Its similar to your idea. All the documentation is available in docs/ folder

**Comment by rogervieiraa** [comment]
Thanks sir, I will start.
