### ISSUE TITLE
New plugins

### ISSUE THREAD

**Issue by skpanagiotis** [sukeesh/Jarvis#477]
I create three new plugins that are unit converters. I have begun to make converters for the area, length and time.

**Comment by appi147** [comment]
Open PR

**Comment by skpanagiotis** [comment]
I have already done a [pull request](https://github.com/sukeesh/Jarvis/pull/489).

**Comment by skpanagiotis** [comment]
I'm also thinking of making the game rock, paper, scissors for Jarvis
