### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by pupun97** [sukeesh/Jarvis#479]
If we access any plugin(that require connection) without internet connection that it throws an whole error not a error message. I already made some changes to solve it if u guys want i will create pull request.
Problem:-
![Screenshot from 2019-04-27 10-54-28](https://user-images.githubusercontent.com/47047786/56845197-e7a4b080-68da-11e9-89ad-4588b9f593fb.png)
Solution:-
![Screenshot from 2019-04-27 10-56-57](https://user-images.githubusercontent.com/47047786/56845220-60a40800-68db-11e9-8dfa-9cce18f0e68a.png)
Note:-
I am new to github correct me if do anything wrong

**Comment by appi147** [comment]
I think there was a option of connection error earlier.

**Comment by appi147** [comment]
`AttributeError: 'Jarvis' object has no attribute 'connection_error'`
This line intrigues me

**Comment by appi147** [comment]
@pnhofmann may help you on this issue

**Comment by pnhofmann** [comment]
Yeah, with plugin manager I created a feature to automatically catch 'requests.exceptions.ConnectionError' for all plugins which require network.

Today, I don't really think this was a good idea.

I would remove this "feature" and create e.g. a decorator 'check_network_exception' instead. But of course @pupun97 if you like, you could show us your solution, too!

**Comment by pupun97** [comment]
I made these changes...
commit the line:-
`jarvis.connection_error()`

and
add that line:-
`jarvis.get_api().say(Fore.BLUE+"Sorry, Internet connection is required to access this command!")`

in plugin._plugin_run_with_network_error()

**Comment by pupun97** [comment]
@pnhofmann i read the code and i think i find the misktake in the line(in plugin.py).
instead of this line
`jarvis.connection_error()`
it should be 
`jarvis.get_api().connection_error();`
after that change all things are good.

**Comment by pnhofmann** [comment]
Yeah, do you want to send the pull request?

**Comment by pupun97** [comment]
Yes I am sending

**Comment by pnhofmann** [comment]
Thanks!
