### ISSUE TITLE
Plugin: Open a website

### ISSUE THREAD

**Issue by rogervieiraa** [sukeesh/Jarvis#483]
I'm thinking about this command for Jarvis and how can work nice.

Basically, this will work in 2 ways.

## Input a complete link:
`> open website www.google.com`
This one will validate if the link is valid before the open.

## Use a dictionary with popular links
`> open website GitHub username`
This will open the respective GitHub page.

If the name isn't on dictionary and isn't a validated link the plugin will print a message.

What do you think about this one? Can I start to build it?

**Comment by cyberboysumanjay** [comment]
This should do the trick for you!


`import webbrowser`
`webbrowser.open(url)`

**Comment by Rickecr** [comment]
Hi, I am interested in solving this issue. Can ?

**Comment by pnhofmann** [comment]
Hi!
hmm,  rogervieiraa did actually quite a good job: #484 
But you could review this PR. Or create a new plugin. Or try to improve existing plugin ;).

**Comment by Rickecr** [comment]
Oh, I didn't even realize it was already resolved in an old PR.

**Comment by pnhofmann** [comment]
#484
