### ISSUE TITLE
Only specific commands can be recognized

### ISSUE THREAD

**Issue by jajupmochi** [sukeesh/Jarvis#490]
It it true that only specific commands can be recognized? Can I randomly command?
The response for me is now like this:

`~> What can i do for you?

sing

I could not identify your command...

~> What can i do for you?

sing a song

I could not identify your command...

~> What can i do for you?

what is your name

I could not identify your command...

~> What can i do for you?

how are you

I could not identify your command...

~> What can i do for you?

how are you?

I could not identify your command...

~> What can i do for you?

where am i

You are at Évry

~> What can i do for you?

restaurant near me

Hold on!, I'll show restaurant near you

~> What can i do for you?

how old are you

I could not identify your command...

~> What can i do for you?

open camera

Opening cheese.......`

**Comment by 5a8l3y3** [comment]
That's what I said I couple of months in another issue that is called "No natural commands and responses of the Assistant". If you know something about NLP and want to help would be great because right now I'm trying to learn but I'm not the best programmer in the world right now...

**Comment by pnhofmann** [comment]
> what I said a couple of months in another issue

Just to link: #424 

So I'll close this one as duplicated.
