### ISSUE TITLE
Feature Proposal: Define word command

### ISSUE THREAD

**Issue by TarunApp** [sukeesh/Jarvis#492]
# Questions
- How does this project look upon using separate packages such as Beautifulsoup?
  - I would like to create a feature that defines a word. I have some experience in web-scraping and would like to help with this project. 
- Before I start I wanted to get some input from you guys, how shall I go about implementing this in regards to project parameters? 

### Thank you, sorry if I didnt follow any guidelines.

**Comment by pnhofmann** [comment]
> How does this project look upon using separate packages such as Beautifulsoup? 

We have zero problem with python-only libraries dependencies. We currently even use Beautifulsoup for some modules (e.g. hackathon) - so Beautifulsoup is installed anyway. Just import and use ;). And maybe not scrap sites if the admin disallows ;).

> I would like to create a feature that defines a word. 

Note: we currently have a command 'dictionary' (works offline). Please also check if there is no API for what you want to do.

But if you think your feature is useful, go for it! 

> how shall I go about implementing this in regards to project parameters?

Should follow PEP8 standards (so  `flake8 --select E,W --max-line-length=140 --ignore E722 jarviscli/` should not yield any formatting issues).

I have documented some basic stuff about creating plugins in README.md. If something is unclear, please ask!

**Comment by TarunApp** [comment]
Hello, I have not yet embarked on this project yet because I am on windows. I have seen recent issues and posts relating to some troubles with windows. Additionally, do you know where I can get an indepth document on testing projects and contributing to them also. I am familiar with contributing, but I feel that there is a little vagueness, perhaps its me, but I just want to be efficient in my contributions. Thank you for the information!

**Comment by appi147** [comment]
@TarunApp Jarvis works on windows fine now. Feel free to ask any questions if you are willing to work on it

**Comment by shreyubee** [comment]
I would like to work on this

**Comment by pnhofmann** [comment]
Closing stale issue
