### ISSUE TITLE
Non-ASCII character '\xe2' in file jarvis.py on line 4

### ISSUE THREAD

**Issue by AibelKingslayer** [sukeesh/Jarvis#494]
File "jarvis.py", line 4
SyntaxError: Non-ASCII character '\xe2' in file jarvis.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by AibelKingslayer** [comment]
please plaese please help me

**Comment by pnhofmann** [comment]
Hi!
That's an interesting error and can't reproduce. Could you provide more information (os, python version, branch)?
Line 4 of Jarvis.py is actually just:
`from colorama import Fore`
But it is actually '**J**arvis.py' and not '**j**arvis.py'. Strange...

**Comment by AibelKingslayer** [comment]
thank you for your reply my os parrot sec os python 2.7

**Comment by pnhofmann** [comment]
Hmm, could you try cleaning python cache:

(in Jarvis directory)

```
find . -name '*.pyc' -delete
find . -name  __pycache__ -delete 
```

**Comment by AibelKingslayer** [comment]
ok

**Comment by AibelKingslayer** [comment]
bro the main file is Jarvis.py right

**Comment by AibelKingslayer** [comment]
but its not executing when i type sudo python Jarvis.py

**Comment by AibelKingslayer** [comment]
File "Jarvis.py", line 7, in <module>
    from CmdInterpreter import CmdInterpreter
  File "/home/aibel/Jarvis/jarviscli/CmdInterpreter.py", line 10, in <module>
    from utilities.voice import create_voice
  File "/home/aibel/Jarvis/jarviscli/utilities/voice.py", line 7, in <module>
    import pyttsx3
ImportError: No module named pyttsx3

**Comment by AibelKingslayer** [comment]
pip install pyttsx3
Requirement already satisfied: pyttsx3 in ./.local/lib/python2.7/site-packages (2.7)

**Comment by AibelKingslayer** [comment]
still error bro please help me please

**Comment by pnhofmann** [comment]
> sudo python Jarvis.py

Please no sudo!

> bro the main file is Jarvis.py right

No - actually not. You need to run

``./setup.sh``

This will install all pip-requirements and create a start-script jarvis.sh.

**Comment by AibelKingslayer** [comment]
ok

**Comment by AibelKingslayer** [comment]
thanks bro 
now its working

**Comment by pnhofmann** [comment]
;)
