### ISSUE TITLE
Error when setting up Jarvis

### ISSUE THREAD

**Issue by CDR-Isaac** [sukeesh/Jarvis#497]

**Comment by CDR-Isaac** [comment]
ERROR: Complete output from command /home/pi/github_projects/JARVIS/Jarvis/env/bin/python3 /home/pi/github_projects/JARVIS/Jarvis/env/lib/python3.5/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ijhqbygx/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- 'setuptools>=18.5' wheel 'cffi>=1.8,!=1.11.3; python_implementation != '"'"'PyPy'"'"'':
  ERROR: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
  Collecting setuptools>=18.5
    Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
  Collecting cffi!=1.11.3,>=1.8
    Using cached https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz
  Collecting pycparser (from cffi!=1.11.3,>=1.8)
    Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.19-py2.py3-none-any.whl
  Building wheels for collected packages: cffi
    Building wheel for cffi (setup.py): started
    Building wheel for cffi (setup.py): finished with status 'error'
    ERROR: Complete output from command /home/pi/github_projects/JARVIS/Jarvis/env/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-bbi5ur_s/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-43exsrj_ --python-tag cp35:
    ERROR: Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.5
    creating build/lib.linux-armv7l-3.5/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/model.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/api.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/cparser.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/error.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/__init__.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/commontypes.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/verifier.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/recompiler.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/lock.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/_embedding.h -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.5/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-armv7l-3.5
    creating build/temp.linux-armv7l-3.5/c
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.5m -I/home/pi/github_projects/JARVIS/Jarvis/env/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.5/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for cffi
    Running setup.py clean for cffi
  Failed to build cffi
  Installing collected packages: setuptools, wheel, pycparser, cffi
    Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Complete output from command /home/pi/github_projects/JARVIS/Jarvis/env/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-bbi5ur_s/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mr6y_s3f/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-ijhqbygx/overlay --compile --install-headers /home/pi/github_projects/JARVIS/Jarvis/env/include/site/python3.5/cffi:
      ERROR: Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-3.5
      creating build/lib.linux-armv7l-3.5/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/model.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/api.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/cparser.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/error.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/__init__.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/commontypes.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/verifier.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/recompiler.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/lock.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/_embedding.h -> build/lib.linux-armv7l-3.5/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.5/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-armv7l-3.5
      creating build/temp.linux-armv7l-3.5/c
      arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.5m -I/home/pi/github_projects/JARVIS/Jarvis/env/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.5/c/_cffi_backend.o
      c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
       #include <ffi.h>
                       ^
      compilation terminated.
      error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
      ----------------------------------------
  ERROR: Command "/home/pi/github_projects/JARVIS/Jarvis/env/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-bbi5ur_s/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mr6y_s3f/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-ijhqbygx/overlay --compile --install-headers /home/pi/github_projects/JARVIS/Jarvis/env/include/site/python3.5/cffi" failed with error code 1 in /tmp/pip-install-bbi5ur_s/cffi/
  ----------------------------------------
ERROR: Command "/home/pi/github_projects/JARVIS/Jarvis/env/bin/python3 /home/pi/github_projects/JARVIS/Jarvis/env/lib/python3.5/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ijhqbygx/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- 'setuptools>=18.5' wheel 'cffi>=1.8,!=1.11.3; python_implementation != '"'"'PyPy'"'"''" failed with error code 1 in None

**Comment by pnhofmann** [comment]
Hi!
Thanks for your bug report.
```
linux-armv7
```

You are on ARM? Guess, probably raspberry pi or something similar? Somehow your system is missing some packages...

Please try to install

```
python3-cffi
```

and see if works now. If not: As a walkaround open **requirements.txt** and replace the line:

```
requests[security]
```

with

```
requests
```

Nevertheless, Jarvis should install with pure python and no other requirements - I'll update the installer to handle this issue sometime next week.

**Comment by CDR-Isaac** [comment]
Hey, I had to install quite a few things, and it works, but thanks for the help!

**Comment by mikeperalta1** [comment]
I also got endless errors until I finally installed every dependency. I think this project could get a little more traction if the README.md file listed all the dependencies you'd need to install, so everyone can easily find it. Especially on the Raspberry Pi.

I might try building this from scratch on Raspbian eventually. If I do, I'll try to make note of what steps I took.

**Comment by pnhofmann** [comment]
Hi! And thanks for your response. In fact our aim is that at last basic functionality works with zero dependencies besides clean python (plus virtualenv).
I actually did some experimenting on an improved installer which among other things should fix this issue (#498) - but was to lacy to review + test + merge yet ;).
