### ISSUE TITLE
Crypto Tracker Feature

### ISSUE THREAD

**Issue by Ian-Gabaraev** [sukeesh/Jarvis#504]
# A handy tool to monitor cryptocurrency prices.

```
import requests
import json

#ANSI escape sequences to print in color
class color:
    GREEN = '\033[92m'
    RED = '\033[91m'
    TAIL = '\033[0m'

#List of default crypto pairs
favorite = [
	'BTC/USD',
	'BTC/ETH',
	'BTC/LTC',
	'BTC/XRP'
]

#If the price is down, print in red. If the price is up, print in green
def print_in_color(change):
	if float(change) < 0:
		return color.RED + str(change) + color.TAIL
	else:
		return color.GREEN + str(change) + color.TAIL

#Main function. It requires the base and target
#crypto symbols, e.g. [BTC, XRP] 
#to build a URL.

def query(base, target):

	#Bulding a url from base and target currency symbols
	#It must look like this: https://api.cryptonator.com/api/ticker/btc-eth

	url = 'https://api.cryptonator.com/api/ticker/{}-{}'.format(base.lower(), target.lower())

	try:
		response = requests.get(url).json()

		price = response['ticker']['price']
		change = response['ticker']['change']


	#This error occurs if the pair is non-existent
	except KeyError:
		print "Wrong pair {}/{}! \nFull list of symbols is here: https://coinmarketcap.com/all/views/all/\n".format(base, target)

	#Results
	else:
		print "\t{}/{}\nPrice: {}\nChange: {} {}\n".format(base, target, price, print_in_color(change), target)

#Iterate over your favorite crypto pairs
def check_favorites():
	for pair in favorite:
		base, target = pair.split('/')
		query(base, target)

#go!
check_favorites()
```

**Comment by pnhofmann** [comment]
Hi!
Looks good to me! Would you like create Pull Request?

You would just have to convert your code to a plugin. But that's actually quite easy:
* from plugin import plugin
* Add ``@plugin("cryptotracker")`` above ``def check_vafourites():`` (and remove ``#go! check_favourites()``)
* Make ``def check_favorites():`` a ``def check_favorites(jarvis, s):``

If you need any help (e.g. with git/github) just ask!

**Comment by pnhofmann** [comment]
Yep, OK I see #506. Not really like PRs work, but no problem, this project is a really good opportunity for learning ;).

So, first, here's something for you to bookmark:

* https://git-scm.com/book/en/v2/

Quite a lot to read, but "Pro Git" is a really good book about everything interesting about git. And it's free and good for look up stuff ;). Also contains chapter about github:

* https://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration

* Noticed you already forked Jarvis repo. That's the first step.
* Make changes locally (put your code in jarviscli/plugins/cryptotracker.py)
* Commit your changes
* Push your changes to your fork
* And then Press the "Create PR"-Button

And if there are any questions, please ask.

**Comment by Ian-Gabaraev** [comment]
> Yep, OK I see #506. Not really like PRs work, but no problem, this project is a really good opportunity for learning ;).
> 
> So, first, here's something for you to bookmark:
> 
> * https://git-scm.com/book/en/v2/
> 
> Quite a lot to read, but "Pro Git" is a really good book about everything interesting about git. And it's free and good for look up stuff ;). Also contains chapter about github:
> 
> * https://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration
> * Noticed you already forked Jarvis repo. That's the first step.
> * Make changes locally (put your code in jarviscli/plugins/cryptotracker.py)
> * Commit your changes
> * Push your changes to your fork
> * And then Press the "Create PR"-Button
> 
> And if there are any questions, please ask.

Thank you, pnhofmann!
I am really new to this, but I followed your instructions. I have committed the cryptotracker.py to the master branch.
I like this project, and I would love to make a useful contribution!

**Comment by Ian-Gabaraev** [comment]
> Yep, OK I see #506. Not really like PRs work, but no problem, this project is a really good opportunity for learning ;).
> 
> So, first, here's something for you to bookmark:
> 
> * https://git-scm.com/book/en/v2/
> 
> Quite a lot to read, but "Pro Git" is a really good book about everything interesting about git. And it's free and good for look up stuff ;). Also contains chapter about github:
> 
> * https://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration
> * Noticed you already forked Jarvis repo. That's the first step.
> * Make changes locally (put your code in jarviscli/plugins/cryptotracker.py)
> * Commit your changes
> * Push your changes to your fork
> * And then Press the "Create PR"-Button
> 
> And if there are any questions, please ask.

Amazing :)
I appreaciate your being so helpful, pnhofmann!
Let us connect on Facebook?

**Comment by pnhofmann** [comment]
> Let us connect on Facebook?

Sorry - don't use Facebook.
