### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by lugoc20** [sukeesh/Jarvis#510]
After running some license scanning programs i found out that  about 16 of the modules have GPL3 license while JARVIS is supposed to have MIT license.

**Comment by pnhofmann** [comment]
And?

GPL3 does not enforce licensing necessary under GPL3 - but under GPL-compatible. Look GPL FAQ:
https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean

The MIT (or X11) License is definitely GPL compatible.
https://www.gnu.org/licenses/license-list.html

So I see no problem! But feel free to re-open if you disagree.
