### ISSUE TITLE
[new_feature] New feature - Add a typing test as a game 

### ISSUE THREAD

**Issue by Sanil2108** [sukeesh/Jarvis#514]
I thought it would be cool to add a typing test as a game, I am not sure how multiple games would work though. It could be the command line equivalant of this - https://thetypingcat.com/typing-speed-test/1m .

**Comment by pnhofmann** [comment]
Hi!
Like this idea! You want to work on this?

> I am not sure how multiple games would work though

Would probably call this feature just 'typing test' or 'test typing'?
Or we just say there is 'game bulls and cows' and 'game typo'.

**Comment by Sanil2108** [comment]
> Really like this idea! You want to work on this?
Yes! I will start implementing it.
> Would probably call this feature just 'typing test' or 'test typing'?
I think "typing test" could be a good name.
