### ISSUE TITLE
Run commands directly from the terminal

### ISSUE THREAD

**Issue by aeciorc** [sukeesh/Jarvis#519]
I thought it would be nice to able to get jarvis to run a command directly from the terminal, i.e, without having to initialize it and wait for the prompt.
For example:
 `jarvis roll` would initialize jarvis, run the dice.py plugin, print the ouput and exit. 

If it is approved, I would love to implement it myself.

**Comment by pnhofmann** [comment]
Hi!
Like this idea ;). Looking forward to your PR!

**Comment by aeciorc** [comment]
Awesome, I just submitted it :)

**Comment by pnhofmann** [comment]
Thanks!
#520
