### ISSUE TITLE
New feature Read out pdf file

### ISSUE THREAD

**Issue by TobiOkanlawon** [sukeesh/Jarvis#521]
I always find myself in a position where I have a long pdf file to read and something else to do at the same time. It'll be nice if jarvis could read out those pdf files for me. I already had a first try implementation, but pyaudio isn't installing on my system, so I can't test the concept.

Can someone else implement this please?

**Comment by pnhofmann** [comment]
Yep, would be quite useful!
There are python-libraries to extract PDF text - printing this text would probably possible with like 2 lines of code.

Biggest challenge I see: You probably won't want e.g. whole table of content read loud. Or read first part, pause, and sometimes later continue reading the long pdf. Or skip one page.
We would probably need some concepts how the user can interact with Jarvis and how Jarvis should react.

**Comment by TobiOkanlawon** [comment]
Thanks, you're really making a lot of sense with this. I had the same problem with Microsoft's pdf reader on edge back when I used Windows. Maybe, making the reader 'smart' wouldn't be a bad idea. I really wish I would implement this myself, would be a great learning experience.

**Comment by plant999** [comment]
or can we have like reda the text of the pdf and try to make a synopsis out of it and then make jarvis read it.

**Comment by snal** [comment]
Hello, with a few friends we are interested in implementing this feature. For the moment we are still considering how to do it in a proper way (deciding what should be read and how this should be done for example).

**Comment by aneeketMangal** [comment]
I think pypdf2 and further pyttsx might come handy.

**Comment by pnhofmann** [comment]
Closing as stale. If someone wants to work on this, please re-open.

**Comment by MakisEu** [comment]
I would like to work on this.
