### ISSUE TITLE
stock does not work

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#530]
API has been moved to new url, needs registration and authentication

**Comment by appi147** [comment]
@pnhofmann Can we add a modifier like @require, for packages that are not supported atm, until they are fixed.

**Comment by pnhofmann** [comment]
Either that or we set platform=[]

**Comment by madhavkulkarni1986** [comment]
I feeel, we have two options to fix this: 

1.  Just like in the news plugin, as the user to register here https://iexcloud.io/cloud-login#/register and provide a way to add the apikey into memory. The same can be passed to the api query. There is a free tier with 500000 queries per month per key.

2. Find a new api that provides a authentication less access to stock data(https://github.com/public-apis/public-apis#finance => https://financialmodelingprep.com/ seems to be good)

Both have pros and cons. I personally would prefer to have the 2nd way, which also provides more endpoints to enhance stock plugin and include more functionality.

**Comment by madhavkulkarni1986** [comment]
This issue is fixed with the new API. Please check PR #554 
Let me know if this is acceptable.

**Comment by pnhofmann** [comment]
#554
