### ISSUE TITLE
Proper name for new command

### ISSUE THREAD

**Issue by alexandr7035** [sukeesh/Jarvis#535]
I want to create a new feature. Should i use such prefixes as "write ...",  "tell ..." or "print ..." in my command in order not to litter output of the "help" command? (especially if my command will have some aliases)

**Comment by appi147** [comment]
`help` command is an issue. You can name your plugin as you like.

**Comment by alexandr7035** [comment]
> `help` command is an issue. You can name your plugin as you like.

Thanks!)
