### ISSUE TITLE
Search google for questions Jarvis doesn't have a plugin for

### ISSUE THREAD

**Issue by CremBluRay** [sukeesh/Jarvis#537]
I noticed that Jarvis doesn't understand google-search type questions, so I was wondering if I could work on a plugin that searched google and parsed the results.

**Comment by CremBluRay** [comment]
I was thinking I could use something like serpwow to do it. It would be really simple and might improve natural language understanding of the AI.

**Comment by appi147** [comment]
Go ahead!

**Comment by CremBluRay** [comment]
thanks! I'm on it!

**Comment by PappaStalin** [comment]
Because this feature has gone a wile without being implemented, and it seems like it would add a lot of extensibility to Jarvis, I'm going to see If I can get something like this to work.

**Comment by PappaStalin** [comment]
I think that this is a great idea, and that it would add a lot of extensibility to Jarvis. However, this issue has not been resolved in 3 months. Do you mind if I try to add this feature?

**Comment by PappaStalin** [comment]
I've made a quick and dirty plugin that you can find here: https://pastebin.com/QvmFQWym

**Comment by pnhofmann** [comment]
> Do you mind if I try to add this feature?

Sure - go ahead.

> I've made a quick and dirty plugin that you can find here: https://pastebin.com/QvmFQWym

Yeah, something like this...

https://pypi.org/project/google/

> I was thinking that, instead of returning "I could not identify your command" when Jarvis runs into an error, it prompts the user if they want to google the question. this could also be done explicitly with the search command.

As an optional feature, which needs to be enabled manually, I'd be OK with that.

But don't like the idea of stuff getting sent to Google by default.

**Comment by PappaStalin** [comment]
I've got the google plugin up and running, the only issue is the BS4 raises a UserWarning (No parser was explicitly specified) when Jarvis is run. I know that this is because of the pluginmanager module, but I don't really know why this is the case or how to hide the error. 

the code for my repo can be find here: https://github.com/PappaStalin/Jarvis

**Comment by pnhofmann** [comment]
Hmm, yes - known issue I should really document somewhere (and this time I hopefully won't forget again, Sorry ;) ).

Only import
```
import BeautifulSoup
```

and use as ```BeautifulSoup.bs4```. Otherwise PluginManager crease bs4-instance to check if bs4 is a plugin - and that prints UserWarning.

**Comment by pnhofmann** [comment]
Nice @PappaStalin  - another issue to close ;)

#537
