### ISSUE TITLE
Voice output fails in Mac if the text has non command line friendly literals

### ISSUE THREAD

**Issue by sravanjosh** [sukeesh/Jarvis#542]
Following is my observations in MacOs.

~> Hi, what can I do for you?
buy
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `say Pick a site (Amazon or Ebay)'
Pick a site (Amazon or Ebay)

**Comment by appi147** [comment]
Can you suggest fix for it? Cause we don't have access to mac

**Comment by pnhofmann** [comment]
May be related to #501. Think the fix I posted there could fix this one, too - honestly forgot to commit + push the change.

**Comment by appi147** [comment]
Hey @sravanjosh , if you have access to mac and if you are free this weekend, can you help me test a PR if I ask you?

**Comment by sravanjosh** [comment]
Sure. I can. But I think this is a simple fix for Mac.
Me being looking for contributing, can I take up this issue my self?

**Comment by appi147** [comment]
Yeah you can fix it. I meant for another PR I am working on.

**Comment by sravanjosh** [comment]
Sure. for other PR, I can help you test. But not this weekend.
Please drop me a message.

**Comment by appi147** [comment]
Sure. Whenever you are free :+1:

**Comment by sravanjosh** [comment]
Submitted a pull request for this. Please review and merge.

**Comment by appi147** [comment]
#545
