### ISSUE TITLE
Speech bug: jarvis.say('') causes "segmentation fault"

### ISSUE THREAD

**Issue by alexandr7035** [sukeesh/Jarvis#546]
I noticed that jarvis crashes if I run 'game' with enabled sound
`~> Hi, what can I do for you?`
`enable sound`
`~> What can i do for you?`
`game`
`./jarvis: строка 3:  6807 Segmentation fault      (стек памяти сброшен на диск) python /home/alexandr7035/prog.d/Jarvis/jarviscli/ $*`

The game crashes at the following string:
`jarvis.say('')`

Found that this is an issue of  pyttsx3:
`>>> eng = pyttsx3.init()`
`>>> import pyttsx3`
`>>> eng = pyttsx3.init()`
`>>> eng.say('')`
`>>> eng.runAndWait()`
`Segmentation fault (стек памяти сброшен на диск)`

**Comment by alexandr7035** [comment]
I see jarvis for windows also uses pyttsx3, but i can't test this fix by myself, so added only for linux

**Comment by appi147** [comment]
It does not crash on windows
