### ISSUE TITLE
Jarvis says 'Speech not Supported!' even when I have pyttsx3 installed

### ISSUE THREAD

**Issue by TobiOkanlawon** [sukeesh/Jarvis#548]
The results of both pip and pip3 install pyttsx3 is a``` Requirement already satisfied and stored in .../local/lib/python3.7/.... ```

Meanwhile enable sound on jarvis returns ```Speech not supported! Please install pyttsx3 text-to-speech engine (sapi5, nsss or espeak)```.

Is there something that needs to be done that I didn't do?

**Comment by pnhofmann** [comment]
Linux? Like error message says, you need sapi5, nsss or espeak. I usually use espeak - e.g. Ubuntu simply sudo apt-get install espeak

**Comment by TobiOkanlawon** [comment]
Why not just drop it in the requirements file?

**Comment by pnhofmann** [comment]
Because these text2speech engines are not Python dependencies and therefore can't be installed with python pip / requiements.txt. And unfortunately I don't know any alternative which can be installed with pip.
