### ISSUE TITLE
Add feature - File converter on command

### ISSUE THREAD

**Issue by Aceee-dev** [sukeesh/Jarvis#549]
I am very much interested in implementing a feature in which we can convert one file format to other by giving command to jarvis.

For example from doc to pdf  etc.
Is this feature already existing ?

**Comment by appi147** [comment]
Sure. Go ahead

**Comment by plant999** [comment]
ok, already started working on it..

**Comment by baptoutiego** [comment]
Hello!
If the issue is not close yet, I would be glad to take it from now.
Is there still anything i can do on the file convertor? :)

**Comment by plant999** [comment]
sure, Go ahead !!

**Comment by pratheekcr** [comment]
Hi there, is this issue still open? I am a first time contributor, is this a difficult task for a beginner?

**Comment by anukul123** [comment]
> Hi there, is this issue still open? I am a first time contributor, is this a difficult task for a beginner?
no it is nor pratheek. You can obviously try.

**Comment by pnhofmann** [comment]
Closing because issue is stale. If someone wants to work on this, please reopen.
