### ISSUE TITLE
Add plugin - website status check

### ISSUE THREAD

**Issue by mikek4233** [sukeesh/Jarvis#559]
I am interested in having a plugin that you put in a website and you get back the status code. I started working on this already.

Do you have any thoughts?

**Comment by pnhofmann** [comment]
Hi, sounds good!
I guess you are using python requests library?
If this plugin could e.g. return for 301 Moved Permanently also new location, think this plugin could actually become really helpful!

**Comment by mikek4233** [comment]
Sounds good! 

I am using a library called urllib 

I think my V1 will just return the status code and then I will work on adding maybe what each code means and if it moved then the new location as well. Is that ok?

**Comment by mikek4233** [comment]
#565 Merged
