### ISSUE TITLE
What do you think about implementing command line functionality to Jarvis class?

### ISSUE THREAD

**Issue by AnderRasoVazquez** [sukeesh/Jarvis#57]
Python's [Cmd class](https://docs.python.org/2/library/cmd.html) provides a simple framework for writing line-oriented command interpreters. I've been playing a little making Jarvis class to inherit from it. Here's a demo with the commands that I've implemented so far *the Cmd way*.

![command line in jarvis](https://cloud.githubusercontent.com/assets/3936719/24755315/f8555494-1ad9-11e7-9454-d08e05ed6b3a.gif)

Cmd class **provides tab completion, command history, ctrl-L to clear window and a lot of great tools** to manage commands. This method of managing and extending Jarvis is different from the current one: Let's see `clock` command for example:
 
``` python
    def do_clock(self, s):
        """
        Gives information about time.
        """
        print(Fore.BLUE + ctime() + Fore.RESET)

    def help_clock(self):
        """
        Prints help about clock command.
        """
        print("Gives information about time.")
```

# Quick overview of Python's Cmd class

`cmd.cmdloop()` is the main loop. When it is called it shows the prompt and asks user for input. When hitting enter, Cmd takes the line entered, executes a function according to it and passing to it the rest of the arguments of the line. If we enter `clock` it will execute the corresponding command. For a command to work, Cmd requires a function named `do_command` with a parameter where it will add the rest of the line. Clock's function would be `do_clock`, weather's `do_weather`... etc.

There's also `help_command` to show help about that command. All the commands that have a `help_command` function are shown in `help` command.
```
~> Hi, what can i do for you?
help

Documented commands (type help <topic>):
========================================
ask    decrease    exit     increase  near  pinpoint  remind    todo   
check  directions  goodbye  movies    news  quit      say       weather
clock  evaluate    help     music     os    reboot    shutdown

~> What can i do for you?
help clock
Gives information about time.
``` 

# A command prompt is cool but I want to communicate with Jarvis using sentences too

Commands like "what about chuck", or "what's the weather like" are a cool way to interact with Jarvis. So I was thinking that we could delegate parsing small commands (<=2 words) to Cmd class and for longer ones use some natural language processing to extract the intent of the line ([nltk](http://www.nltk.org/) module can do this).

For example: if we extract the nouns of `what's the weather like` we would get `weather`. We can pass it to Cmd and it will know what command to execute. 

# Before continuing

I've done this just for fun, because I wanted to try coding something with Cmd class. If you are interested in this I would be happy to finish it, clean it and make a pull request. I've only made changes to Jarvis.py class, [here's the code](https://github.com/AnderRasoVazquez/Jarvis/blob/command_line_implementation/Jarvis/Jarvis.py) if you want to take a look.

**Keep up the good work! =)**

**Comment by sukeesh** [comment]
This looks so cool!

**Comment by StefanosChaliasos** [comment]
It looks very interesting. Do you have any idea on how we could refactor the Jarvis class because it's very big?

**Comment by AnderRasoVazquez** [comment]
Yes, at the moment it looks huge, but I have some ideas. We could start doing the easiest task, one line docstrings wherever it's possible:
```python
def help_clock(self):
        """
        Prints help about clock command.
        """
        print("Gives information about time.")
```
```python
def help_clock(self):
        """Prints help about clock command."""
        print("Gives information about time.")
```
This will save us two lines for every command, because those docstrings are very short.

**Now, let's take a look at the biggest function, `weather`**:
```python
def do_weather(self, s):
        """
        Get information about today's weather.
        """

        location = MEMORY.get_data('city') #Will return None if no value
        if location is None:
            loc = str(location)
            city = mapps.getLocation()['city']
            print(Fore.RED + "It appears you are in " + city + " Is this correct? (y/n)" + Fore.RESET)

            try:
                i = raw_input()
            except:
                i = input()
            if i == 'n' or i == 'no':
                print("Enter Name of city: ")
                try:
                    i = raw_input()
                except:
                    i = input()
                city = i

            mapps.weather(str(city))

            MEMORY.update_data('city', city)
            MEMORY.save()
        else:
            loc = str(location)
            city = mapps.getLocation()['city']
            if city != loc:
                print(Fore.RED + "It appears you are in " + city + ". But you set your location to " + loc + Fore.RESET)
                print(Fore.RED + "Do you want weather for " + city + " instead? (y/n)" + Fore.RESET)
                try:
                    i = raw_input()
                except:
                    i = input()
                if i == 'y' or i == 'yes':
                    try:
                        print(Fore.RED + "Would you like to set " + city + " as your new location? (y/n)" + Fore.RESET)
                        try:
                            i = raw_input()
                        except:
                            i = input()
                        if i == 'y' or i == 'yes':
                            MEMORY.update_data('city', city)
                            MEMORY.save()

                        mapps.weather(city)
                    except:
                        print(Fore.RED + "I couldn't locate you" + Fore.RESET)
                else:
                    try:
                        mapps.weather(loc)
                    except:
                        print(Fore.RED + "I couldn't locate you" + For.RESET)
            else:
                try:
                    mapps.weather(loc)
                except:
                    print(Fore.RED + "I couldn't locate you" + Fore.RESET)
```
Wow, 60 lines of code. This doesn't look very clean, Jarvis shouldn't be the one to handle the `weather`. Do you think that it might be a good idea to make a package for every *skill* Jarvis has? We could end up with an implementation like this:

```python
from packages import weather
# the command might look like this
def do_weather(self, s):
        """Get information about today's weather."""
        weather.main()  # if the skill needs input -> skill.main(s)
```
**3 lines instead of 60**. Another good thing about having the implementation of the skill separated in a package is that it allows isolated tests from Jarivs. We can test new skills and when we are sure that it works we can add them as a new command to Jarvis. Do you have any more ideas?

**Comment by StefanosChaliasos** [comment]
Obviously we should create packages for each skill. I agree with your idea about comments too but i think we need something more efficient like having all actions in other file or files. I don't have any idea right now on how to do that.

**Comment by AnderRasoVazquez** [comment]
We can make Jarvis.py very small if we take out the command interpreter functionality out to another class.

![captura de pantalla de 2017-04-08 11-50-55](https://cloud.githubusercontent.com/assets/3936719/24827837/f30ccfde-1c51-11e7-9014-d7f0f9b04af3.png)

This way we would have all the actions in other file. What do you think?

**Comment by StefanosChaliasos** [comment]
In Jarvis class we will have only the user_input, speak find_action methods? If you can implement it do it. I made some refactoring to Jarvis class (like your proposal for weather and inline comments).

**Comment by AnderRasoVazquez** [comment]
> In Jarvis class we will have only the user_input, speak find_action methods?

Yes, that's right. I'll start implementing it.

**Comment by AnderRasoVazquez** [comment]
Oh, and thanks @StefanosChaliasos for considering my proposal for weather and inline comments.

**Comment by AnderRasoVazquez** [comment]
I've finished the command line implementation. I changed find_action method code that it can recognize commands if it finds those command words in the input, let's take a look at the result:
![captura de pantalla de 2017-04-09 13-51-29](https://cloud.githubusercontent.com/assets/3936719/24837078/58f70140-1d2c-11e7-88a1-d3fd482ec958.png)

[Pull request](https://github.com/sukeesh/Jarvis/pull/61)
