### ISSUE TITLE
Notify on reminder.py module is not working

### ISSUE THREAD

**Issue by RottenCrab** [sukeesh/Jarvis#58]
I have successfully installed gi, but Notify is not recognized and as a result while running Jarvis an AttributeError is raised.

**Comment by StefanosChaliasos** [comment]
@5n8ke

**Comment by 5n8ke** [comment]
The APT dependencies are:
- python-gobject
- libnotify-bin

Try displaying a notification with
`notify-send "Title" "Notification description"`

Which Desktop Manager are you running? Perhaps you have different dependencies than on Gnome.

**Comment by 5n8ke** [comment]
@RottenCrab Have you some more information regarding your issues with Notify?

**Comment by RottenCrab** [comment]
No i do not, i have a busy schedule this month. When i find a solution about this issue i will post to inform you.

**Comment by yigalbeer** [comment]
Hi, I just tried to use the source in order to become a contributer, but facing the same issues with gi (v1.2) - which doesn't have Notify (actually not require_version and repository as well), using Ubuntu 16.04. & Python v2.7.12
Any update on that?

**Comment by alokst** [comment]
Facing same issue as @yigalbeer .

**Comment by alokst** [comment]
Replaced Notify with notify2 . solves the issue. PR #112 .

**Comment by StefanosChaliasos** [comment]
@RottenCrab , @yigalbeer does PR #112 solved your issue?
