### ISSUE TITLE
Jarvis Installation Issue on Arch Linux

### ISSUE THREAD

**Issue by prasannarajaram** [sukeesh/Jarvis#581]
I cloned the git repo to install Jarvis onto my Arch linux. 
_espeak_ did not install during the process
I could not run `$ jarvis` from the command line in the terminal.
Here is a installation dump from [pastebin](https://pastebin.com/WTgiKAMf).

**Comment by pnhofmann** [comment]
> I could not run $ jarvis from the command line in the terminal.

Sorry! Seriously forgot to set execute Permission (+x) to the installer. Quick fix for you:

```sudo chmod +x  /usr/local/bin/jarvis```

And I'll immediately fix this issue.

**Comment by pnhofmann** [comment]
By the way: Are you apart from that satisfied with our (new) installer? Anything unclear or stuff you noticed that can be improved?

Just for me to get some feedback and maybe to learn from that ;).
