### ISSUE TITLE
Use Jarvis with virtualenv.

### ISSUE THREAD

**Issue by marcjal** [sukeesh/Jarvis#584]
Hi 👋!

I have some problems to use Jarvis. I'm using Python 2.7.10 and a virtual environment. When I saw the README I think that was only that but the `python installer` I confused with that because is a folder and not a file. When I enter to installer folder I install the dependencies from requirements.txt. So if someone can help me I'd be very happy

**Comment by appi147** [comment]
Hi @marcjal Python 2 support has just been dropped. Check releases page. Last version (without installer) to support python 2 is present there. Or go to 1.0 tag

**Comment by marcjal** [comment]
@appi147 Hi 👋! Thanks for your comment. I'm going to do that

**Comment by appi147** [comment]
Let me know if you face any issue

**Comment by marcjal** [comment]
@appi147 Sure! I'm going to study the code I would like to contribute. How can I help to be part of collaborators?

**Comment by appi147** [comment]
To be a collaborator, you need to stay for some time with this project. Review PRs and the current codebase, and how can be it improved.

**Comment by marcjal** [comment]
@appi147 cool 😎! I got it. So I'm studying right now the code.

I have a question maybe is silly but what is the advantage of using docker in this project?

**Comment by pnhofmann** [comment]
> I have a question maybe is silly but what is the advantage of using docker in this project?

Actually - this is a good question! So good, that I just noticed, docker currently is broken ;) (*).
If you don't use docker, just ignore it ;).

(*) I'll fix it later
