### ISSUE TITLE
Move plugins/animations.py to utilities / JarvisAPI

### ISSUE THREAD

**Issue by pnhofmann** [sukeesh/Jarvis#596]
Propose and plan to implement:

* Move plugins/animation.py to utilities folder
* Add spin_start and spin_stop to JarvisAPI
* Make sure, spinning stops in all cases - even if exception is thrown

**Comment by pnhofmann** [comment]
Sure!

**Comment by akshgpt7** [comment]
If this hasn't yet been implemented, Can I go for it?

**Comment by pnhofmann** [comment]
@jay24rajput what's your status/progress on this issue?

**Comment by jay24rajput** [comment]
I am working on it, will issue the PR in a day or so. Sorry for the delay! I was caught up a bit!

**Comment by jay24rajput** [comment]
@pnhofmann, when you say add spin_start in every function the spinner is hardly visible, for example, tried it with enable_voice() and the spinner wasn't even visible. Look at the code:
  ```
  def enable_voice(self):
        """
        Use text to speech for every text passed to jarvis.say()
        """
        spinner=SpinnerThread('Enabling Voice',0.15)
        spinner.start()

        self._jarvis.enable_voice = True

        spinner.stop()
        print_say("Voice Enabled", self, Fore.GREEN)
```
The shifting of animations.py to utilities is done. Do you still want me to implement spinner for all utility functions??

**Comment by pnhofmann** [comment]
No stress - we are all doing this just for fun ;).

> when you say add spin_start in every function

Actually did not say that. Or at last did not mean to say that - maybe expressed myself bit unclear (Sorry in this case). What I actually meant:

https://github.com/sukeesh/Jarvis/blob/master/jarviscli/CmdInterpreter.py#L18

Would be nice to add two functions ``spinner_start()`` and ``spinner_stop()`` here so it's possible to write plugins like:

```
@plugin("demo")
def demo(jarvis, s):
    jarvis.spinner_start()
    # ... do stuff ...
    jarvis.spinner_stop()
```

**Comment by jay24rajput** [comment]
Okay issued the PR! Please check

**Comment by pnhofmann** [comment]
#620
