### ISSUE TITLE
[QUESTION] How can I use voice?

### ISSUE THREAD

**Issue by weathon** [sukeesh/Jarvis#598]
I install all the needs library(Software), but now it only accepts my text input but cannot listen to my sound.
I am using Raspbian on Raspberry Pi 1 B+

**Comment by appi147** [comment]
Try `hear` command

**Comment by weathon** [comment]
It can hear me now but still cannot read out the answer

**Comment by appi147** [comment]
You need to `enable sound`

**Comment by weathon** [comment]
@appi147 
It only can read out "WHat can I do for you" but not the reply

**Comment by pnhofmann** [comment]
What are you Jarvis asking to do? Might be an issue with this command, you are trying to use...

**Comment by weathon** [comment]
I ask the weather

**Comment by jay24rajput** [comment]
@pnhofmann the issue here is that the control is not being transferred back to the `voice_controller.py`. I think if we make `voice_controller.py ` a utility instead of a plugin, we can use it in various functions for giving output through voice. For example the **SpinnerThread** in `animations.py`.  
Thoughts?

**Comment by pnhofmann** [comment]
>  I think if we make voice_controller.py a utility instead of a plugin, we can use it in various functions for giving output through voice. 

* voice_controller.py is for recognizing what you speak only (input) 
* "Speaking out loud" (output) is implemented in ``utilities/voice.py`` and can be accessed with ``jarvis.say()`` (Jarvis will only speak out load if enabled with ``enable sound``
* voice_controller.py is in an early stage (#411) and I still haven't found time to improve yet. But sure, having voice_controller as a utility instead plugin will be unavoidable at some point. But currently voice_controller.py is more like a test ;).

**Comment by jay24rajput** [comment]
Okay! Sounds cool

**Comment by pnhofmann** [comment]
So, since voice control tracked in another issue and apart from that this question looks answered, I'm closing this.
Feel free to reopen if issue persists.
