### ISSUE TITLE
Help needed for procedure to create and deploy new plugin

### ISSUE THREAD

**Issue by akshgpt7** [sukeesh/Jarvis#608]
I've made a new plugin for jarvis, however, I cannot find the actions tuple in CmdInterpreter.py .
Also, how can I deploy the plugin into jarvis' plugin list and check if it's working fine?

**Comment by pnhofmann** [comment]
No need! Just drop your plugin - something like this

```
from plugin import plugin


@plugin("helloworld")
def helloworld(jarvis, s):
    """Repeats what you type"""
    jarvis.say(s)
```

In the ``jarviscli/plugins``-folder. Your plugin will be found and auto-loaded.

**Comment by akshgpt7** [comment]
Thank you very much for the help!
