### ISSUE TITLE
Fix open website plugin

### ISSUE THREAD

**Issue by akshgpt7** [sukeesh/Jarvis#611]
The open website plugin doesn't work currently.
Can I take up the task of fixing it?

**Comment by pnhofmann** [comment]
Sure, you can try...
I'm pretty sure, issue must be somewhere here:
https://github.com/sukeesh/Jarvis/blob/master/jarviscli/Jarvis.py#L135

But could be a conceptional problem, which would make this issue really, really hard (like implementing natural voice recognition => #424).

**Comment by pnhofmann** [comment]
This won't fix the real problem, but I would suggest this workaround for now:

* Rename "open website" to "browser"
* Rename your new "browser"-plugin to "browser google"

**Comment by pnhofmann** [comment]
#612
