### ISSUE TITLE
[New Feature] Give user option to create custom Routines 

### ISSUE THREAD

**Issue by theViz343** [sukeesh/Jarvis#613]
So I was thinking to let users have option to create custom routines and call them by any name they choose. A routine is a collection of commands executed one by one whenever the specific routine's name is called.
It will increase user personalization and might be interesting to implement. What say?

**Comment by aprzn123** [comment]
As the pull request to close this issue seems to be abandoned, could I work on this and finish what they started?

**Comment by pnhofmann** [comment]
#748
