### ISSUE TITLE
[NEW FEATURE] Configurable colours for CLI prompts

### ISSUE THREAD

**Issue by shydefoo** [sukeesh/Jarvis#615]
I'm interested in contributing to this project, thought this would be a good way to start. 
Saw that the cli colours are hard coded using `colorama`, any interest/objections in making them configurable? The implementation could be discussed further, perhaps using a config file or default environment variables. 

This could fall under personal configurations, but thats a much broader topic.

**Comment by pnhofmann** [comment]
Sounds really promising!

Probably most complicated task to think of good names how to call configurable colors. And bit of a task change colors for different plugins.

But if you would like to try, sure would be nice!

> perhaps using a config file or default environment variables.

Prefer config file. In fact there is already a config file which could be used.

https://github.com/sukeesh/Jarvis/blob/master/jarviscli/CmdInterpreter.py#L149

**Comment by arjunk2004** [comment]
Is this still being worked? If not, I'd like to give it a shot.

**Comment by pnhofmann** [comment]
Close in favor of #615
