### ISSUE TITLE
Aliases also showing in list of plugins on typing 'help'

### ISSUE THREAD

**Issue by akshgpt7** [sukeesh/Jarvis#617]
The ```help``` command should show only the plugin names available, however, it is displaying all the aliases as well. This makes the plugin list redundant and hard to look for what you need.
I think aliases are only an alternative to those commands and should not show up in the actual list of plugins on typing 'help'. This will make ```help``` more effective.

**Comment by pnhofmann** [comment]
Hmm, agree... But will be a bit tricky to implement. I'll add this to my imaginary list and will check what I can do ;).

**Comment by nemesis06** [comment]
I'm new to Open Source. I'd like to work on this, if it's ok.

**Comment by pnhofmann** [comment]
If you like, sure!

Currently Jarvis used help output from [Cmd](https://docs.python.org/3/library/cmd.html), you would probably need to rewrite the complete help-function.

**Comment by nemesis06** [comment]
Oof, I will try my best.

**Comment by arjunk2004** [comment]
Great! Also, do you happens to know where the help function is @akshgpt7 ?

**Comment by arjunk2004** [comment]
PR #706 created.
Jarvis now does this:
![Screenshot from 2020-06-12 12-15-11](https://user-images.githubusercontent.com/49816728/84538927-5c85a600-aca7-11ea-8ae7-58d8b91db2f7.png)
This is an alternative that I came up with:

![Screenshot from 2020-06-12 12-31-05](https://user-images.githubusercontent.com/49816728/84539705-c6eb1600-aca8-11ea-9e35-966a84904496.png)


I think the first method is better, but I wanted to put the alternative up to see what you all thought of it.

**Comment by lit3ral** [comment]
Can we resolve this issue?

**Comment by akshgpt7** [comment]
Fixed in #706
