### ISSUE TITLE
[CALORIES ERROR] impossible to put correct input 

### ISSUE THREAD

**Issue by baptoutiego** [sukeesh/Jarvis#627]
I launched calories in Jarvis cli and I couldn't managed to put correct input.
I think the error appears because the use of "is" instead of "=="  on different string. As the "is" test memory allocation, this couldn't work. I would be glad to solve this issues by replacing the line 43 and 45 of calories.py file.
![Screenshot from 2019-11-20 15-49-11](https://user-images.githubusercontent.com/33863595/69248991-82354b80-0bad-11ea-85c9-f254ffda1e42.png)

**Comment by appi147** [comment]
Sure!

**Comment by appi147** [comment]
#628
