### ISSUE TITLE
battery plugin didn't work in linux mint 

### ISSUE THREAD

**Issue by Baocaifeng** [sukeesh/Jarvis#636]
hello, the battery plugin dind't work in linux mint

**Comment by pnhofmann** [comment]
Hi!
battery plugin basically calls 'upower'.
Related: #590 - PR for 'battery plugin implementation without upower'. Would probably be a good idea to merge that PR soon, which should also fix this issue ;).

**Comment by pnhofmann** [comment]
#590 merged which should make this obsolete. If issue persists, please reopen.
