### ISSUE TITLE
Feature request: Extract sound from youtube video

### ISSUE THREAD

**Issue by Guissey** [sukeesh/Jarvis#643]

**Comment by appi147** [comment]
What do you think of such "features" @pnhofmann ? Are that ethical? Moreover, there are number of apps available on Internet for the same

**Comment by pnhofmann** [comment]
Don't have a problem with youtube downloaders...

Would rather point to the fact, that a 'download sound form youtube'-plugin in fact already exists for quite a while ;).
https://github.com/sukeesh/Jarvis/blob/master/jarviscli/plugins/music.py

So, another plugin to just extract audio, probably not - but e.g. a full youtube-dl binding (which could download audio and/or video from lots of sources), if someone would like to have one and is willing to implement, for all i care, yes.
