### ISSUE TITLE
Feature : img to pdf converter and pdf to image converter

### ISSUE THREAD

**Issue by ytabyaoui** [sukeesh/Jarvis#645]

**Comment by pnhofmann** [comment]
Would be nice addition to #647 - sure, go ahead!

**Comment by h4ppysmile** [comment]
Hi @pnhofmann !
Is this issue still open? Can I work on it?

**Comment by pnhofmann** [comment]
Hi! No update since December - so guess, yes, if you like to work on this: Sure!

**Comment by jay24rajput** [comment]
@pnhofmann Is the issue up for grabs?

**Comment by pnhofmann** [comment]
If @h4ppysmile does not answer: sure!

**Comment by h4ppysmile** [comment]
Hi!
Unfortunately I didn’t work on it!
Hope you do well.

**Comment by jay24rajput** [comment]
Thanks @h4ppysmile! 
- - -
@pnhofmann should we implement it as a plugin in form of a new files, for example: 
````
jarviscli/plugins/imagetopdf.py
jarviscli/plugins/pdftoimage.py
````
