### ISSUE TITLE
[Feature] Voice speed control

### ISSUE THREAD

**Issue by aazuspan** [sukeesh/Jarvis#653]
I think it would be great if the user could control the speed of Jarvis's speech when voice is enabled. I'm thinking this could be accomplished by adding some plugins to voice.py so the user could type 'talk faster' or 'talk slower'. Additionally, the user's preferred speed would be saved in Jarvis' memory and would be recalled on startup if voice is enabled. I'll start looking into how exactly to implement this, but I'm open to any suggestions on functionality or implementation.

**Comment by pnhofmann** [comment]
#654
