### ISSUE TITLE
New features: tic tac toe and workout program provider

### ISSUE THREAD

**Issue by DannKim98** [sukeesh/Jarvis#659]
Hi, I really want to contribute to this project and implement some new features. Now I am thinking about kind of a personal push-up and pull-up workout program provider, based on the maximum number of times a user can do these exercises, with a timer to rest between sets. And another plugin I want to implement is a game "tic tac toe". @pnhofmann what do you think about them?

**Comment by pnhofmann** [comment]
Sure!

Both features sound good - small games are always nice for sure. And the workout program would finally make more use of utilities/notification.py and utilities/schedule.py; both are used by plugins/reminder.py but for nothing else ;).

If you need help or don't understand something about our documentation ( ;) ) don't hesitate to ask.
