### ISSUE TITLE
How to update requirement.txt

### ISSUE THREAD

**Issue by chekoduadarsh** [sukeesh/Jarvis#662]
I was adding a new feature for Jarvis but I want to add opencv-python to requirement.txt since I am doing that I am getting problem in Tavis, pls look into this pull request https://github.com/sukeesh/Jarvis/pull/661

**Comment by pnhofmann** [comment]
Sure - your requirements.txt is correct. Travis is complaining about a trailing whitespace (-> PEP8).

```
jarviscli/plugins/bulkresize.py:50:29: W291 trailing whitespace
The command "flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/" exited with 1.
```

**Comment by chekoduadarsh** [comment]
@pnhofmann Silly me didn't see that  Thanks for the help!!!
