### ISSUE TITLE
Changing the voice of assistant

### ISSUE THREAD

**Issue by chekoduadarsh** [sukeesh/Jarvis#663]
Hey,
 When I was checking up the voice mode of Jarvis, it wasn't pleasant to listen it was super robotic and non-human like. Proposing a migration from `pyttsx` to a combination of `gtts` and `playsound` which gives a way better humanitarian approach!!

**Comment by pnhofmann** [comment]
Sure!
Just, would prefer to let the pyttsx code in Jarvis and add gtts as an alternative backend (and make the user choice if he wants to send stuff to google or not).

``jarviscli/utilities/voice.py`` does implement 3 backend anyway - one for Windows, one for Mac and one for Linux. On Mac pyttsx isn't even used ;).

**Comment by chekoduadarsh** [comment]
> Just, would prefer to let the pyttsx code in Jarvis and add gtts as an alternative backend (and make the user choice if he wants to send stuff to google or not).
Will do it

**Comment by OneHighCloud** [comment]
I am working on Win10 with the code. In voice.py, I made some changes regarding voice (VoiceWin()). Might help you.
`self.engine = pyttsx3.init("sapi5")
 voices = self.engine.getProperty("voices")
 self.engine.setProperty("voice", voices[1].id)
 self.engine.setProperty("rate", 140)`

**Comment by Methenitis** [comment]
Hey! 

After communicating with @chekoduadarsh , my colleague @annakotsa and I have worked on adding GTTS as an option for voice generation and fixed the parameters of pyttsx3 in order to make the voice sound less robotic.

Would love to get your feedback on this @pnhofmann 

Thank you in advance!

**Comment by pnhofmann** [comment]
#686
