### ISSUE TITLE
Windows Installer: "python 3" not found

### ISSUE THREAD

**Issue by pnhofmann** [sukeesh/Jarvis#664]
I'm running Windows 7 on my laptop and it has python 3 and the directory is called as `Python38-32`. Now, do I need to create a symlink? and where do i need the symbolic link? 

Below is the cmd snapshot when I run setup.bat
![jar](https://user-images.githubusercontent.com/36512165/75477027-a03af500-59c1-11ea-8e39-8543dde93ace.png)

_Originally posted by @Karthick-Balaji in https://github.com/sukeesh/Jarvis/issues/424#issuecomment-592123608_

**Comment by pnhofmann** [comment]
Not like I am an expert on Windows - and not like Windows 7 is supported... But could reproduce issue with Windows 10 and current Python installer.
For some reasons, there is no binary 'py'? But only 'python'?
Will work on a patch tomorrow.

**Comment by appi147** [comment]
I'm not sure if they changed behavior. The documentation still states that py should work.
[https://docs.python.org/3/using/windows.html#from-the-command-line](https://docs.python.org/3/using/windows.html#from-the-command-line)

**Comment by pnhofmann** [comment]
Hmm:
https://stackoverflow.com/questions/51861943/how-to-install-python-launcher

Created #665 - guess it wouldn't hurt to just use 'python' if 'py' is not available for whatever reason.

**Comment by cinun** [comment]
I had the same problem, I ran the "py -3 -m pip install virtualenv" line and it worked. Have you added your python pip script to your PATH in Environment Variables? Here's a tutorial : 
 https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages

Hope this helps!

**Comment by Karthick-Balaji** [comment]
> I had the same problem, I ran the "py -3 -m pip install virtualenv" line and it worked. Have you added your python pip script to your PATH in Environment Variables? Here's a tutorial :
> https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages
> 
> Hope this helps!

hi..  for the command "py -3 -m pip install virtualenv", I get "py is not recognized as internal or external command". but python gets launched when I type "python". Could anybody figure out what is going wrong?

**Comment by pnhofmann** [comment]
Merged #665 - please try again with newest version (``git pull``). New Installer should just use 'python' if 'py' is not found (for whatever reason).

Please re-open should error persists or installer is still not working for you.
