### ISSUE TITLE
 Enable command shown in help not working

### ISSUE THREAD

**Issue by chekoduadarsh** [sukeesh/Jarvis#666]
![](https://i.ibb.co/bmrggKb/Screenshot-from-2020-03-02-22-03-15.png)

In help command `enable` is not found I think it is `enable sound` but only first word is seen

**Comment by pnhofmann** [comment]
That's actually the expected behavior.

help: Print major commands, ``help enable`` prints ``sound`` as sub-command.
And as shown in your screenshot, when typing ``enable`` Jarvis already suggests: ``Did you mean: enable sound``.

**Comment by pnhofmann** [comment]
Still, discussions how to improve help command could be useful.
Related: #617

**Comment by chekoduadarsh** [comment]
ohhk then I am closing this issue!!
