### ISSUE TITLE
Evaluate doesn't work properly

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#67]

**Comment by regantinaveen** [comment]
Could you provide a case in which it is not working. That would be helpful for debugging.

**Comment by StefanosChaliasos** [comment]
Excuse me for the delay. The issue is that evaluate doesn't work after the addition of cmdinterpreter. 
<img width="282" alt="screen shot 2017-04-15 at 21 02 48" src="https://cloud.githubusercontent.com/assets/15054312/25065846/583e964e-221f-11e7-991d-983779655748.png">
Can you fix this bug? Do you need extra informations? @regantinaveen

**Comment by StefanosChaliasos** [comment]
#68
