### ISSUE TITLE
Adding support for anaconda installation

### ISSUE THREAD

**Issue by krish1237** [sukeesh/Jarvis#672]
I noticed that python virtual-env is being used in installation. It provides no support to remove the environment while anaconda provides gui option "navigator" to do so.

**Comment by pnhofmann** [comment]
> It provides no support to remove the environment while anaconda provides gui option "navigator" to do so.

I honestly don't think you need a gui just to delete a folder... Removing the environment isn't more than deleting the env-folder. Respectively deleting whole Jarvis-Folder, if you want to uninstall Jarvis ;).

> Adding support for anaconda installation

Don't see any reasons why one should run Jarvis with anaconda - but then again guess there are no reasons against.

Unfortunately, AFAIK conda has its own virtualenv-replacement and does not work with "vanilla"-virtualenv.
https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/

Maybe a option

```python installer --conda=PATH_ANACONDA```

Should be possible to implement with a view lines.

**Comment by krish1237** [comment]
Oh okay that works too i had a problem because both python2 and 3 are installed in my ubuntu.Naturally the code was using python2 i had to use "python3 installer". I thought anaconda could solve this, but reading about virtualenv, it was just the way you initialize the scripts. I'm gonna close this issue now.
