### ISSUE TITLE
An error in ubuntu. I think you have to install distutils seperately using "sudo apt install python3-distutils"

### ISSUE THREAD

**Issue by krish1237** [sukeesh/Jarvis#673]
Python 3.8.2

An unexpected error occurred. Please open an issue on github!
here is the error:

Traceback (most recent call last):
  File "installer/__main__.py", line 3, in <module>
    from helper import log_init, log_close
  File "installer/helper.py", line 3, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'

**Comment by gkodosis** [comment]
Yeeep, encountered this error as well. Followed the above mentioned commands and worked fine;

sudo apt install python3-distutils
sudo apt install  virtualenv
