### ISSUE TITLE
New Feature: plugin to create new_plugin.py with template

### ISSUE THREAD

**Issue by KonstantinosLolos** [sukeesh/Jarvis#674]
Hello! I have been toying around with Jarvis on my computer and I would really like to contribute.
I was messing around with some ideas and I thought about adding a plugin that creates a new_plugin.py file with the Hello World  plugin sample you provide and some extra documentation about the different options a developer has.
You guys have created really helpful info on how to contribute and create new plugins and since this is a plugin based System I thought it would be nice to apply the info you provide to a template! Any thoughts?

**Comment by pnhofmann** [comment]
Sounds good to me!

**Comment by KonstantinosLolos** [comment]
Hello again! I would like your opinion on a matter. I have been able to test my code in both MAC os and LINUX. The only difference between them and the reason i use the require tag is that in linux i have not been able to open the plugin after it has been created (the open command uses terminal based editors and not the default editor of the user which is not practical).

The question is: Should I remove the 'open' feature so the plugin is not that big or are you okay with the current situation?
Thanks!

**Comment by KonstantinosLolos** [comment]
Looks like thats what it does! Thanks for the tip! I added that in and made some more practical changes. I shall proceed with a pull request for review.

**Comment by KonstantinosLolos** [comment]
Not adding anything else for the time being. Should we consider issue closed for now? :)

**Comment by pnhofmann** [comment]
Yeah, forgot closing this one.

Hint: Nice github-feature, if you add issue-id '#674' to one of your commit-message github auto-closes related issues while merging.
