### ISSUE TITLE
Make bulkresizer plugin more user friendly.

### ISSUE THREAD

**Issue by gianniskokkosis** [sukeesh/Jarvis#676]
Hello! I 've been looking through some code and I noticed that the bulkresizer plugin has room for improvements. More specifically:

- Jarvis' speech uses plain white letters (and they appear in the wrong order upon start)

- If the user gives an invalid path jarvis throws an unhandled exception and the user dosen't get the chance to give another path. 

- Could add more specific and detailed documentation

I would like to work on theese issues because I really like this project and I would love to contribute if it's ok with you. Let me know. Cheers!

**Comment by pnhofmann** [comment]
Sure!

**Comment by jay24rajput** [comment]
Hey is this issue up for grabs?

**Comment by gianniskokkosis** [comment]
@jay24rajput Hello. I have finished the changes I wanted to make in bulkresizer plugin. In a couple of days I will make a PR. It's ok if you want to make some changes too!

**Comment by jay24rajput** [comment]
Hey @gianniskokkosis sorry for barging in! Please go ahead with your PR. Cheers!

> @jay24rajput Hello. I have finished the changes I wanted to make in bulkresizer plugin. In a couple of days I will make a PR. It's ok if you want to make some changes too!

**Comment by pnhofmann** [comment]
#692
