### ISSUE TITLE
Create a new Alexa skill for Jarvis

### ISSUE THREAD

**Issue by annakotsa** [sukeesh/Jarvis#687]
Hello! With my colleague @Methenitis, we have been working on our contribution to Jarvis for some time now and we thought it would be a really nice idea if we also added a new feature to Jarvis, besides solving existing issues. More specifically, we are thinking of creating a new Alexa skill for Jarvis which:

•	Will enable Alexa to access some of the Jarvis’ functions and perform them
•	Will enable Jarvis to also work on an Amazon Alexa device, therefore increasing the number of its users
•	Will be based on the code that exists here: https://github.com/johnwheeler/flask-ask?fbclid=IwAR00GEPMoscCfStI4sTyNib0YLFW4RIXoJ6Osy6uIY0qaEVx8SXHKLxeJiE

We really like this project and we would love to contribute to it with this idea if you also agree with that. Thank you in advance!

**Comment by pnhofmann** [comment]
Yeah- sure!

Not that I'm using Alexa, but maybe we could even learn a bit from Alexa ;). Especially what is called in flask-ask ``Allows for the separation of code and speech through Jinja templates`` ;).

**Comment by shreyubee** [comment]
I would like to work on this

**Comment by pnhofmann** [comment]
Obviously wouldn't stop you if you say you just really want Jarvis as an Alexa skill (in this case re-open this issue); but closing this one because has no priority.
