### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by klabacher** [sukeesh/Jarvis#690]
Can I use jarvis as an module?

**Comment by pnhofmann** [comment]
You mean like as a library for other projects? This isn't intended, but I see no reason why this shouldn't be possible with maybe a view smaller adjustments.

What exactly are you trying to do?

**Comment by klabacher** [comment]
I'm trying to do a real jarvis with voice recognition and your project fits exactly for what I need. If you want, you can be in the project

**Comment by pnhofmann** [comment]
> I'm trying to do a real jarvis with voice recognition

Sure! Or you could also try improve this project with a better voice recognition feature ;). Or of course use this project to create your own project. And maybe we'll even merge some code back - possibilities are endless ;).

The whole magic lies in PluginManager. Basically:

```
>>> from PluginManager import PluginManager
>>> plug = PluginManager()
>>> plug.add_directory('plugins')
>>> plug.get_plugins()
```

And you have a list of plugins = commands for whatever you want to do. All with methods 'get_name()-> str', 'require()-> List[Requirements]', 'alias-> List[str]'.

And of course 'run(jarvis: CmdInterpreter.JarvisAPI, s: str)'. You would need to adapt / reimplement all methods of JarvisAPI to your needs.

**Comment by klabacher** [comment]
Can I talk with you by discord?

**Comment by pnhofmann** [comment]
Sorry, I generally don't do private chats.
