### ISSUE TITLE
portaudio is not detected

### ISSUE THREAD

**Issue by Darin755** [sukeesh/Jarvis#695]
The installer says that the voice recorder is not installed even though it is

**Comment by pnhofmann** [comment]
Hi!
It's not just basic portaudio. We need to install the python-binding of portaudio. And this requires native extension - and therefore you need:

* portaudio devel package
* gcc
* python devel package.

The command called is:
```
source env/bin/activate
pip install pyaudio --global-option='build_ext' --global-option='-I/usr/local/include' --global-option='-L/usr/local/lib'
```

And this probably fails.

I am aware, this is far from perfect and I hope to find a better solution in the future. For now, the whole speech-recognition part is still in an early stage.

**Comment by Darin755** [comment]
Thank you

**Comment by Darin755** [comment]
I got pyaudio to work on ubuntu by running 

sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0

then

sudo pip3 install pyaudio
