### ISSUE TITLE
Adding a Visual Response Character

### ISSUE THREAD

**Issue by mookieepps** [sukeesh/Jarvis#699]
Hello!  I'm wanted to  contribute to Jarvis and had nice idea if we also added a new feature to Jarvis, besides solving existing issues. More specifically, we are thinking of creating a new visual character that can be enabled to pop up and read the command responses?

**Comment by pnhofmann** [comment]
You mean something like [Clippit](https://upload.wikimedia.org/wikipedia/en/d/db/Clippy-letter.PNG)?
That'd be funny! Like this idea.

**Comment by pnhofmann** [comment]
Close in favor of #485
