### ISSUE TITLE
Non-interactive mode for Jarvis

### ISSUE THREAD

**Issue by arjunk2004** [sukeesh/Jarvis#703]
Hi, I'm fairly new to this project. I was wondering if there was a non-interactive mode for jarvis. Something like where you could just go `jarvis "[command]"` and get the normal output.

**Comment by arjunk2004** [comment]
I’d like to try to fix this if you don’t mind @pnhofmann

**Comment by pnhofmann** [comment]
Sure!

**Comment by arjunk2004** [comment]
Okay, I created a pull request (PR #711). The only catch is: for existing versions of jarvis, you need to delete the main jarvis file. Then, you should rerun the setup.sh script and make sure to do these steps in the processes (in the "Write Jarvis starter" part of the script):
  1) Install jarvis /usr/local/bin starter (requires root)
  2) Add /home/qbp/projects/Jarvis to $PATH (.bashrc)

I'm going ahead and closing the issue because I think it's all fixed, but please let me know if there are any problems!
