### ISSUE TITLE
Stopping stopwatch

### ISSUE THREAD

**Issue by arjunk2004** [sukeesh/Jarvis#705]
I might be missing something, but is there a way to stop the stopwatch mode?
I tried to stop it, command z on macOS paused it, but I couldn't go back to the normal JARVIS command line.

**Comment by pnhofmann** [comment]
```
~> What can I do for you?
help stopwatch
Start stopwatch

L       Lap
R       Reset
SPACE   Pause
**Q       Quit**
```

Or use ctrl-c

**Comment by arjunk2004** [comment]
Hi! Thanks for the help. I feel like we should display these at the bottom of the stopwatch. There seems to be plenty of space there if it’s not too complicated. Thoughts?
I could work on it if you like the idea @pnhofmann

**Comment by pnhofmann** [comment]
Hmm, our stopwatch is just termdown: https://github.com/trehn/termdown

**Comment by arjunk2004** [comment]
I've been fiddling around a bit, there doesn't seem to be a good way to do this without it looking horrible so perhaps we should just leave it as is.
