### ISSUE TITLE
Weather doesn't ask for state

### ISSUE THREAD

**Issue by ak2243** [sukeesh/Jarvis#713]
The weather forecast doesn't ask for the state, thus it could be the right city but the wrong state. I think we should either ask for state or zip code.
Thoughts?

EDIT: I phrased the issue badly initially so this should better clarify what I meant.
I'm in the U.S. so I'm not exactly sure how this works in other countries but it does seem to be a problem here, as there are a lot of cities with the same name in different states (for example, there are thirty one cities called Franklin in the U.S.) and Jarvis, currently, has no way of knowing which one the user is trying to get the weather for.

**Comment by pnhofmann** [comment]
Funny, seems to work for German zip codes. Quick look, API does support ZIP Code: https://openweathermap.org/current
But to be honest: I haven't touched this code yet ;).

Also just noticed, command parsing heuristic fails for ``update location``. Calls ``location`` instead :(.

**Comment by aprzn123** [comment]
It seems like in general it will use the last thing it can interpret as a command. That should probably be a separate issue, though.

**Comment by arjunk2004** [comment]
Perhaps we should just make it zip code and country and not city at all?

**Comment by KrishnaSai2020** [comment]
@arjunk2004 seems like a good idea but zip code is a bit risky ie giving personal info maybe type get the user to tell the city and choose from a list that Jarvis gives. eg if I say 'weather in franklin' it could say 'which state Ohio, etc...'

**Comment by arjunk2004** [comment]
Okay. That makes sense. Sorry about the late response I've been busy. I'll see if I can get it to provide a list...

**Comment by shreyubee** [comment]
I would like to work on this if it's still available

**Comment by pnhofmann** [comment]
Sure!

**Comment by shreyubee** [comment]
> Sure!

Could you please assign it to me?

**Comment by pnhofmann** [comment]
Closing since lots of changes for location on dev branch
