### ISSUE TITLE
Code is too clutterred

### ISSUE THREAD

**Issue by KrishnaSai2020** [sukeesh/Jarvis#716]
I've had a quick look at your code and it is just cluttered with comments. Some are ok as in the ones that say thing along the line of "insert new feature here" or 'in progress'.

But ones like 'this line does this' or 'this variable does that' are not really needed. Take this in a good way as far as I can tell your code explains itself it doesn't need all these comments it just confuses things. If you guys don't mind I'll create a pull request and get rid of the ones that are not needed.

**Comment by pnhofmann** [comment]
#717
