### ISSUE TITLE
Leetcode Integration

### ISSUE THREAD

**Issue by adarshtri** [sukeesh/Jarvis#718]
Leetcode has an endpoint https://leetcode.com/api/problems/algorithms/ to get basic information of the logged-in account like problems solved, easy count and plenty more trivial information as such. How about writing a plugin to integrate this command as well into Jarvis? I would like to create this plugin if the idea sounds good enough as a use case.

**Comment by pnhofmann** [comment]
> Leetcode has an endpoint

Can't really find any documentation or terms of usage. The latter, you definitely should check if Leetcode does allow building apps using this api.
Never heard of LeetCode and must say, this plugin would probably be quite product-specific. But our policy is: PRs are accepted!!
If you can build a useful plugin (and are allowed to), sure we will accept!

**Comment by adarshtri** [comment]
I think you have got a valid point. After doing some research I found that the API can't be used otherwise for any purpose. Closing the issue.
