### ISSUE TITLE
Add the ability to ask Jarvis the weather of a specific city

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#72]
For example you could ask: "weather in London" or "weather New York" and Jarvis will find the weather of the specific city for you.

**Comment by StefanosChaliasos** [comment]
@LuisFSilva  do you want to implement that feature?

**Comment by LuisFSilva** [comment]
Yeah, seems simple enough. I'll work on that tomorrow

**Comment by LuisFSilva** [comment]
And maybe also do the same with time?

**Comment by StefanosChaliasos** [comment]
Yes of course but please implement the two features in different pull request

**Comment by LuisFSilva** [comment]
Will do so. Expect it during the next few days

**Comment by StefanosChaliasos** [comment]
#77
