### ISSUE TITLE
New plugin

### ISSUE THREAD

**Issue by alexandr7035** [sukeesh/Jarvis#722]
Is it ok if I create a plugin which displays guitar chords' schemas? :)

**Comment by pnhofmann** [comment]
Sure!

**Comment by alexandr7035** [comment]
> Sure!

Great!

**Comment by alexandr7035** [comment]
@pnhofmann should I open data file in __init__() method of my plugin (so it will be opened only once, but on jarvis start) or on each plugin call?

**Comment by pnhofmann** [comment]
Both is fine, but I would prefer --> ``init()`` (without underscores !).

**Comment by pnhofmann** [comment]
closing as stale
