### ISSUE TITLE
Convert the weather to Fahrenheit if the location is in US

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#73]

**Comment by LuisFSilva** [comment]
I started working on this today and I got something the works with the normal function of weather (take a look in one of my [branches](https://github.com/LuisFSilva/Jarvis/tree/Enhancement/Weather)), but have no idea how to do this with the new function 'check time in'. Any suggestions?

**Comment by LuisFSilva** [comment]
Nevermind, got it. Check my PR

**Comment by StefanosChaliasos** [comment]
#81
