### ISSUE TITLE
Create tests for evaluate method

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#74]
Create unit tests for method calc of file [evaluator](https://github.com/sukeesh/Jarvis/blob/master/Jarvis/packages/evaluator.py)

**Comment by dudu84** [comment]
Hi! Can I take this one?

**Comment by StefanosChaliasos** [comment]
Unfortunately someone else work on that issue #84. You could expand the tests made in PR #84.
