### ISSUE TITLE
@plugin decorator appears to not be working

### ISSUE THREAD

**Issue by aprzn123** [sukeesh/Jarvis#744]
I'm working on the routines described in #613, but I'm finding a weird issue wherein some plugins failed to be registered. Below is an abridged version of my code in jarviscli/plugins/routine.py
```
from plugin import plugin

@plugin("create routine")
def new_routine(jarvis, s):
    #create routine

@plugin("call routine")
def call_routine(jarvis, s):
    # call routine

@plugin("list routines")
def list_routines(jarvis, s):
    # list routines

@plugin("delete routine")
def list_routines(jarvis, s):
    # delete routine
```

The issue I'm having is that the first two plugins are registering and running fine, but the third and fourth don't seem to be registered. They're not listed when you use `help`, and when you try to use them, Jarvis gives the standard "I could not identify your command" error.

**Comment by pnhofmann** [comment]
Hi!

> They're not listed when you use help

That is the interesting part of this issue.

Obviously your example code is missing some 'pass'. And fourth plugin shadows third plugin because both are called ``list_routines``. Unfortunately - beyond that, I can't reproduce any strange behavior.

**Comment by aprzn123** [comment]
Apparently due to some quirk in the plugin registering system, giving two functions the same name somehow causes neither to register. Not sure why that is, I'm not that familiar with the part of the program which does that.

**Comment by pnhofmann** [comment]
>  giving two functions the same name

Two functions definitely cannot exist with the same name in python.

You probably think  ``@plugin`` does register a new plugin. Unfortunately it isn't implemented this way: ``@plugin()``only **creates** plugin. And in a second step a small lib called [pluginmanger](https://github.com/benhoff/pluginmanager) searches everything for stuff that looks like a plugin.

Second definition of ``list_routines`` overwrites first ``list_routines`` - and therefore no way the first plugin can be found. It just does not exists any more.

However this still does not explain why second``list_routines`` (as plugin delete routine) is not found and registered.
