### ISSUE TITLE
Create tests for clock method 

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#75]

**Comment by Josiah-DuBose** [comment]
Hello, I'd like to help with this. can you provide more details?

**Comment by Josiah-DuBose** [comment]
For instance, is the clock method somewhere in packages?

**Comment by StefanosChaliasos** [comment]
Yeah my mistake. I mean the check time action (method do_check line 97 Cmdinterpeter.py). You could check if the s is equal to your location then is the time given from the call of timeIn.main(self, s) the same with ctime()?

**Comment by sladyn98** [comment]
I'm new to GitHub .can you tell me how can I be helpful with this issue

**Comment by StefanosChaliasos** [comment]
@sladyn98  The steps you need to follow to contribute to a GitHub project are [here](http://stackoverflow.com/questions/4384776/how-do-i-contribute-to-others-code-in-github). You could try to solve the issue #74 which is easier. You can find more information about unit testing on python in that [documentation](https://docs.python.org/2/library/unittest.html) .

**Comment by trp07** [comment]
Hello,
I believe I completed the required test and am about to initiate a PR.  

Please let me know if I did it incorrectly.  This would be my first PR.  I'm new to coding and am trying to get involved!  

Thanks for posting the request!
-Tim

**Comment by salman-bhai** [comment]
Hey, Is this Issue still up for grabs or is it resolved?

**Comment by trp07** [comment]
I submitted pull request #88 in response to this.

**Comment by salman-bhai** [comment]
Oh okay so it hasn't been merged! Thanks :smile:
