### ISSUE TITLE
Language Translation Feature

### ISSUE THREAD

**Issue by farseenmanekhan1232** [sukeesh/Jarvis#755]
Translate a given sentence into a specified Language
This can be done using Google Translate API

**Comment by pnhofmann** [comment]
This feature already exists:
https://github.com/sukeesh/Jarvis/blob/master/jarviscli/plugins/translate.py

**Comment by Ed1123** [comment]
If the feature already exist I think you may want to close the issue, @farseenmanekhan1232 .

**Comment by pnhofmann** [comment]
Yeah, let's close this one ;)
