### ISSUE TITLE
Updating the todo plugin

### ISSUE THREAD

**Issue by aprzn123** [sukeesh/Jarvis#758]
I was considering adding some additional functionality to the todo plugins in `reminder.py`. Before I start working on that, can someone explain to me what the progress subcommand does? Is it just a string associated with the todo item, or is there additional functionality to it?

**Comment by pnhofmann** [comment]
Hi!

> Is it just a string associated with the todo item, or is there additional functionality to it?

Yes, currently progress it's just a string which can be set to really everything. But if you like, I wouldn't mind if you change this behavior to for example percentage value 0..100.

**Comment by aprzn123** [comment]
I might update it to that; I might also add functionality to filter by incomplete tasks.

**Comment by pnhofmann** [comment]
#803
