### ISSUE TITLE
Starting and ending output using non-interactive mode

### ISSUE THREAD

**Issue by lit3ral** [sukeesh/Jarvis#759]
When you launch Jarvis in interactive mode, it has some output at the beginning and some more when you exit jarvis. When you use jarvis in non-interactive mode like `jarvis [command]`, this output at the beginning and end is still there. I think we should just keep the command output and not the jarvis start and end output. Thoughts?

**Comment by pnhofmann** [comment]
Agree!

Probably we could just create CmdInterpreter with ``first_reaction=False`` to get rid of output at the beginning
``https://github.com/sukeesh/Jarvis/blob/master/jarviscli/CmdInterpreter.py#L315``

For output at end, we could add a ``no_output`` option to ``exit()``.
``https://github.com/sukeesh/Jarvis/blob/master/jarviscli/CmdInterpreter.py#L430``

**Comment by lit3ral** [comment]
Great, I'll do that as soon as I can. Sorry for the late response. I'm still in school so I've been a bit busy since it's opened

**Comment by shreyubee** [comment]
I would like to work on this.

**Comment by pnhofmann** [comment]
Sure!

**Comment by shreyubee** [comment]
> Sure!

Could you please assign it to me?

**Comment by pnhofmann** [comment]
Of course ;).

**Comment by pnhofmann** [comment]
#802
