### ISSUE TITLE
Installation Failed in Ubuntu 20.04

### ISSUE THREAD

**Issue by harikarthickt** [sukeesh/Jarvis#760]
root@hk-VirtualBox:~/python/Jarvis# ls
custom  Dockerfile  installer  LICENSE   README.md  setup.sh
doc     icons       jarviscli  Makefile  setup.bat  test.sh

root@hk-VirtualBox:~/python/Jarvis# source setup.sh

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3

Python 3.8.2
Logging to /tmp/tmp1yuwjvzl

============== Preparing virtualenv ==============

============== Install requirements ==============

Installation failed with unexpected error - This should not have happened.
Please check logs at "/tmp/tmp1yuwjvzl". If you open a bug report, please include this file.

[tmp1yuwjvzl.log](https://github.com/sukeesh/Jarvis/files/5249196/tmp1yuwjvzl.log)

**Comment by lit3ral** [comment]
Hi! If you're on ubuntu you should run `python3 installer` once inside the Jarvis directory instead of running `source setup.sh`
If it can't find `python3`, you can fix that easily by running `sudo apt install python3`. Let me know if that works!

**Comment by pnhofmann** [comment]
Hi! Thanks for reporting this issue!

Problem is actually not with ``python`` <-> ``python3``. The ``Python 3.8.2`` is correctly found and used. Although silencing the ``python`` cmd not found (and therefore not used) message would be a good idea to avoid confusion ;).

Problem is, newer versions our requirement archey4 (used for sysinfo plugin) got a new requirement (netifaces) which requires native extension and therefore python dev package to compile some stuff, which is not installed on your system.

Our policy is, that Jarvis should be able to run with pure Python. Therefore I froze archey4 to an older version without netifaces requirements. At last till we find a better solution ;).

https://github.com/sukeesh/Jarvis/commit/9b142879af6ee175694b3b98619c44f14a72ea06
