### ISSUE TITLE
Handling spam PRs

### ISSUE THREAD

**Issue by sukeesh** [sukeesh/Jarvis#768]
@appi147 @pnhofmann @StefanosChaliasos @yashLadha 

Hi all,

Due to the Hacktober fest, We might get a lot of spam PRs to update README's. I will be closing them manually one-by-one throughout the month.

Some background: https://blog.domenic.me/hacktoberfest/

**Comment by sohail532** [comment]
just try changing the structure a little bit and u will get it and try to use sigmoids other than perceptrons
