### ISSUE TITLE
MAC Address Changer

### ISSUE THREAD

**Issue by mikek4233** [sukeesh/Jarvis#781]
A useful tool is a MAC address changer I would love to work on this. What do you think?

If I am working on Linux how do I test my code for windows and macos?

**Comment by pnhofmann** [comment]
> A useful tool is a MAC address changer I would love to work on this.

Sure!

> If I am working on Linux how do I test my code for windows and macos?

It would be ok for a plugin to only work on one platform. Just mark add a ``@require(platform=LINUX)``.

https://github.com/sukeesh/Jarvis/blob/master/doc/PLUGINS.md#require

**Comment by mikek4233** [comment]
Ok so I have finished the linux one - if I figure out how to test on other platforms (I am having trouble setting up jarvis for  windows) then I'll add to this plugin at a later date

**Comment by pnhofmann** [comment]
#788
