### ISSUE TITLE
Roadmap and development coordination

### ISSUE THREAD

**Issue by 5n8ke** [sukeesh/Jarvis#79]
Due to studying I only have a limited amount of time for hobby projects such as this one.

So I want to spend my time as productive as possible. Right now I mostly did what I felt like regarding reminders and the to do list. But my latest feature (lexical similarity) could easily be used by more parts.

But I feel like we are missing a place to coordinate our efforts and discuss new features and the priorities of them. But these issues are definitely not the right place for this.

How are you feeling about this?

**Comment by StefanosChaliasos** [comment]
We could create an email list or a google group @sukeesh . We could used that list to have a better communication the core contributors of this project but we should use the github as the main tool to discuss and keep track of bugs, new features, enhancements and other technical issues. You could open an issue about any

**Comment by sukeesh** [comment]
@StefanosChaliasos google group will be good.

**Comment by 5n8ke** [comment]
Since it would be mostly brainstorming, I think opening an issue for every small idea would be to much spam.
In addition it would be harder to get a quick overview over every proposal and the priorities of other people. I am not sure how the permissions for this are managed, but I really like the projects feature in Github itself. 
If it's to much of a hassle, a google group or something similar would be fine by me.

**Comment by StefanosChaliasos** [comment]
You can join the google group from that link https://groups.google.com/forum/#!forum/jarvis_pa. Please feel free to create a topic with your ideas.
