### ISSUE TITLE
Ineligible for Hacktober fest

### ISSUE THREAD

**Issue by shaw8wit** [sukeesh/Jarvis#792]
Maintainers,
Please add the topic 'hacktoberfest' to make the repository eligible for Hacktoberfest 2020.
![image](https://user-images.githubusercontent.com/52004561/95009020-4af05180-063c-11eb-8fbc-d4b9c22ff776.png)
Kindly check the 4th point.

**Comment by appi147** [comment]
@shaw8wit Do you mean in About section of this repo? Because we have a label named hacktoberfest

**Comment by shaw8wit** [comment]
@appi147 Yes In the about section of the repo.

**Comment by appi147** [comment]
@sukeesh We don't have rights to add the topics. Please add the topic, so that community benefits from it.
