### ISSUE TITLE
WIFI Password Getter

### ISSUE THREAD

**Issue by mikek4233** [sukeesh/Jarvis#793]
This plugin will find and display all the profiles of the wifis that you have connected to and then display the password if selected 

Happy to work on this

**Comment by pnhofmann** [comment]
Sure!

**Comment by mikek4233** [comment]
@pnhofmann - regarding the name I wanted to just do "wifi" but if later I want to do other wifi related features such as wifi reboot? So maybe I should do "wifi passwords" that way I can do other commands like reboot your wifi in later features 

What do you think?

**Comment by pnhofmann** [comment]
whatever you prefer - just calling it "wifi" sounds fine to me and this won't stop you from adding features like "wifi passwords"

**Comment by mikek4233** [comment]
Ok @pnhofmann done
