### ISSUE TITLE
create and upload python package (pip)

### ISSUE THREAD

**Issue by sukeesh** [sukeesh/Jarvis#8]
Create a python pip package

**Comment by akshaysharma096** [comment]
More context here

**Comment by appi147** [comment]
@StefanosChaliasos  I want to help

**Comment by sukeesh** [comment]
@appi147 Go Ahead!

**Comment by appi147** [comment]
Hi @sukeesh jarvis name is not available on [PyPi](https://pypi.python.org/pypi?%3Aaction=search&term=jarvis&submit=search) . Also, make a release with version number

**Comment by StefanosChaliasos** [comment]
https://pypi.python.org/pypi/jarviscli/1.0

**Comment by appi147** [comment]
![screenshot from 2017-07-02 12-56-37](https://user-images.githubusercontent.com/22685364/27768041-ed4e6b6c-5f26-11e7-9e4f-f87724e16a47.png)

@sukeesh @StefanosChaliasos full package is not uploaded on pypi

**Comment by appi147** [comment]
@sukeesh @StefanosChaliasos Please merge  #137 and  reupload on pip with different version number

**Comment by sukeesh** [comment]
https://pypi.python.org/pypi/jarviscli/1.0.1
