### ISSUE TITLE
Library/Repository for Jarvis Plugins

### ISSUE THREAD

**Issue by Martins6** [sukeesh/Jarvis#801]
I've built a Jarvis plugin to administer my R scripts, but I also know not everybody will be interested in this specific plugin. So, I was thinking:

1. How about we construct a repository or library for Jarvis plugins? Some server or someone's repository in Github where it would contain a bunch of plugins ready to be installed as needeed.

2. We should also build alongside an "install plugin" plugin, where it could install from this server/library/repository of codes! 

As it is fairly simple the "install plugin" plugin (simply extract file and copy it to jarviscli/plugins), I'd volunteer to build this script, however...for that we need the repository first. And that seems something to be discussed with the community.

**Comment by Martins6** [comment]
Those jarvis plugins in the repository could be in a specific file type like: "example.jarvis_plugin". Many ways to do the same job!

**Comment by pnhofmann** [comment]
Like a marketplace ;). Like this idea.

I'd also have no problem with plugins in this repo, which are disabled by default. But I agree, for highly specific plugins a own repository would be better.

My two cents:

> simply extract file and copy it to jarviscli/plugins

I'd simply ``git submodule``  the repositories to a ``jarviscli/additional`` folder (included in plugin search path).

**Comment by Martins6** [comment]
I've got to be frank, didn't know what git submodule was. Then I searched for it and found it amazing! Nice git functionality. 

Anyways...like you said @pnhofmann, for the more accepted plugins the ` git submodule ` would work just fine. However...I'd argue that as Jarvis grows the 'marketplace' will become more and more necessary. So...why not start with that? It will solve for the more accepted plugins but It will likewise solve for the more specific ones too!

The difficult part, I'd wager, would be creating the infrastructure and the community rules.

**Comment by pnhofmann** [comment]
>  git submodule would work just fine.

OK, need to rollback from this spontaneous idea ;). Didn't think this through: Git submodule means, this repo is added to git history and we certainly don't want to commit what plugins we installed.
What we'd need would be rather a regular ``git clone`` (like e.g. my vim plugin manager does it) - and obviously exclude ``jarviscli/additional`` from Jarvis git history.

> We could also elaborate a way to 'download' a bunch of plugins, like they are tagged together, at the same time. So there could be a canonical 'extra' plugins, the more accepted ones, that would be just a one line of code away. That way everyone is happy!

+1

> The difficult part, I'd wager, would be creating the infrastructure and the community rules.

Another suggestion - which isn't really from me, but I have seen similar solutions:

In Readme say, just tag your repository with 'jarvis-plugins'. And then we could link the github Topics page:
https://github.com/topics/zsh-plugins
And maybe maintain a link list to common extensions.

**Comment by Martins6** [comment]
Sold! For me, at least. :laughing: 

I shall begin some experiments with that. It can be a sort of foundation or benchmark for future upgrades.

About the tag, still... My idea would be for the user who wants to offer his code in the plugin marketplace (I hope this nomeclature sticks) as a bunch, or tagged combo, put all the code in the same folder. Example: 'spicy.py', 'sweets.py', etc, in the same folder of 'recipes'.

About the requirements with each plugin... I think a simple comment in the top of the code can solve that. Taking the packages names, and inscribing into the 'installer\requirements.txt'.

**Comment by Martins6** [comment]
Hi again, @pnhofmann ! Glad to see the project growing since last time!!
So... in #874 , I made an PR to add some enhancements, and one of them I think it is up to discussion: giving the option to leave in the marketplace folder only .py files.

I think that would be a nice addition because one may not want to have a bunch of LICENSE, or README.md in the marketplace.

**Comment by Martins6** [comment]
Quick update in light of my last comment: I removed all of the removing options of alternatives files! The branch with the updates is ready, in my opinion!

**Comment by pnhofmann** [comment]
Closing since this is merged in dev
