### ISSUE TITLE
No basic commands accepted

### ISSUE THREAD

**Issue by Alenjojo** [sukeesh/Jarvis#814]
Most of the basic common commands are not defined in the program

**Comment by pnhofmann** [comment]
Hi!
Can you give an example what you mean with "basic common commands"?

**Comment by appi147** [comment]
Maybe he is referring to [https://github.com/Alenjojo/Friday](https://github.com/Alenjojo/Friday) 😉

**Comment by Alenjojo** [comment]
> 
> 
> Hi!
> Can you give an example what you mean with "basic common commands"?

like when i tested it out, i used the common sentences that we use daily so in that sense

**Comment by pnhofmann** [comment]
Related to #424

[dev](https://github.com/sukeesh/Jarvis/tree/dev)-branch contains some improvements.

If you like, just really write done some example of common sentence you would like to use with Jarvis. Would be useful for testing ;).
