### ISSUE TITLE
fix error on matrix_add

### ISSUE THREAD

**Issue by ropoko** [sukeesh/Jarvis#815]
after inputting the dimensions of the matrix if you input something different from a number this error appears: 

![issue](https://user-images.githubusercontent.com/49417432/104778390-09ebfb00-575c-11eb-8c2b-d1ffd0d07f02.png)

**Comment by pnhofmann** [comment]
Thanks for reporting this issue ;).

**Comment by Akshit1510** [comment]
i would like to work on it

**Comment by pnhofmann** [comment]
Thanks @Akshit1510  
#817
