### ISSUE TITLE
No module named 'reminder'

### ISSUE THREAD

**Issue by FelippeRoza** [sukeesh/Jarvis#82]
I'm trying to run Jarvis on python3, but the following error appears:

```
File "Jarvis/packages/todo.py", line 5, in <module>
    from reminder import addReminder, removeReminder
ModuleNotFoundError: No module named 'reminder'
```
The file reminder.py is under packages/ folder.
Do I have to change something?

**Comment by StefanosChaliasos** [comment]
Currently we don't support Python 3. You could open an issue about run Jarvis with Python 3. It will be great if you could try to make the appropriate changes to support Python 3

**Comment by FelippeRoza** [comment]
Then I will close this issue and open a new one.
Best.
