### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by FelippeRoza** [sukeesh/Jarvis#83]
It would be great if Jarvis could run on Python 3.
I'll try to make the changes to reach this, but any help would be welcome.

**Comment by 5n8ke** [comment]
I just looked into the python 3 issue and there are mainly 2 problems:
 - pyttsx
 - aiml
Both packages don't have support for python 3.x. They only work with python 2.
All the other errors with imports could be fixed. In python 3 implicit relative imports are no longer supported.

**Comment by FelippeRoza** [comment]
Totally agree. The relative imports errors are somehow a simple problem to solve.

https://github.com/jpercent/pyttsx is a fork that ports pyttsx to Python 3. Maybe something like `pip install git+https://github.com/jpercent/pyttsx.git` could fix it.

**Comment by Prakash2403** [comment]
Changing to pyttsx3 or gTTS will help. See #113

**Comment by umangahuja1** [comment]
I think the issue is not resolved yet and it is not yet running on python3.
