### ISSUE TITLE
Uninstalling Jarvis from MacOS BigSur

### ISSUE THREAD

**Issue by LiranCaduri** [sukeesh/Jarvis#836]
Hi everybody!

I want to uninstall Jarvis completely, with no left overs file and code.
I already read the closed issues about uninstalling and for some reason it didn't help, couldn't seem to remove Jarvis.
Can anybody help me please?

I ran the `setup.sh` script.

Thanks in advance!

**Comment by pnhofmann** [comment]
> I already read the closed issues about uninstalling

That be #332? Yes, that is outdated. Jarvis now doesn't install files globally.

Only exception: The launcher.
* If you choose to "Install jarvis /usr/local/bin starter (requires root)", just delete ``/usr/local/bin/jarvis``.
* If you choose to add Jarvis to your path, remove the ``export PATH="$PATH:/home/.../Jarvis"`` line from your ``~/.bashrc``. 

Everything else happens in the Jarvis-Folder.

**Comment by LiranCaduri** [comment]
Awesome, Thank you 🙏
