### ISSUE TITLE
File Manager?

### ISSUE THREAD

**Issue by Tpool1** [sukeesh/Jarvis#839]
Hello, 

Could I implement a file manager plugin? You might be able to say "delete X file" or "move X file to a certain directory": things like that. I am new to contributing so if I am doing something wrong please bear with me! Is this something that already exists?

**Comment by pnhofmann** [comment]
Sure!

> Is this something that already exists?

Full File Manager? No. But you could take a look at 'file_organizer" - this plugin moves files based on extensions. Maybe some parts can be re-used?

https://github.com/sukeesh/Jarvis/blob/master/jarviscli/plugins/file_organise.py
