### ISSUE TITLE
Improve write agenda feature

### ISSUE THREAD

**Issue by IriannaPapoutsi** [sukeesh/Jarvis#843]
Hello everyone!
I'm Irianna and I would like to make some contributions in Jarvis.
To begin with, I have observed that the input data of wirte agenda feature are not being saved in different columns in the csv file.
So I would like to correct that and add some new information of the event such as date, time etc.
Would you like that?

**Comment by pnhofmann** [comment]
Hi! Sure, sounds good!

**Comment by pnhofmann** [comment]
Merged
