### ISSUE TITLE
Add Labels for Issues, and Pull Requests, and overall more orginizations such as Docs, and branches

### ISSUE THREAD

**Issue by DobbyK** [sukeesh/Jarvis#853]
This repository is, although, not the largest, is sometimes difficult to get around. If we had Labels the organization of the project would be much easier to get around. And to find important Issues such as security (if we ever get more plugins that connect to a chat server or something, which I may work on).

**Comment by DobbyK** [comment]
I mean we should use labels more often, if anyone was confused by this.

**Comment by pnhofmann** [comment]
> I mean we should use labels more ofte

Yes, we could ;)
