### ISSUE TITLE
Installation failed with unexpected error

### ISSUE THREAD

**Issue by tzzzening** [sukeesh/Jarvis#858]
Hello, I tried to install Jarvis but I met with this error. The error message instructed me to include the following file in the bug report. I have tried searching online for solutions, but none seemed relevant. I look forward to some help.

[tmpf2ksyanw.txt](https://github.com/sukeesh/Jarvis/files/6508894/tmpf2ksyanw.txt)

**Comment by pnhofmann** [comment]
Hmm, the installer script does not look enough ;(. That is another issue...

Can check what this command
``env\Scripts\pip.exe install -U -r installer/requirements.txt``
(call in Jarvis folder) returns?

**Comment by anrawool** [comment]
I am just looking through the project. But maybe do ‘cd installer’ first and then ‘pip3 install -U -r requirements.txt’.
