### ISSUE TITLE
[NEW FEATURE] Opening Applications

### ISSUE THREAD

**Issue by mrmuke** [sukeesh/Jarvis#861]
I would like to have the user just type open and type the first few letters of an application and click tab to autocomplete and open the application.

**Comment by pnhofmann** [comment]
Sounds really good!

**Comment by williamwu062** [comment]
I think I would like to attempt to tackle this. Is mrmuke working on this, or was it just a suggestion of some sort?

**Comment by artginzburg** [comment]
```ps1
$ open -a S [Tab]
  Safari          Slack           Spark           Suohai                        
  Shazam          Sublime\ Text
$ open -a Sa [Tab]
$ open -a Safari
```

Magic :)

**Comment by pnhofmann** [comment]
Closing as stale
