### ISSUE TITLE
[NEW FEATURE] Book Suggest

### ISSUE THREAD

**Issue by mrmuke** [sukeesh/Jarvis#862]
I like to use selenium or bs4 to get top book suggestions based on what they've read or just something new.

**Comment by pnhofmann** [comment]
Probably bs4 better than selenium, because selenium is a bit tricky to ensure to really work on all systems ;).

Web Scrapping - always a bit tricky. Just make sure, the owner of the website has no problem with what you plan to do ;).

**Comment by 26tanishabanik** [comment]
I have the added the above said feature, https://github.com/sukeesh/Jarvis/pull/892

**Comment by mohitrbhardwaj** [comment]
I am new to open source. Would like to contribute here but don't know how to start. Can somebody help please?
