### ISSUE TITLE
[NEW FEATURES] News

### ISSUE THREAD

**Issue by mrmuke** [sukeesh/Jarvis#863]
Based on location, get top local news to the user.

**Comment by pnhofmann** [comment]
Hi!
what news source do you plan to use?

To link existing news plugin:
https://github.com/sukeesh/Jarvis/blob/master/jarviscli/plugins/news.py

Just spontaneous thought: Maybe some kind of simple RSS-based news plugin would be nice?

**Comment by xopherw** [comment]
hey, kinda first timer here...how do you guys normally start working on feature? and how to test?

**Comment by pnhofmann** [comment]
Closing as stale
