### ISSUE TITLE
[NEW FEATURE] go to wiki search

### ISSUE THREAD

**Issue by williamwu062** [sukeesh/Jarvis#875]
Hi, just thought of an idea where if someone were to type something like 'wiki Tom Cruise', it would do a wikipedia search of Tom Cruise and give the page for him.

**Comment by pnhofmann** [comment]
Hi!
https://github.com/sukeesh/Jarvis/blob/master/jarviscli/plugins/wiki.py
However improvements are welcome ;).

**Comment by williamwu062** [comment]
oh god haha. I'll try to think of some other plugin then.
