### ISSUE TITLE
Travis CI stop checking file

### ISSUE THREAD

**Issue by bnothomb** [sukeesh/Jarvis#877]
I started looking at Jarvis and I feel like Travis CI hasn't checked commits for several days. 
In the resume page, everything has failed from the 15th June: https://travis-ci.org/github/sukeesh/Jarvis/requests

On Travis's page, there is a message warning that tell to migrate:
"Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on."

If I understand it correctly, the solution is to migrate it to travis-ci.com

**Comment by KrishnaSai2020** [comment]
Yeah a possible replacement could be pep8speaks used in major repos such as Pandas see #883 .
