### ISSUE TITLE
[NEW FEATURE] IMDB Top 250 Movies by Genre

### ISSUE THREAD

**Issue by jronzo99** [sukeesh/Jarvis#882]
Hi,
I see that there are already movie modules that pull information from IMDB, however, I would like to implement a plugin that takes a movie genre and loads the IMDB "Top 250" list for that genre. Eventually, I would integrate it with the other movie plugins so that the user can choose a movie from the list and retrieve the information about it. Let me know if this has been done or is being worked on. 
Thanks

**Comment by pnhofmann** [comment]
Hi!
Sure, this feature would be quite nice!

**Comment by WWFelina** [comment]
This sounds interesting. IMDB already has pages for top movies in a particular genre and I was able to set up an experimental plugin to extract top movies from there just by scraping the webpage
`@plugin("topmovies")
def topmovies(jarvis, genre):
    url = "https://www.imdb.com/search/title/?genres="+genre+"&explore=title_type,genres&title_type=movie"
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")
    table = soup.find('div', attrs = {'class':'lister-list'}) 

    for row2 in table.findAll('h3', attrs = {'class':'lister-item-header'}):
        jarvis.say(row2.a.text)`
      
Is a solution like this useful? If yes, can I be assigned this? @pnhofmann
