### ISSUE TITLE
[NEW] Add pep8speaks to auto check all contributions

### ISSUE THREAD

**Issue by KrishnaSai2020** [sukeesh/Jarvis#883]
I am working to add an automatic pep8 checker for this repo to auto-check whether any contributions meet pep 8 guidelines.

Main features
The bot makes a single comment on the Pull Request and keeps updating it on new commits. No hustle on emails!
The bot comments only if Python files are involved. So, install the integration on all of your repositories. The bot would not comment where it should not.
By default, the bot does not comment if there are no PEP 8 issues. You can change this in configuration.
You can use choose between pycodestyle or flake8 as your linter. The bot can read configurations for both.
The bot can read your setup.cfg for [flake8] and [pycodestyle] sections. Check out the Configuration section below.

**Comment by pnhofmann** [comment]
Hi!

another tool I never heard of - and I really, really like it!

I think we should use this as a replacement for Travis (-> #877). Travis is great, but for our use-case the PEP8-errors were always a bit hard to find.

Question: You added two PRs: #884 and #885 which add pep8speaks.yml to different locations?
And after merge, pep8speaks just needs to enabled (https://github.com/apps/pep8-speaks) and it should work?

**Comment by KrishnaSai2020** [comment]
I only added it one place I think... Either way, it's meant to go into the root directory.

**Comment by KrishnaSai2020** [comment]
I have now fixed both PRs. pep8speaks.yml is only included in the PR specifically mentioning PEP8speaks.

**Comment by KrishnaSai2020** [comment]
@pnhofmann actually I've had a good look at Travis and think pep8speeaks could work in parallel. For now, if we get pep8speeaks integrated now as a temporary solution whilst #877 hopefully fixes the Travis build and then the 2 of them can work together.

**Comment by pnhofmann** [comment]
Duplicated #968
