### ISSUE TITLE
[Feature] telling Jarvis to Capture screen.

### ISSUE THREAD

**Issue by ShreyPatel4** [sukeesh/Jarvis#894]
let's add this productivity feature to the AI agent also further we can use it to log it when issues or errors occurrence?

share ideas if any.

what I thought it add a simple rule on receiving input for multiple possible commands like "ss", "take ss", "screenshot", "capture screen ", etc it should perform a certain task for continued actions.

I have achieved the screenshot part. just don't know how to merge with existing files

```
/home/nan/Desktop/Open_source/Jarvis/env/lib/python3.8/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
**No module named 'pyautogui'**
Jarvis' sound is by default disabled.
In order to let Jarvis talk out loud type: enable sound
Type 'help' for a list of available actions.
180 plugins loaded 12 plugins disabled. More information: status

~> Hi, what can I do for you?
screenshot
I could not identify your command...
~> What can I do for you?
```

**Comment by pnhofmann** [comment]
Yeah, create PR and let us see. So, both @ShreyPatel4 and @26tanishabanik.

> I have achieved the screenshot part. just don't know how to merge with existing files

Looks like issue with virtualenv. ``**No module named 'pyautogui'**`` Jarvis can't find your module.

In jarvis home dir call ``source env/bin/activate``. Now you are in the Python-Environment Jarvis uses. Then you can install the package (again!) with pip like you are probably used to it (pip install pyautogui).

And put pyautogui in installer/requirements.txt ;).

**Comment by ShreyPatel4** [comment]
@pnhofmann I have created PR and Guide me from there

**Comment by 26tanishabanik** [comment]
I have added a new feature in the dev branch. This is my Pull request https://github.com/sukeesh/Jarvis/pull/900

**Comment by ShreyPatel4** [comment]
@26tanishabanik  that is great.
can you guide me where you added the token as trigger words for that plugin

**Comment by 26tanishabanik** [comment]
> @26tanishabanik that is great.
> can you guide me where you added the token as trigger words for that plugin

Yah sure, did you add the tag @plugin at the very beginning of the code after import to add the new plugin

**Comment by ritikranjan12** [comment]
@ShreyPatel4 
I have made a plugin to capture the screen can i make a Pull Request?

**Comment by ritikranjan12** [comment]
@ShreyPatel4 I had added the screen recording functionality with a Pull Request #918, Please review it.

**Comment by ShreyPatel4** [comment]
sorry guys I am not working on this issue now you can contact @26tanishabanik and @ritikranjan12 these guys had made good efforts and take follow up from these devs.
