### ISSUE TITLE
Bug while running --with-voice argument

### ISSUE THREAD

**Issue by AhmetFurkann** [sukeesh/Jarvis#895]
There is a bug when try to run `python __main__.py --with-voice` in the `dev` branch.

The error message is like below.

![backend_error](https://user-images.githubusercontent.com/35719856/130863621-afa7f037-42d9-4b14-8c23-a94f36bbd8a7.png)

As I understood the error is related the `Jarvis.say` method.

**Comment by pnhofmann** [comment]
Yeah, dev branch ;).
