### ISSUE TITLE
Jarvis don't run

### ISSUE THREAD

**Issue by Suprimo** [sukeesh/Jarvis#90]
when i type python Jarvis.py there's nothing happen :/

**Comment by anaisabel7** [comment]
It works for me typing `python Jarvis` (notice, without `.py` at the end). Can you check you are in the correct directory and have installed all dependecies.
Do you not get any response? Any error of any kind? Any message in the terminal?

**Comment by StefanosChaliasos** [comment]
I close that issue. If you still can't run Jarvis please create a new one with more informations.
