### ISSUE TITLE
Bug with Windows installer

### ISSUE THREAD

**Issue by GamingMineblox** [sukeesh/Jarvis#902]
So I've tried to install Jarvis with the setup.bat for Windows, but each time it gets to install requirements it opens reg.py in VS Code without doing anything else. I don't know what is causing this, and I don't know how to fix it.

```
Python 3.9.7
Logging to C:\Users\name\AppData\Local\Temp\tmplebmjzq5

============== Preparing virtualenv ==============

============== Install requirements ==============
/
\[main 2021-09-01T09:01:03.946Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
|[main 2021-09-01T09:01:04.054Z] update#setState idle
/[main 2021-09-01T09:01:34.055Z] update#setState checking for updates
[main 2021-09-01T09:01:34.091Z] update#setState idle
\[16308:0901/110304.010:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
\
```
![image](https://user-images.githubusercontent.com/42892277/131644421-99327669-97e3-4313-ad8c-dbada43ff663.png)

**Comment by pnhofmann** [comment]
Okay?

Can you give the version of VSCode so I can try to reproduce. Actually during 'Install requirements' everything that happens is a cmd-call

``env\\Scripts\\pip.exe install -U -r installer/requirements.txt``

Can you try (in Jarvis home directory) to execute this command and check if VS Code still opens?

If you close VSCode (not the cmd.exe window), does anything happen on the terminal?

**Comment by GamingMineblox** [comment]
VSCode is running on version 1.59.1

When I run that command I get an error trying to install ``python-nmap`` and then it opens VSCode.

![image](https://user-images.githubusercontent.com/42892277/131686679-8ec4616c-04c8-4ea2-b222-111a03160446.png)

And when I close VSCode it just reopens and outputs the same 2 lines on the terminal:
``[main 2021-09-01T14:08:50.807Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-09-01T14:08:50.915Z] update#setState idle``

If I wait it also outputs a different line:
``[17380:0901/161050.874:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled``

**Comment by GamingMineblox** [comment]
I fixed the VSCode opening issue, it was because *.py files are suppose to open in VSCode on my pc. I changed it to python and it ran without opening it. It did give errors from installing the requirements but that's a different problem

**Comment by pnhofmann** [comment]
Thanks for the info!
