### ISSUE TITLE
[Feature] Make Jarvis to read Wikipedia Articles

### ISSUE THREAD

**Issue by SmallLion** [sukeesh/Jarvis#904]
Hey! Here's a new feature, let's make Jarvis read Wikipedia articles!

My idea is, the user gives a command something like "What is programming" and Jarvis reads the related Wikipedia article.

I know the way to do it so please help me to create a pull request for you 🙏🏻

share ideas if any! (I need to do hacktoberfest task haha)

CC: @sukeesh

**Comment by JaskiratSudan** [comment]
hey can you assign this feature to me

**Comment by pnhofmann** [comment]
Hi!
please take a look at: https://github.com/sukeesh/Jarvis/blob/master/jarviscli/plugins/wiki.py
But you can improve this plugin for sure!

**Comment by Milind220** [comment]
Hey! I'd love to work on improving this. Any suggestions on how this could be improved?
