### ISSUE TITLE
Provide more support for zsh. Currently when running 'python installer' to get Jarvis, if I select option 2, 'Add to bashrc' it says no bashrc found

### ISSUE THREAD

**Issue by Milind220** [sukeesh/Jarvis#912]
This makes sense if one is not using bash and is using zsh I know, but still, I feel like it's a pretty simple error to fix if one knew which file to edit.

**Comment by riju-dc** [comment]
I am picking this up.

**Comment by rijumone** [comment]
I am picking this issue up.

**Comment by riju-dc** [comment]
Submitted PR:
https://github.com/sukeesh/Jarvis/pull/914

**Comment by rijumone** [comment]
Submitted PR: https://github.com/sukeesh/Jarvis/pull/914
