### ISSUE TITLE
No error message displayed for two word commands missing 2nd word

### ISSUE THREAD

**Issue by anaisabel7** [sukeesh/Jarvis#92]
For two (or more) word commands, such as `disable sound` or `decrease volume`, no error or warning message is displayed if only the first word is found in the command passed to Jarvis, such as:
`decrease`
`please, can you decrease`
`decrease my cat, thank you`

**Comment by nashid** [comment]
is this issue still up for grab?

**Comment by StefanosChaliasos** [comment]
No a solution had been merged
