### ISSUE TITLE
[New Feature] Reddit post plugin?

### ISSUE THREAD

**Issue by edricantoine** [sukeesh/Jarvis#931]
Hello, I had an idea for a plugin that can take a subreddit name as user input, and use the Reddit API to fetch post titles, along with their upvote/downvote/comment numbers. I have two questions for this:
First, I know the Reddit API requires authentication to use. How would I handle this when making the plugin, since it requires a specific username/password/API key in the code? 
Second, I am experiencing issues getting the application to run on my local machine. I have opened an issue recently about that, so I would like to have that solved before I begin work on this plugin.
Thank you!

**Comment by pnhofmann** [comment]
> First, I know the Reddit API requires authentication to use. 

For stuff which needs login, you need to ask the user for username / password first time and then you can store it in key vault:
https://github.com/sukeesh/Jarvis/blob/dev/jarviscli/jarvis.py#L244

(it's basically jarvis.save_user_pass('reddit', user, password) and jarvis.get_user_pass('reddit').

At last for dev-branch; on master there currently is only the 'get_data' and 'update_data'

Should an API key be required, I'm currently working on a @require(api_key='reddit') function which would handle everything (but haven't uploaded yet).

**Comment by edricantoine** [comment]
The reddit API also requires a 'personal use script' in addition to the API key. If things get too complicated I may try and find another idea for a plugin using an API that doesn't require (as much) authentication.
