### ISSUE TITLE
Fix gtts?

### ISSUE THREAD

**Issue by JerryBerry12** [sukeesh/Jarvis#936]
I have a espeech voice I want to use instead of the default scary one... How can I change it?

**Comment by pnhofmann** [comment]
Try this code:
https://stackoverflow.com/a/44931699

(Run in Jarvis home folder ``env/bin/activate`` before so you are in Jarvis virtualenv)

If you like one voice better, it you would just need to add this one ``engine.setProperty('voice', voice.id)``-line.
Or yeah, we could add an official option ;).

**Comment by JerryBerry12** [comment]
I actually started this because when I try to do gtts, it shows A big block of code:
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Can you guide me in fixing that?

**Comment by JerryBerry12** [comment]
Can somebody help me?

**Comment by pnhofmann** [comment]
Yeah, would be a good idea to fix ;). We will just need to redirect this output somewhere - probably not that hard... But we warned, voice output currently has some issues...
