### ISSUE TITLE
[New Feature] Image Compressor

### ISSUE THREAD

**Issue by hugofpaiva** [sukeesh/Jarvis#940]
The idea would be to @orlando-pt and I to implement an algorithm to compress images and have them occupy less space after processing.

The use-case will be for the user to ask Jarvis to use Image Compressor and then, input a path to a folder with images or a full image path to be compressed.

**Comment by hugofpaiva** [comment]
We will start working on this as soon as possible.

**Comment by pnhofmann** [comment]
Sure.
For curiosity, do you plan to really implement an own compression-algorithm or use library? Or build something on top of something like Pillow?
In any case, looking forward your contribution ;).

**Comment by Orlando-pt** [comment]
Hello @pnhofmann :wink: 
We are planning to use pillow library to implement this feature. Principally because this library was already one of the dependencies of Jarvis, so we can just reuse it.
