### ISSUE TITLE
[New Feature] Name day

### ISSUE THREAD

**Issue by AirlineDog** [sukeesh/Jarvis#941]
I would like to contribute to this project and thought that this would be a good way to start.
I would like to add a feature that can tell you when is someone's name day and if today or any other given day is someone's name day. 
I will implement it using [this](https://nameday.abalin.net/) api i found.

Since it's my first time contributing here be free to give me any advice.
I will start working on this as soon as possible.

**Comment by pnhofmann** [comment]
Sounds nice ;)
