### ISSUE TITLE
Improve calories plugin

### ISSUE THREAD

**Issue by Papajohn77** [sukeesh/Jarvis#944]
I suggest the following improvements for the calories plugin:
- Not suggesting calorie intake less than 1200 cal for females and 1500 cal for males (Harvard Health Publications suggests women get at least 1,200 calories and men get at least 1,500 calories a day unless supervised by doctors). Instead we can suggest them to increase their activity level.
- Suggesting the appropriate macronutrients (proteins, carbs & fats) for losing or gaining weight.
- Providing some more information to the user.

I would like this to be assigned to me if you agree with the above suggestions.

**Comment by pnhofmann** [comment]
sure, go for it!
