### ISSUE TITLE
[New Feature] Find famous movie quote

### ISSUE THREAD

**Issue by george-kakavas** [sukeesh/Jarvis#946]
Hello, as a first time open source contributor i thought that this feature might be a good start. This feature will search through movie quotes by actors, characters, movies, genres, years and even pieces of quotes using the following [api](https://juanroldan.com.ar/movie-quotes-api/?ref=apitemple#introduction) . Would you like something like that?

**Comment by pnhofmann** [comment]
Hey, Sorry, totally missed this issue. 
Yeah, we allready have this plugin:
https://github.com/sukeesh/Jarvis/blob/master/jarviscli/plugins/movie.py
Your plugin seems to require a bit of a annoying API key.
But if you still want to contribute something, feel free :).
