### ISSUE TITLE
[New Feature] Moon Phase Plugin

### ISSUE THREAD

**Issue by anastasisbak** [sukeesh/Jarvis#949]
Hello, I'm a first time contributor and I would like to develop a new feature that informs the user about the **current phase of the moon** and **how many days are left until the next full moon phase**, in their location. I would like to implement the above feature, using this [API](https://www.visualcrossing.com/resources/documentation/weather-api/how-to-include-sunrise-sunset-and-moon-phase-data-into-your-api-requests/) I found.

Let me know if you are interested on this feature and I will start working on it as soon as possible.

**Comment by pnhofmann** [comment]
Sure!
Look [here](https://github.com/sukeesh/Jarvis/blob/700ea2e8b1f88aca5d5baf5df0103c9ec647fe15/jarviscli/plugins/basketball.py) for an example how you could handle the API key.

**Comment by anastasisbak** [comment]
Thank you for your feedback!
I will start working on the issue shortly.
I may use a script instead of an API in order to calculate the current moon phase. Let me know if that is okay.
