### ISSUE TITLE
[New Feature] Taste dive suggestions

### ISSUE THREAD

**Issue by george-kakavas** [sukeesh/Jarvis#956]
Hello, i would like to add a plugin that will let jarvis give suggestions for films, TV shows, music, video games, and books depending on user input, using the following  [api](https://tastedive.com/read/api) (No api key is needed anymore). For example if the user gives "The Rolling Stones" or "Breaking Bad" as input, jarvis will suggest similar bands,TV series, etc.

I'm open to any suggestions or advices!

**Comment by pnhofmann** [comment]
> No api key is needed anymore

Nice ;)
