### ISSUE TITLE
Jarvis Error! And how to uninstall jarvis and all its dependencies from system

### ISSUE THREAD

**Issue by akhil3417** [sukeesh/Jarvis#958]
This is the output I get when Tryna start Jarvis..M on Arch 

❯ jarvis
No module named 'PyPDF2'
No module named 'pyautogui'
Duplicated plugin workspace!
Jarvis' sound is by default disabled.
In order to let Jarvis talk out loud type: enable sound
Type 'help' for a list of available actions.
193 plugins loaded 7 plugins disabled. More information: status

ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shiva/Jarvis/jarviscli/__main__.py", line 22, in <module>
    main()
  File "/home/shiva/Jarvis/jarviscli/__main__.py", line 15, in main
    jarvis = Jarvis.Jarvis()
  File "/home/shiva/Jarvis/jarviscli/Jarvis.py", line 61, in init
    CmdInterpreter.init(self, first_reaction_text, prompt,
  File "/home/shiva/Jarvis/jarviscli/CmdInterpreter.py", line 366, in init
    self._api.say(self.first_reaction_text)
  File "/home/shiva/Jarvis/jarviscli/CmdInterpreter.py", line 48, in say
    self._jarvis.speak(text)
  File "/home/shiva/Jarvis/jarviscli/Jarvis.py", line 118, in speak
    self.speech.text_to_speech(text)
  File "/home/shiva/Jarvis/jarviscli/utilities/voice.py", line 69, in text_to_speech
    playback.play(audio)
  File "/home/shiva/Jarvis/env/lib/python3.10/site-packages/pydub/playback.py", line 67, in pl
    _play_with_pyaudio(audio_segment)
  File "/home/shiva/Jarvis/env/lib/python3.10/site-packages/pydub/playback.py", line 36, in _p
    stream.write(chunk._data)
  File "/home/shiva/Jarvis/env/lib/python3.10/site-packages/pyaudio.py", line 585, in write
    pa.write_stream(self._stream, frames, num_frames,
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by akhil3417** [comment]
Some more 
~> Hi, what can I do for you?
hello
I could not identify your command...
~> What can I do for you?
music
Sorry, I could not recognise your command. Did you mean:
    * music recognition

**Comment by pnhofmann** [comment]
Better open separate issues in future.

About the lines "ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear (...):
Duplicated #936

About the issue with pyaudio (SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats)
That's not good ;(. And seems to be an upstream issue? Will take a look into it at some later point.

About the "some more" output:
What would be the expected output?

About uninstallation:
Jarvis lives completely in the installation folder (with all it's requirements!). Just remove the Jarvis home folder.
* Should you have installed dependencies manually, uninstall them manually (probably with your package manager)
* Should you have installed the laucher, remove the file /usr/local/bin/jarvis or the line ``export PATH="$PATH:JARVIS_HOME_FOLDER`` in your ~/.bashrc

**Comment by akhil3417** [comment]
Thanks for the response...

~> Hi, what can I do for you?
hello
I could not identify your command...
~> What can I do for you?
music
Sorry, I could not recognise your command. Did you mean:
* music recognition

Why doesn't it recognize the music and the normal talk command as you showed in the video...as music is also mentioned in the help

And I also need to mention that i use pipe wire
