### ISSUE TITLE
[New Feature] QR generator for URLs

### ISSUE THREAD

**Issue by george-kakavas** [sukeesh/Jarvis#962]
Hello, i had this idea for a plugin that creates a QR code for a URL that the user gives as input. I will use the following [api](https://goqr.me/api/) . This api creates a PNG image of the QR ,that Jarvis will save on the directory the user specifies.

**Comment by pnhofmann** [comment]
Go for it!
Alternative would be this library:
https://pypi.org/project/qrcode/
Which works offline but requires Pillow as requirement.

**Comment by george-kakavas** [comment]
Ok, so i'm thinking that Jarvis could use the API if internet connection is available and pillow if the user is offline.But how can i add pillow as requirement so it can be available for every user to import (is included in env\Lib\site-packages not just for me but for anyone)?

**Comment by pnhofmann** [comment]
Would be adding ``pillow`` to this file:
https://github.com/sukeesh/Jarvis/blob/master/installer/requirements.txt

But honestly I'm not 100% sure if I want pillow to be installed with every jarvis instance ;). Which would speak in favor of your implementation.
