### ISSUE TITLE
Apparently virtualenv on Python3 (py -3 -m virtualenv) does not work. Exiting!

### ISSUE THREAD

**Issue by SpandyBoss** [sukeesh/Jarvis#970]
When running setup.bat on windows it gives the following error, kindly guide me thru how to fix it.

Screenshot :- 
![image](https://user-images.githubusercontent.com/77114710/170815504-496d0c14-0ba1-431f-ba6b-15435aec5de0.png)

Thanks

**Comment by eldinesh** [comment]
Try installing virtualenv manually using pip, it'll resolve the issue.

**Comment by eldinesh** [comment]
@sukeesh I have created a pull request for this issue, please check it out, and let me know, about the changes, if it's possible.

Thanks!
