### ISSUE TITLE
Location provider

### ISSUE THREAD

**Issue by pnhofmann** [sukeesh/Jarvis#971]
Build gelocation provider directly into jarvis. Started development here:

https://github.com/pnhofmann/Jarvis/blob/dev/jarviscli/packages/geolocation.py

**Comment by eldinesh** [comment]
I wanna work on it, I'm new to open source contribution. But I'm sure, I'll make it happen. I tried using some modules like, GeoPy and other. I'm getting issues with wifi network, as it uses ip based approach to detect location, so it shows wifi network provider based location. 

is there any way to improve it?
