### ISSUE TITLE
[New Feature] yeelight plugin

### ISSUE THREAD

**Issue by LeonidhaMara** [sukeesh/Jarvis#985]
Hi,
Me and @Manousakis01 had an idea to implement a shortcut for turning on and off the smart lights. Just something handful to impress your friends or to avoid getting up from your desk.

**Comment by Manousakis01** [comment]
@LeonidhaMara  PS: As the Issue names indicates the plugin we preparing is for controlling smart lightning devices by Yeelight. Is the only brand of smart lightning we have available to use and to test.
