### ISSUE TITLE
if I try to return back from cocktail list to jarvis functionality , it close batch and quit the program

### ISSUE THREAD

**Issue by ARaieta** [sukeesh/Jarvis#992]
19.  Rum Toddy
 20.  Spice 75
 21.  Zippy's Revenge
 22.  Zombie
Choose Cocktail:
Please select a number (1 - 22)
Choose Cocktail: 22  
                              ------------------------------------------------------------
                                                ALL YOU NEED for Zombie
                              ------------------------------------------------------------
                                     INGREDIENTS                   MEASURE
                                     Rum                           1 1/2 oz
                                     Gold rum                      1 1/2 oz
                                     151 proof rum                 1 oz
                                     Pernod                        1 tsp
                                     Grenadine                     1 tsp
                                     Lime Juice                    1 tsp
                                     Angostura Bitters             1 drop
Goodbye, see you later!
Terminate batch job (Y/N)? n

**Comment by pnhofmann** [comment]
Can't reproduce :(
