### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MATHEROS5DEV** [sukeesh/Jarvis#995]
C:/Users/HELLO/AppData/Local/Programs/Python/Python39/python.exe e:/A.I/jarviscli/Jarvis.py
C:\Users\HELLO\AppData\Local\Programs\Python\Python39\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - 
defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\HELLO\AppData\Local\Programs\Python\Python39\lib\site-packages\pydub\utils.py:184: RuntimeWarning: Couldn't find ffplay or avplay - 
defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)

**Comment by pnhofmann** [comment]
duplicated #719
